### ISSUE TITLE
Generating a mask

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1015]
Hi @pchlap :),

I stumbled upon the following:

https://github.com/pymedphys/pymedphys/blob/1241924d027163fccdc95750db0c984805bb83d4/pymedphys/tests/experimental/pinnacle/test_pinnacle.py#L187

and I wanted to let you know about the following tool which creates a mask:

https://github.com/pymedphys/pymedphys/blob/1241924d027163fccdc95750db0c984805bb83d4/pymedphys/_experimental/autosegmentation/mask.py#L81-L89

Also wanted to give you a heads up about the following which is able to convert the above mask back into contours:

https://github.com/pymedphys/pymedphys/blob/1241924d027163fccdc95750db0c984805bb83d4/pymedphys/_experimental/autosegmentation/mask.py#L92-L101

Cheers,
Simon

**Comment by pchlap** [comment]
Cool, thanks @SimonBiggs :)
