### ISSUE TITLE
Split up tests into different cases, implement CodeCov

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#102]
So, right now, we have three pipelines, one for each OS. But there is a lot of duplicated work, and a lot of work being done towards the end that could be done relatively quickly.

So I want to firstly remove conda from the testing chain, just use pip instead. Then I want to split the tests up in the following way:

* Docs only on Linux
* Pylint only on Linux
* Written tests + code coverage analysis on Linux
  * It's important that this is only the written tests, we don't want code coverage to tell us we're amazing when it's being fooled by pylint.
* Written tests on Mac
* Written tests on Windows
* Mypy only on Linux

This split will be achieved using the tox package.

**Comment by Centrus007** [comment]
Ready for closing?

**Comment by SimonBiggs** [comment]
Partially, code coverage isn't implemented. Maybe close this one and make a
new issue just for code coverage?
