### ISSUE TITLE
experimental pseudonymisation crashes when sequence is present in data that is listed as an identifying key word

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1034]
When an RT Structure Set contained RequestAttributesSequence pseudonymisation crashed with a KeyError ('SQ').
pseudonymisation recurses in to sequences that are not listed as identifiers.
But there is no strategy (function) for VR of type SQ
Possible fixes are:
1)  strategy to put an empty "value" in to the Sequence
2)  default identifying keywords for pseudonymisation to have *Sequence removed from the list (this is the work around I've implemented programmatically elsewhere):
>
        identifying_keywords_less_sequences = [
            x
            for x in pseudonymise.get_default_pseudonymisation_keywords()
            if not x.endswith("Sequence")
        ]

The result of #2 would be pseudonymisation of the *contents* of the identifying sequence (which might have value)
I'm open to suggestions on which approach to take.
I haven't tried creating a "replace with empty value" approach.

**Comment by SimonBiggs** [comment]
I think the most natural option is that should the anonymisation method not have an entry for SQ then the approach should recurse into SQ and for each dataset within SQ apply the original anonymisation approach.

I believe this is similar to what you implemented already?

**Comment by sjswerdloff** [comment]
yup.  that maps to solution number 2 above.
and that a "validate" feature discussed previously/elsewhere would indicate that an identifying key with VR of SQ is not compatible with the strategy (if someone is customizing their identifying keyword list).
Will get to it this coming week.
Thanks for the feedback.

**Comment by SimonBiggs** [comment]
I don't think it'd hurt to let people define SQ in the strategy. Maybe I
need to give it more thought...

**Comment by sjswerdloff** [comment]
I wasn't saying don't allow people to define SQ in their strategy, just that it could be avoided in the pseudonymisation strategy.
I've implemented both ways in my PR (#1038 )
The default identifying keys for pseudonymisation no longer contain Sequences.
The pseudonymisation strategy now does provide a SQ replacement function (replace with an empty sequence), but that should only get used if the programmer chooses to *add* a Sequence as an identifying key (which they could do one by one, or they could pull in the default keys for anonymisation, and do a set union (or comprehend just the items that end with "Sequence" and append to the list provided from pseudonymisation).
So the default behaviour for pseudonymisation will be "pseudonymise the contents of all sequences", while leaving open the option for a programmer to replace identifying sequences with an empty sequence (although that has DICOM compliance risks if they have type 1 or 2 elements).
So... consistent by default, but flexible in the face of a programmer having a different preference for how to go about dealing with things.

**Comment by sjswerdloff** [comment]
BTW, the approach of replacing an "identifying" sequence (with however many populated sequence items and elements in those sequence items) with an empty sequence (no items) is what the original anonymisation strategy does.  So the PR doesn't introduce any situation that hasn't already been part of anonymisation...
