### ISSUE TITLE
import pymedphys.experimental.xyz forces installing dependencies from other experimental packages

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1035]
>We could make all the slicer like dependencies installable via the extras "slicer" so that they don't come by default, but do come should the user install with "pip install pymedphys[slicer]".

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/issues/962#issuecomment-668243172_

I started with pip install --no-deps pymedphys

my code has:
import pymedphys.experimental.pseudonymisation as pseudonymise
from pymedphys._dicom.anonymise import create_filename_from_dataset
from pymedphys.dicom import anonymise as pmp_anonymise

but at initialisation, I get error messages about various packages that are used in other experimental packages within pymedphys.
I already have some package conflict issues (pyradiomics 3.0 requires pyWavelets <1.0, while pymedphys requires pyWavelets >= 1.0), so I'm trying to minimise what gets installed to avoid further package version conflicts.
 

Is there some way to separate out the runtime requirements so that one experimental package can get what it needs without having to pull in support for the other experimental packages? (No is a fair answer, but don't ask/don't get).

I linked in to the previous comment that showed what looks like the use of package-index-options because I'm wondering if that's applicable here.  
I found:
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
and I suppose pip makes use of setup tools for this extras-optional

**Comment by SimonBiggs** [comment]
Yup, certainly possible. Other modules need to import external packages
from pymedphys._imports instead of importing them directly.

**Comment by SimonBiggs** [comment]
@sjswerdloff I can sort this one out, I'll see if I can give it a punt tonight :)

**Comment by SimonBiggs** [comment]
@sjswerdloff can you try to install within a fresh environment with the following:

```bash
pip install pymedphys==0.33.0dev1
```

Also, I have added a new test that `import pymedphys.experimental` needs to work with no dependencies installed:

https://github.com/pymedphys/pymedphys/blob/fb26477d0de6bfd185b80b42a0692f36d5941d1b/.github/workflows/on-push.yml#L141-L147

Importantly, I have decided that pymedphys will install no dependencies by default. That way, a project like OnkoDICOM can declare pymedphys as a dependency, and it won't automatically pull in the kitchen sink.

If users wish to install pymedphys, the process for them will now become:

```bash
pip install pymedphys[user]
```

If a developer wants to install pymedphys they will now need to either run:

```bash
pip install pymedphys[dev]
```

Or, from within the git repo:

```bash
poetry install -E dev
```

This will be true once the following PR merges:
https://github.com/pymedphys/pymedphys/pull/1036

**Comment by sjswerdloff** [comment]
I'll give it a go first thing in the morning.
