### ISSUE TITLE
VisibleDeprecationWarning problem with jaw

### ISSUE THREAD

**Issue by bianka-m** [pymedphys/pymedphys#1047]
Hi! I tried using the following code:

`imrt_plan_ds = pydicom.dcmread(file)
beam_sequence = imrt_plan_ds.BeamSequence

delivery = pymedphys.Delivery.from_dicom(imrt_plan_ds, fraction_number=1)`

However, the following warning appears when I run the program

`C:\Users\USER\PycharmProjects\Fluence_Map\venv\lib\site-packages\pymedphys\_dicom\delivery\core.py:170: **VisibleDeprecationWarning**: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  jaw = np.array(dicom_jaw)
Traceback (most recent call last):
  File "C:/Users/USER/PycharmProjects/Fluence_Map/fluence_map.py", line 103, in <module>
    delivery = pymedphys.Delivery.from_dicom(imrt_plan_ds, fraction_number=1)
  File "C:\Users\USER\PycharmProjects\Fluence_Map\venv\lib\site-packages\pymedphys\_dicom\delivery\core.py", line 75, in from_dicom
    delivery_data_by_beam_sequence.append(cls._from_dicom_beam(beam, meterset))
  File "C:\Users\USER\PycharmProjects\Fluence_Map\venv\lib\site-packages\pymedphys\_dicom\delivery\core.py", line 172, in _from_dicom_beam
    second_col = deepcopy(jaw[:, 1])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`

**Comment by SimonBiggs** [comment]
Hi @bianka-m,

Would you be able to make sure that the DICOM file is anonymised and then upload it to this GitHub issue by dragging and dropping it onto the comment field?

To anonymise the DICOM file you can run in a command prompt/terminal `pymedphys dicom anonymise path/to/dicom/file.dcm`

And then, you can check that the anonymisation has worked by opening the new file with something like dicompyler (https://www.dicompyler.com/)

**Comment by bianka-m** [comment]
Hi Simon! Here's the anonymised DICOM RTPlan file I'm using 

[NPCA_Anonymised.zip](https://github.com/pymedphys/pymedphys/files/5212087/NPCA_Anonymised.zip)

**Comment by SimonBiggs** [comment]
@bianka-m just a heads up that I have been able to replicate the issue and when I get a chance I'll see if I can fix it in the pull request over at https://github.com/pymedphys/pymedphys/pull/1048

Cheers :)

**Comment by bianka-m** [comment]
Thanks Simon! :)

**Comment by SimonBiggs** [comment]
Hi @bianka-m,

I'm sorry for getting your hopes up. We only have Elekta's at our site, and it seems this code that I mentioned to you is just not ready for prime time when it comes to a Varian machine :(.

So for now, my "fix" has been to provide a "not supported" error message. I don't envisage a fix in the near future :(.

**Comment by bianka-m** [comment]
It's ok! :) I appreciate your effort to help me.

**Comment by SimonBiggs** [comment]
Thanks @bianka-m :)
