### ISSUE TITLE
Run Length Encoding unpacking

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1049]
Yes, there is a Run Length Encoding approach specified in DICOM.
But the standard also says that if the value *never* changes, you can use the RLE approach, and just put it in with the control point with Control Point Index == 0.  
And if it does *ever* change, you need to put in a value in each control point (even if it is all duplicates except for one).

What the code tells me is that the function returns a list of values, with the list being of length "Number of Control Points", and if the value is itself a list, you are going to receive a list of lists.
I encourage you to put in docstring that says something on the order of
"""returns a list of values, one list item per control point, unpacking any run length encoding
"""

Also, will the values returned be of the conceptual type most closely represented in Python, e.g.
a floating point value if the DICOM Element has a VR of DS, or will it be literally of the DICOM VR (so DS comes back as a string)?
If the attribute is a Sequence (VR is SQ), is the return a list of dataset or a list of iterables of the Sequence Item?

I think it will be very useful for it to be clear what the function returns for a variety of attributes.
While I'm not a fan of changing signatures, the name of the function suggested to me that it was trying to get a single value.  I'm not sure of the python terminology, but you are slicing across a dimension (the attribute axis?) (and getting back something that is of the dimension "dimension of attribute value + 1" (where the 1 comes from the control point/index axis).  For something like a Gantry Angle, the value is a scalar and has dimension 0.
If this was new code, I'd push for a name that more clearly reflects that.

_Originally posted by @sjswerdloff in https://github.com/pymedphys/pymedphys/pull/1048#discussion_r487469683_

**Comment by SimonBiggs** [comment]
> While I'm not a fan of changing signatures, the name of the function suggested to me that it was trying to get a single value. I'm not sure of the python terminology, but you are slicing across a dimension (the attribute axis?) (and getting back something that is of the dimension "dimension of attribute value + 1" (where the 1 comes from the control point/index axis). For something like a Gantry Angle, the value is a scalar and has dimension 0.
> If this was new code, I'd push for a name that more clearly reflects that.

Given this is an internal function that is not exposed via the API I am more than happy to adjust function signatures and naming. In fact, if a better name is available, if a better signature is thought of, I would prefer to lean towards being able to change. That way we are free to optimise and improve the clarity of the code.

So on that note, happy and keen to make these adjustments.

**Comment by sjswerdloff** [comment]
the current function name is: **get_cp_attribute_leaning_on_prior**
How about
get_run_length_decoded_attribute_for_all_cp ?
or make it more generic and
rle_attribute_to_list(attribute, my_sequence)
or
rle_attribute_to_dict(attribute, my_sequence, key_attribute)
