### ISSUE TITLE
nnUNet

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1078]
https://arxiv.org/abs/1809.10486

https://github.com/MIC-DKFZ/nnUNet

https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/inference/pretrained_models/download_pretrained_model.py

**Comment by pchlap** [comment]
Hi @SimonBiggs ,

I've been using the nnUNet quite a bit, its a really nice framework and you can start getting really good results out of the box on your own data. Gives a really good baseline of the quality of segmentation thats possible to achieve on your data.

**Comment by pchlap** [comment]
And their pretrained models actually work really well as well (at least the ones I've tried) :)

**Comment by SimonBiggs** [comment]
Yup, and they're currently the leaders on the decathlon challenge:

https://decathlon-10.grand-challenge.org/evaluation/challenge/leaderboard/

Certainly if one wants to improve segmentation, from what I can see, at the moment it should probably start from their framework.

I've hit a little bit of a speed bump (I probably did something silly). I'm going to dive into it a bit more maybe Thursday night, but I explained my issue over at:

https://github.com/MIC-DKFZ/nnUNet/issues/334

Any ideas where I might have tripped up?

**Comment by pchlap** [comment]
Hmmmm nothing immediately obvious to me. The only thing I am wondering is why it has detected the patch size as 256,64...? I would have expected it to be 64,64 since that is what you have scaled your images down to?

**Comment by pchlap** [comment]
Hi @SimonBiggs, have you seen this implementation of the nnUNet?
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Segmentation/nnUNet

I haven't tried it out yet myself, but perhaps this could help put together an example which is faster to train and works on scaled down data?

**Comment by SimonBiggs** [comment]
Actually... I have already had success with the following notebook:

https://colab.research.google.com/github/pymedphys/pymedphys/blob/c5fa262fd5eb927dcbbe1fced3469f13ad7f1a96/prototyping/unet.ipynb

So I imagine that'll be the avenue I'll continue down.

**Comment by pchlap** [comment]
Very cool!

**Comment by SimonBiggs** [comment]
> Very cool!

Yeah 🙂. My hope is to flesh it out with some decent tutorial text, and then even make a YouTube video teaching people what all the components are and helping people make it themselves.
