### ISSUE TITLE
Create a binary

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1084]
Use the following standalone Python executables:
https://github.com/indygreg/python-build-standalone

Choose an installation creation framework that enables auto-updating that way a single installer can be provided and it will be able to always be used to get the latest version. Having a single binary that can be used to install the latest version means that the binary only needs to be signed once, and that binary can build up trust over time on Windows and MacOS.

An example bundler that enables auto-updating is https://www.electron.build/auto-update.

Qt Installer Framework is also promising. It allows the creation of an online installer and an offline installer:
https://doc.qt.io/qtinstallerframework/index.html

Ideally the binary creation process will have the installed files not be obfuscated (users should still be able to open up the Python files at the install location), also, it should allow for arbitrary artefact inclusion and build chains to allow for the inclusion of non-python based tooling.

**Comment by SimonBiggs** [comment]
@sjswerdloff what are your thoughts about using https://doc.qt.io/qtinstallerframework/index.html with https://github.com/indygreg/python-build-standalone executables being used within the build?

**Comment by sjswerdloff** [comment]
I don't think the qt installer framework supports construction of python bundled  executables. Python_ build_standalone looks promising.

While having a single executable seems like a very satisfying approach, it seems like a gui that hid the complexity of installing python, pyenv, poetry, non python packages/libraries, and then has poetry do the heavy lifting on python package installation would be fine (with a script or batch file that the user invokes to start the application or command line to tee up the virtual environment).  Maybe that's what you were thinking of with qt installer framework? 

It might be overkill, but construction of a fully populated docker / container that's ready to go might be the way to ensure that the application will run properly.  And then the requirement becomes 'have docker'.   I think that also makes it feasible to inherit a docker environment and layer additional tooling/ software on top of that. 

It's either 'make it dirt simple to install' and have a heavyweight download, or 'be ready to spend time on a command line' , but the installation will be as lightweight as possible' 

In a commercial environment it tends to start with the latter and rely on knowledgeable installer personnel and then evolve towards middle ground.

**Comment by SimonBiggs** [comment]
I have found that both the "docker" solution, and the "GUI hiding pip install" solution to at the end of the day not solve the need for user-friendly. An example in each camp, Docker on Windows can't access network paths, also it is not so simple for it to access the host environment. GUI hiding pip has some nasty trip ups too. Some hospitals/companies have proxy set ups and pip will error out if there is any man-in-the-middle stuff going on.

At the end of the day, it is certainly better, if one is to make a binary installable, to package everything in the original installation. I wouldn't ask an online installer to call pip, instead I would get it to download a new tested bundle.

My thought was to have a GitHub deployment CI download a `python_build_standalone` for each platform call this the deployment environment. Then within the "build environment" use poetry to create a requirements.txt pin file and build a pymedphys wheel. Use pip within the deployment environment to install the pinned packages and the pymedphys wheel. Then bundle up all of the files, standalone python, dependencies, and pymedphys into an installation executable with the Qt Installer Framework.

Lastly the Qt Installer Framework could do a few neat things like add the pymedphys CLI to the path, optionally register some file extensions (https://doc.qt.io/qtinstallerframework/qt-installer-framework-registerfileextension-example.html), create a start menu item (https://doc.qt.io/qtinstallerframework/qt-installer-framework-startmenu-example.html) and provide options to only install some of the pymedphys dependencies (https://doc.qt.io/qtinstallerframework/qt-installer-framework-dependencies-example.html) and provide a way for users to run the installer to update the installation:

https://doc.qt.io/qtinstallerframework/qt-installer-framework-online-example.html#providing-updates

**Comment by sjswerdloff** [comment]
All in one is good (that allows for sneakernet distribution in a bandwidth poor environment, as well as "guaranteed contents").
I would put "only install some of the pymedphys dependencies" low on the list of priorities.  If someone wants a lightweight installation, this isn't the approach (better for them to build a python virtual environment, and then use pip pymedphys, and incrementally add what they need, e.g. pip pymedphys[dicom]).
I misunderstood what python_build_standalone was offering.  I thought it was an alternative to PyInstaller, py2App or py2Exe.  Instead, it's a "python distro builder".  I'm not sure if someone can install different python distros (e.g. 3.7 vs. 3.9) side by side using python_build_standalone.
But overall, I can see the approach you specify having a lot of merit.

**Comment by SimonBiggs** [comment]
I've been undergoing a bit more research. For now just focused on a Windows installation. I'm currently leaning towards going down the MSIX path:

https://docs.microsoft.com/en-us/windows/msix/overview

**Comment by SimonBiggs** [comment]
Hi @sjswerdloff and @Matthew-Jennings,

I thought I'd let you know that I think I may have got a "zip bundle" working. So, currently the zip has a `launch_pymedohys.bat` along with a python directory. If I've done everything correctly, you should be able to download the zip file, extract it, and then run `launch_pymedphys.bat`, and hopefully, the GUI should boot up.

The zip file bundle can be downloaded from:

https://github.com/pymedphys/pymedphys/releases/download/v0.34.0/pymedphys-v0.34.0.zip

Just to preempt the question, I suspect @Matthew-Jennings may ask "why not use pyinstaller". My reasoning is that I don't want the Python imports to be filtered out. Down the line, I'd like users to be able to create their own streamlit apps on their own machine, and have a means (like a "plugin") that they can be also included within their version of the GUI index. As such, I want all of the Python libraries available in their unaltered state, so that users can use those libraries in their native format (without pyinstaller doing its strip out business).

Now that I have made a zip, I'd like to automate this process of "zip building", and then include a CI task that makes the zip, and then runs the GUI tests on the bundle.

Another task is to make it so that an MSIX (windows store app) can be built from this. I need to learn how to do that though...

**Comment by SimonBiggs** [comment]
So, I've had a bit of a win. I have replaced the link above with a new one. This time, it is a single `.exe` that when double clicked takes a bit longer the first time round, but it does eventually boot the GUI. When run it extracts an embedded Python to the current directory, as well as a `pymedphys.bat` which can be used to run all of the pymedphys CLI commands.

Subsequent clicks to the `.exe` will boot the GUI with only a small delay.

The download link is at:

https://github.com/pymedphys/pymedphys/releases/download/v0.34.0/PyMedPhysGUI-v0.34.0.exe

In the end, I actually did use pyinstaller... but not in the traditional way. The pyinstaller script was quite small:

```python
import os
import subprocess
import sys
import pathlib
import zipfile
import shutil


def boot_streamlit_app(installation_path):
    subprocess.check_call(
        f'./python.exe -m pymedphys gui', cwd=installation_path,
        shell=True
    )


def main():
    cwd = pathlib.Path(os.getcwd())
    installation_path = cwd.joinpath('python-embed')

    if installation_path.exists():
        boot_streamlit_app(installation_path)
    else:
        pyinstaller_temp_dir = pathlib.Path(sys._MEIPASS)
        data_path = pyinstaller_temp_dir.joinpath("data")

        for filename in ["resolve_path.cmd", "pymedphys.bat"]:
            shutil.copy(data_path.joinpath(filename), cwd.joinpath(filename))

        python_zip = data_path.joinpath("python-embed.zip")

        with zipfile.ZipFile(python_zip, 'r') as zip_ref:
            zip_ref.extractall(cwd)

        boot_streamlit_app(installation_path)


if __name__ == '__main__':
    main()
```

It's only job is to extract the full-featured embedded Python distro to the current directory if it doesn't exist already, and then use that embedded Python version to boot up the GUI.

I then built the pyinstaller script with:

```bash
wine pyinstaller pymedphys_gui.py --add-data "python-embed.zip;data" --add-data "pymedphys.bat;data" --add-data "resolve_path.cmd;data" --onefile
```

The `python-embed.zip` was created by downloading the Windows embedded Python and installing `pymedphys[user]` within it.

So there we go! A binary! Now I just need to set up continuous build, test, and deployment of said binary :).

**Comment by SimonBiggs** [comment]
Binary now made in CI/CD :)

See https://github.com/pymedphys/pymedphys/pull/1192
