### ISSUE TITLE
TRF header.py improvements

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1096]
Comments pulled out of the following PR:
https://github.com/pymedphys/pymedphys/pull/1095#pullrequestreview-508805157

----

`decode_header` needs docstring
and it would be helpful to have comments that discuss what the various regex pieces were expected to look like, perhaps with an example.
Or a reference to any trf file format documentation...

_Originally posted by @sjswerdloff in https://github.com/pymedphys/pymedphys/pull/1095#discussion_r505009278_

---

what other date formats might be expected?
Dutch timestamp format is presumably not really just Dutch, but might include other parts of Western Europe.  Which then raises the question regarding what other region formats might be expected.  Might Eastern Europe use a different date format?  Different places in Asia (Japan, Korea, China)?

Is anyone concerned about rolling over the century mark (previously known as the Y2K problem)?

Further down, the bytes are being decoded as ascii.
but the regex that got parsed includes up to \xFF, while ascii is only up to \xEF or maybe \xF0.
so it is really ascii or is it Latin1 (or iso-8859, or something similar)?

_Originally posted by @sjswerdloff in https://github.com/pymedphys/pymedphys/pull/1095#discussion_r505013097_

**Comment by SimonBiggs** [comment]
Probably the only two pieces I'd be willing to adjust without having TRF files that represent the issue in my hands would be to change the decoding from "ascii" to "utf-8" and add in the docstring. For everything else, I'd rather not predict what files *might* be out there, and instead have them provided and then adjust accordingly.

**Comment by SimonBiggs** [comment]
> and it would be helpful to have comments that discuss what the various regex pieces were expected to look like, perhaps with an example.

I'd agree here, but would rather instead lean on official documentation if it was available. At the end of the day this regex has been chosen to be the minimum subset that "works" across every TRF file I have ever seen.

**Comment by sjswerdloff** [comment]
Fair enough...

**Comment by SimonBiggs** [comment]
> Fair enough...

I did provide examples in the docstring though
