### ISSUE TITLE
expand and improve the Profile() class

### ISSUE THREAD

**Issue by kingrpaul** [pymedphys/pymedphys#111]
- [x]  incorporate changes made in support of GUI
- [ ]  add short bio or link to labs page
- [ ]  expand/improve test-bed to include new film / profiler data sets
- [ ]  address Profile segmentation breaking with low-resolution profiles
- [ ]  normalize_x produces visibly bad results w/profiler film calib test scan 
- [ ] attempt to get Profile() into -> pymedphys-proper
- [ ] from_raystation_plan()
- [ ] from_rfa_ascii()
- [ ] from_pinnacle_ascii()
- [ ] apply_calibration()
- [ ] to_rfa_ascii()
- [ ] to_snc_profiler()

https://github.com/pymedphys/pymedphys/pull/130
https://github.com/pymedphys/pymedphys/tree/expand-profile

**Comment by SimonBiggs** [comment]
Heya Paul, those pins pin the issues for everyone.

**Comment by kingrpaul** [comment]
> 
> 
> Heya Paul, those pins pin the issues for everyone.

Oops. Sorry.

**Comment by SimonBiggs** [comment]
All good :). Handy feature though. I think I might make use of it at some
point.

**Comment by SimonBiggs** [comment]
Closing this. Can reopen on further activity in this direction.
