### ISSUE TITLE
unable to find TRF files within diagnostic backup

### ISSUE THREAD

**Issue by chop-shape** [pymedphys/pymedphys#1110]
Hi, Simon. I can not find the trf files in the SDD backup. Do you know why?
The linac is Axesse with Agility head.

![integrity](https://user-images.githubusercontent.com/47208071/97667648-54de6680-1abb-11eb-8e0f-132533c00762.JPG)
![SDD](https://user-images.githubusercontent.com/47208071/97667652-56a82a00-1abb-11eb-9461-56265d4ac71e.JPG)

**Comment by SimonBiggs** [comment]
Hi @chop-shape,

That is interesting. I've personally never seen the diagnostic zips of the axesse machines. There may be options if you discuss with Elekta to retrieve the TRF files via an alternative approach.

Is there someone at Elekta you might be able to discuss this with?

**Comment by chop-shape** [comment]
Perhaps the version of integrity is too low (3.0) ?

**Comment by SimonBiggs** [comment]
Hi @chop-shape,

We have successfully extracted TRF files for diagnostic zips from both integrity version 3 and 4...
