### ISSUE TITLE
convert_patient_name_from_split() does not support middle initials

### ISSUE THREAD

**Issue by mchamberland** [pymedphys/pymedphys#1137]
The function fails if the patient has a middle initial (as far as I can tell!).

So if the DICOM has the name as:

LASTNAME^FIRSTNAME^MIDDLEINITIAL

it fails. But this works:

LASTNAME^FIRSTNAME

This is on pymedphys 0.34.0-dev8.

**Comment by SimonBiggs** [comment]
This one "should" fail gracefully if it can't pretty print it. Can you send
through a screenshot of what the GUI looks like during this error?(GitHub
lets you drag and drop pictures into comments)

**Comment by mchamberland** [comment]
Sorry, I should have been more explicit in my error report (it's been chaotic around here!).

I get a TypeError:

`TypeError: convert_patient_name_from_split() takes 2 positional arguments but 3 were given`

With the following Traceback:

> File "c:\users\m310767\appdata\local\continuum\anaconda3\envs\py3\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
>     exec(code, module.__dict__)
> File "C:\Users\m310767\AppData\Local\Continuum\anaconda3\envs\py3\Lib\site-packages\pymedphys\_gui\streamlit\mudensity\main.py", line 1197, in <module>
>     main()
> File "C:\Users\m310767\AppData\Local\Continuum\anaconda3\envs\py3\Lib\site-packages\pymedphys\_gui\streamlit\mudensity\main.py", line 1109, in main
>     advanced_mode,
> File "C:\Users\m310767\AppData\Local\Continuum\anaconda3\envs\py3\Lib\site-packages\pymedphys\_gui\streamlit\mudensity\main.py", line 678, in get_input_data_ui
>     **previous_results,
> File "C:\Users\m310767\AppData\Local\Continuum\anaconda3\envs\py3\Lib\site-packages\pymedphys\_gui\streamlit\mudensity\main.py", line 388, in dicom_input_method
>     patient_name = utl_patient.convert_patient_name(patient_name)
> File "c:\users\m310767\appdata\local\continuum\anaconda3\envs\py3\lib\site-packages\pymedphys\_utilities\patient.py", line 36, in convert_patient_name
>     patient_name = convert_patient_name_from_split(*patient_split)

**Comment by mchamberland** [comment]
![MU Density TypeError](https://user-images.githubusercontent.com/1675666/98175197-1b936580-1ec4-11eb-9623-47f2169a3534.png)

**Comment by SimonBiggs** [comment]
Yup, I'll see if I can take a shot at fixing these tonight once the kids are in bed.

**Comment by sjswerdloff** [comment]
@SimonBiggs I'm on it.
The fix is done already, I'm just adding a comprehensive test for it.
The short answer is:
change
>patient_name = convert_patient_name_from_split(*patient_split)

to
>patient_name = convert_patient_name_from_split(*patient_split[0:2])

**Comment by SimonBiggs** [comment]
Awesome @sjswerdloff, thank you :).

If you're keen, it might be worth making a dev release for @mchamberland to test out.

The most recent dev release is dev9, https://pypi.org/project/pymedphys/#history so, a new dev release would be dev10.

And then, as long as a PyPI API key is saved on the local machine poetry can be used to build and publish the proposed fix for the user to give feedback on (see details over here regarding API key and publishing):

https://github.com/pymedphys/pymedphys/issues/1122

**Comment by sjswerdloff** [comment]
I branched off master/main, not the stack, so I think specifying dev10 might result in a merge failure (not a problem, just a heads up/question) when the last of the latest stack gets merged.
I'll try to do the release, but I'm going to start with just getting the fix approved and merged to master/main

**Comment by SimonBiggs** [comment]
> I branched off master/main, not the stack, so I think specifying dev10 might result in a merge failure (not a problem, just a heads up/question) when the last of the latest stack gets merged.
> I'll try to do the release, but I'm going to start with just getting the fix approved and merged to master/main

Yup, all good. Merge conflicts there do often occur and are okay. The version he's running does require the "bare minimum config" PR. So he likely won't be able to test it out until the stack merges.

**Comment by sjswerdloff** [comment]
>The version he's running does require the "bare minimum config" PR. So he likely won't be able to test it out until the stack merges.

Without the name of the branch, its very hard to figure out what branch to merge in to for said one off test release.
However, I will not delete the fix branch, so if you want to merge that in to some other test branch, it should be feasible (and not too onerous).  In theory, (ultimately) merging twice should not result in a conflict that can't be automatically resolved.

**Comment by SimonBiggs** [comment]
Yup, all good. There was a bit going on with that "stack"... not sure if it was more helpful or painful. Might be worth a 'post-mortem' :). Hopefully the stacks almost in, so the new master will be up to date anyway.

**Comment by sjswerdloff** [comment]
Closed via:
enforce / reduce to two or fewer name components in patient name conversion utility with tests #1144

**Comment by SimonBiggs** [comment]
Hi @mchamberland,

Would you be able to confirm that the latest dev build fixes this for you?

```
pip install pymedphys[user]==0.34.0-dev10
```

**Comment by mchamberland** [comment]
Yup, this fixed it. Thanks a lot!

**Comment by SimonBiggs** [comment]
Awesome @sjswerdloff to thank for this one :)
