### ISSUE TITLE
Delivery core does not support {'MLCX', 'ASYMY', 'ASYMX'} even though ASYMX is just bogus in certain cases

### ISSUE THREAD

**Issue by mchamberland** [pymedphys/pymedphys#1138]
When exporting an Agility plan from Pinnacle, the DICOM includes MLCX, ASYMY, and ASYMX, even though the ASYMX values are just bogus.

Would be nice if pymedphys could just ignore the ASYMX values and use the MLCX and ASYMY.

Perhaps a check that the DICOM came from Pinnacle? For example, (0008,1090) shows up as "Pinnacle3" when we export DICOM from Pinnacle.

**Comment by SimonBiggs** [comment]
Yeah, this one is a "safety assertion". I don't want my code running off
and doing something I haven't planned for. Unless I have the appropriate
testing data I don't want to override this one.

Are you able to zip up a small basic delivery where you have a pinnacle
dicom plan and the corresponding TRF file? Possibly best to use a something
simple like a 10x10 100 MU field, just so the TRF file is small, but really
anything will do (as long the DICOM file doesn't have anything identifying
in the header)

**Comment by SimonBiggs** [comment]
@mchamberland I'm actually planning on opening up this code to make it handle the MRI Linac today as a part of a bigger GUI rework:

https://github.com/pymedphys/pymedphys/pull/1120

If you are in a position to send through a DICOM TRF pair today I should be able to hit two birds with one stone.

**Comment by mchamberland** [comment]
@SimonBiggs  Thanks, Simon! Yes, I assumed this was done out of an abundance of caution, rightly so.

Let me see if I can get something out to you.

**Comment by SimonBiggs** [comment]
Here's an issue to track the restriction for both of its cases (that I currently know of):

https://github.com/pymedphys/pymedphys/issues/1142
