### ISSUE TITLE
Relax DICOM constraints for two cases the MRI Unity Linac, and Pinnacle exports

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1142]
There are cases that would map appropriately to the Delivery object that currently are blocked from doing so:

* MRI Unity Linac swaps MLCX and ASYMY with MLCY and ASYMX.
* Pinnacle exports an ASYMX and an ASYMY even though only ASYMY is used.

A good set of testing data between TRF and RT DICOM plans are required in order to relax this constraint. If you have one of these systems, please create a small simple off-axis DICOM plan and deliver this on the Linac and then provide the corresponding RT Plan DICOM file and TRF file in a zip attached to this issue.

**Comment by mchamberland** [comment]
@SimonBiggs I have a TRF / DICOM pair for the case of X+ASYMY+MLCX. Tomorrow, I should also have a pair for ASYMX+ASYMY+MLCX.

Unfortunately, I can't upload right now. Due to the network issues at work, I thought I could bring them home on an encrypted USB drive. Of course, the drive does not work on my Mac or on my Windows VM.

I'll share with you tomorrow.

**Comment by mchamberland** [comment]
Here is a case with X, ASYMY, and MLCX. I will get the other case later today (hopefully!).

[pinnacle_x_mlcx.zip](https://github.com/pymedphys/pymedphys/files/5495372/pinnacle_x_mlcx.zip)

**Comment by SimonBiggs** [comment]
Awesome. And for the time being, are you able to use pydicom to make a script to simply delete ASYMY from the DICOM files? That way you can still March forward...

My thought to fix this for the pinnacle case is to do the following. If there are both ASYMX and ASYMY then do a check to make sure that the travel of ASYMX is never closer to the central axis than the most open MLCX pair. That way, I've essentially checked that for that DICOM file the ASYMX jaws are not doing any collimation.

From there I can proceed to either ignore ASYMX, or raise an error saying that for the time being collimation by both ASYMX and MLCX is not supported.

**Comment by SimonBiggs** [comment]
Also, at this stage, I'll probably give this a punt on Saturday night Australia time.

**Comment by mchamberland** [comment]
That’s a good idea. I’ll try that. 

And I believe your check would work.

**Comment by SimonBiggs** [comment]
Hi @mchamberland,

That data was really helpful. Thanks @mchamberland. If you can also do something similar for the `ASYMX` case that'd be awesome.

I have opted to go the route that presents the user with the error message, and then allows the user to flip a switch for that session that turns that error off.

Could you install the following and let me know how that goes for you?

```
pip install pymedphys[user]==0.34.0-dev11
```

That'd be awesome. Thanks :).

Cheers,
Simon

**Comment by mchamberland** [comment]
@SimonBiggs I will test on Monday and also you a test case for the ASYMX case. I needed the weekend off after 12 straight days at work! 😆

**Comment by SimonBiggs** [comment]
Awesome :) thanks Marc. Make sure not to burn out.

**Comment by mchamberland** [comment]
@SimonBiggs  Here's the ASYMX, ASYMY, and MLCX case. It's a simple step-n-shoot, with two control points. Let me know if any issues with it.

[pinnacle_asymx_mlcx.zip](https://github.com/pymedphys/pymedphys/files/5513093/pinnacle_asymx_mlcx.zip)

**Comment by mchamberland** [comment]
@SimonBiggs version 0.34.0-dev11 seems to be working for me! When I find time, I'll try a couple of other deliveries. Thanks a lot!

**Comment by SimonBiggs** [comment]
Given the override nature of that fix posted there's a request to have an
audit trail. Potentially a name going into the UI when the override is
about to occur. Maybe displaying the override on the pdf created,
potentially logging it somewhere else.

Do you have any thoughts on how you think this might work best for your
centre?

**Comment by mchamberland** [comment]
At this point, not really. All of your suggestions sound reasonable to me: name in UI, print on PDF, etc.

**Comment by SimonBiggs** [comment]
Another thought is that potentially within the config file I can make an
option to provide support for different formats.

An example could be, supported combinations:

configuration: [ASYMX, ASYMY, MLCX]
mlc: MLCX
jaw: ASYMY
ignore: [ASYMX]

configuration: [X, ASYMY, MLCX]
mlc: MLCX
jaw: ASYMY
ignore: [X]

That way, if those predefined cases are seen it will support those without
override by following the rules provided in the config file.

...not sure. Still thinking on this one.

**Comment by SimonBiggs** [comment]
On further thought, I think my first idea of checking to see if that extra
jaw is coming in more than the MLCs is the way to go. No extra config
needed. An error will only be raised if there actually is an issue, and
people aren't getting "override fatigue" getting used to overrides as the
norm...

**Comment by SimonBiggs** [comment]
This is to be addressed using machine characterisation pulled from Mosaiq SQL. Will track this issue within https://github.com/pymedphys/pymedphys/issues/1285.
