### ISSUE TITLE
pseudonymise is breaking the app because of pointing to a download directory

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1152]
> pseudonymise is breaking the app because of pointing to a download directory
> I think that can be corrected relatively easily by removing the part attempting to make a directory there.
> And might as well remove the code that assumes files instead of BytesIO for intermediate steps.

Yup, I think that should be undergone in a separate PR though. Key aim here is to move to lib/pymedphys and make sure everything works the same as before.

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/pull/1151#issuecomment-723339268_

**Comment by sjswerdloff** [comment]
streamlit app no longer crashes on streamlit.io host
pseudonymise app ran on a small set of CT and produced appropriate zip.

**Comment by SimonBiggs** [comment]
Awesome :) :)

**Comment by SimonBiggs** [comment]
There's also room to have some "post merge" tests that use Selenium (
https://www.selenium.dev/) against the share.streamlit.io hosted
application.

That way we can be doing a subset of testing in the live hosted environment
that users see...
