### ISSUE TITLE
Problem getting gamma example jupyter notebook on binder to work (clicking through)

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1158]
<img width="1249" alt="Screen Shot 2020-11-08 at 8 55 47 PM" src="https://user-images.githubusercontent.com/16871837/98459990-e9a43b00-2204-11eb-92f9-f11925cf414a.png">

https://mybinder.org/v2/gh/pymedphys/pymedphys/main?urlpath=/lab/tree/docs/howto/gamma/from-dicom.ipynb

when clicking on the Binder badge (below is the text from the online documentation)
This page was generated from docs/howto/gamma/from-dicom.ipynb. Interactive online version: Binder badge

**Comment by SimonBiggs** [comment]
Yup, I suspect that would have broken when I added `requirements.txt`. Potentially it may be better to have a colaboratory link instead...

**Comment by sjswerdloff** [comment]
I saw some discussion on the email list and wandered through to understand the situation better.
It seems like having a streamlit GUI around a "stick your data here" version of the example might have significant value (same charts and reports, but with the users uploaded data).
I don't have an itch to scratch on this, just commenting...

**Comment by SimonBiggs** [comment]
@sjswerdloff what do you think about the following badge instead?

https://5fa7be69952d470008df72fd--pymedphys.netlify.app/howto/gamma/effect-of-noise.html

**Comment by SimonBiggs** [comment]
> It seems like having a streamlit GUI around a "stick your data here" version of the example might have significant value (same charts and reports, but with the users uploaded data).

Yeah, I agree, a Gamma GUI would be quite nice/helpful. Certainly also as we mature the share.streamlit.io link I can envision that becoming quite embedded within the docs. In fact... the streamlit API docs is actually a streamlit app itself:

https://docs.streamlit.io/en/stable/api.html

I am certainly a fan of living documentation... Having the docs themselves include streamlit interactivity would be quite neat... not overdone, but just enough to give little mini demos here and there inline.
