### ISSUE TITLE
Difficulties with Poetry and Anaconda

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1164]
Hi @SimonBiggs and all,

I've been having some troubles with [this section of the Windows Contributor Setup page](https://docs.pymedphys.com/howto/advanced/setup-win.html#install-the-development-version-of-pymedphys-and-pre-commit); installing `pymedphys` using `poetry`.

If I try to run `poetry run pre-commit install` within a fresh conda environment (`pmp`), it fails complaining of a broken environment. I've tried searching for a solution, so far to no avail; e.g. I've tried disabling virtual environment creation by `poetry`, telling `poetry` where the env is, etc.

There do seem to be a fair amount of complaints floating around regarding compatibility between `poetry` and `conda`. I could avoid using `conda`, but installing Python using Anaconda _is_ a recommendation in the pymedphys docs, and it would take quite a bit of work for me to standardise all my other projects away from `conda` (some use specific conda packages, and I've sometimes had trouble with the pip equivalents).

I'm able to run `poetry run pre-commit install` within the `base` conda environment, but even then I have trouble running `poetry run pymedphys dev docs --live`. I get `AttributeError: module 'sip' has no attribute 'setapi'`. This might be unrelated.

Has anyone else had any luck installing `pymedphys` within a conda env?

**Comment by SimonBiggs** [comment]
Hi @Matthew-Jennings,

Thanks for the heads up. I personally have swapped completely away from conda and I have been using `pyenv-win` and `pyenv`. As such I haven't been exposed to any recent conda issues.

As an interesting side step, does `pip install -r requirements.txt` within that conda env work? There has been an attempt to have a `poetry`-less option, and this should be able to extend to development as long as I make a `requirements-dev.txt`.

Alternatively, if going the poetry route, what if you don't activate your conda env at all, install poetry using the base conda environment, then run the following to allow poetry to put the virtual environment within the pymedphys dir:

https://github.com/pymedphys/pymedphys/issues/1114

And then essentially let poetry manage the venv. Does that work? Or is that what you've already tried and described above?

**Comment by Matthew-Jennings** [comment]
I tried with your new `requirements-dev.txt` and got the following error that terminated installation:

`ERROR: Cannot uninstall 'terminado'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

Note that this was within a fresh conda environment.

Poetry install seemed to work in `base`, but with no venv. I'm just cleaning up `conda base` again to try poetry's own venv handling as per your suggestion. I say "seemed to work" because I can't build the live docs even after your recent fix, which for me just stopped the build error from looping!

**Comment by Matthew-Jennings** [comment]
Update: poetry seems to work fine in `base` within it's venv. :)

**Comment by SimonBiggs** [comment]
> Update: poetry seems to work fine in `base` within it's venv. :)

Awesome :) glad to hear :). Do you think there's anything we should update the Windows contributor docs with in light of this?

**Comment by Matthew-Jennings** [comment]
> Awesome :) glad to hear :). Do you think there's anything we should update the Windows contributor docs with in light of this?

It might take a little more thought. One one hand, Anaconda users would still prefer a `pymedphys` conda environment, rather than a poetry one, for consistency across their other projects and associated environments. But on the other hand, I don't actually know how common Anaconda use is (among medical physicists), especially its "venv" functionality. E.g. although we use the Anaconda Python at the RAH, most don't bother with (conda) envs - to their peril, I'd cheekily add!

With that in mind, we could either:

- note possible issues with `pymedphys` installation within a conda environment and the (imperfect) workaround we've found, or
- avoid recommending Anaconda altogether

I personally do think it'd be best if we could support installation of `pymedphys` within a venv of some kind, and wrap it in a solution that would support other projects in other envs in a consistent way. Use of venvs is good practice, and many users and possible contributors may not use them. To the extent PyMedPhys has an educational component to its vision, maybe this is something to think about?

**Comment by SimonBiggs** [comment]
I mean, I find that in the last two or so years with all the extra funding and attention pip is getting, as well as the reliable community wheel builds it has become quite beautiful and seamless.

For example, I'd be very surprised if in a clean Windows environment the following didn't work:

Install Python with the official installation exe:

https://www.python.org/ftp/python/3.8.6/python-3.8.6-amd64.exe

Download pymedphys-main.zip and extract it:

https://github.com/pymedphys/pymedphys/archive/main.zip

Then within a command prompt within the extracted pymedphys run

```
python -m venv .venv
.\venv\Scripts\activate
pip install -r requirements-dev.txt
```

The first class virtual environment support that the Python ecosystem has built in is amazing...

**Comment by Matthew-Jennings** [comment]
So scrap Anaconda?

**Comment by SimonBiggs** [comment]
> So scrap Anaconda (pretty happy to)?

I have...

**Comment by Matthew-Jennings** [comment]
Assuming we still recommend an environment manager, what would you suggest?
- `pyenv-win`?
- `virtualenv`?
- `pipenv`?
- or stick with native `venv`?

Or not recommend an environment manager at all?

**Comment by SimonBiggs** [comment]
There are two separate issues here. `pyenv-win` is for swapping Python versions, not for making virtual environments themselves. My personal solution is now the following:

* `pyenv-win` on Windows or `pyenv` on *nix for easily swapping between Python versions locally and globally.
* `Poetry` for virtual environment management.

I think when it comes to the recommended install method for Python, on Windows, we're probably best recommending the official installation executable. For *nix I would be quite comfortable recommending `pyenv` as it is very mature.

For virtual environment creation and management, allow users to either opt for the a tradition approach with `venv` or if that want a few more bells and whistles they should go with `Poetry` within PyMedPhys (for example running `pymedphys dev propagate` will only work with poetry installed)

**Comment by Matthew-Jennings** [comment]
The `pyenv-win` + `poetry` solution seems to work pretty nicely :)

> we're probably best recommending the official installation executable

Specifically 3.7? I eventually successfully troubleshot my docs building issue and I concluded it (embarrassingly) was happening because I wasn't running 3.7.

**Comment by SimonBiggs** [comment]
I think 3.8 support is almost universal, but there certainly might be some edge cases. Interested to know what was breaking with 3.8

**Comment by SimonBiggs** [comment]
If you are driving into poetry + pyenv-win the main (only) issue I've had is with pre-commit. I had to actually manually go into the pre-commit hook that was installed and write in the full path the to python.exe.

It's something about Windows not properly being able to resolve the shims that pyenv-win is using within the hook script.

**Comment by Matthew-Jennings** [comment]
I'm still struggling with setup :( Could we please perhaps have another Zoom/Teams sesh to sort it out? Happy to reflect it in the docs :)

**Comment by SimonBiggs** [comment]
> I'm still struggling with setup :( Could we please perhaps have another Zoom/Teams sesh to sort it out? 

Yup, certainly :)

> Happy to reflect it in the docs :)

You know how to motivate me 😄

**Comment by Matthew-Jennings** [comment]
I'm sorry I missed this! I'll be out this evening unfortunately. Next week?

**Comment by SimonBiggs** [comment]
> I'm sorry I missed this! I'll be out this evening unfortunately. Next week?

Not sure when will be the best time next week. Might be best trying for a quick call over the weekend?

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, you mentioned my terminal, here is my setup:

https://stackoverflow.com/a/65174417/3912576

Also with powershell-core as recommended by the commenter.

**Comment by Matthew-Jennings** [comment]
I can't download Windows Terminal on my workstation! 

![image](https://user-images.githubusercontent.com/19767103/105921234-88179e00-6088-11eb-93ef-928a6a9e3e40.png)

But I've been able to install the dev version of pymedphys in conda `base` :)

**Comment by SimonBiggs** [comment]
> I can't download Windows Terminal on my workstation!

Oh that is unfortunate.

> But I've been able to install the dev version of pymedphys in conda base :)

Lovely to hear :) Was that with poetry? Or pip?

**Comment by Matthew-Jennings** [comment]
Poetry. Just needed to disable venv creation.

**Comment by SimonBiggs** [comment]
> Poetry. Just needed to disable venv creation.

Hmm interesting. I haven't used poetry with that config much. Does poetry go and uninstall things within base when you try and sync the environment with the poetry lock file?
