### ISSUE TITLE
Patient/Study/Series directory hierarchy for DICOM Listener

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1182]
Suggest that the files written out be organized according to Patient/Study/Series directory hierarchy.
This will make the resulting data easier to use as a backing store for hierarchical Q/R (vs. relational queries).
It will also make it easier for navigating with file system based tools for patient centric workflows.
As concrete examples, OnkoDICOM and DICOMpyler have the user select a directory and they recurse to present studies and series to the user.
Further, PyMedPhys pseudonymisation is oriented towards recursing through directories, so patient specific pseudonymisation would be facilitated as well.

My personal preference is to use the DICOM Patient ID as the directory name for the patient level because Patient Name can have some minor variation between systems (middle initial, misspellings, truncation of long names).  Study Instance UID and Series Instance UID for those levels respectively.

I'm happy to be assigned the task or be the reviewer

**Comment by SimonBiggs** [comment]
Yup, I like that approach. @pchlap what are your thoughts? If @sjswerdloff implemented this would you be okay to handle the review of it @pchlap?

**Comment by pchlap** [comment]
For sure, thats a great idea. Sounds good to me!
