### ISSUE TITLE
Key improvements for the UX of the binary

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1197]
* [ ] Print something in the exe console while it is loading for the first time to let people know it is extracting.
* [ ] Print out a little splash screen in the console.
* [ ] Change the exe icon to be the PyMedPhys icon.
* [ ] Make it extract into a sub-directory, so that when it is run from the downloads folder it is still tidy.
* [ ] Make the bat extract into sub-sub-directory called "bin".
* [x] Make the "these may not work" bold.
* [ ] Store a hash file in the exe that is a hash of the python-embed bundle. Have that hash file be extracted. When exe is pressed, compare extracted hash file to that within the exe. If the hash file is different, delete all of the current bundle and re-extract.
* [ ] Upgrade pylinac and remove the "git patch"

**Comment by Matthew-Jennings** [comment]
- [ ] `setup.exe` and `run.exe`

**Comment by SimonBiggs** [comment]
Make PyMedPhys be on the Windows Store:

https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package
