### ISSUE TITLE
Utilise config.toml defined centres and servers within Mosaiq Dashboard

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1213]
this will be much more broadly applicable if the centres and servers are read from configuration (falling back to these defaults is fine to save your own facility from having to do the configuration).

_Originally posted by @sjswerdloff in https://github.com/pymedphys/pymedphys/pull/1199#r525613673_

**Comment by SimonBiggs** [comment]
I'd like to delay this until the following two items are complete:

* A Config GUI
* Config versioning implementation
