### ISSUE TITLE
serviceplans module/package naming

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1245]
> I had not noticed serviceplans before.
> Separate discussion regarding the choice of "service" for the name of the module/package.

Yup, let's discuss in an issue?

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/issues/1243#issuecomment-737431785_

**Comment by sjswerdloff** [comment]
If I understand the code, it's intended to generate a set of plans based on templates and combinatoric use of a handful of treatment beam/control point properties, such as energy, angle, etc.

Is the *intent* for these plans to be used in performing service/maintenance tasks?

**Comment by SimonBiggs** [comment]
> Is the _intent_ for these plans to be used in performing service/maintenance tasks?

The intent for these plans is for them to be sent to the service mode of the Linac for QA tasks. Particularly, the Winston Lutz Arc beam. I recognise though that a "service" is a well defined word in software engineering and perhaps a better name here would be "qaplans" or something similar...

**Comment by sjswerdloff** [comment]
service_mode_plans
or
ServiceModePlans

is what I suggest for an alternative name

**Comment by SimonBiggs** [comment]
For module naming caps aren't to be used and underscores are highly frowned upon. Names preferably should be one word long, only more if they are easily recognisable as separate...

I suspect when that module graduates out of experimental it'll actually likely be part of a greater "plan creation utility" and the "service" part will be mostly irrelevant...

Maybe for now leave it as is? Change it when it comes out of experimental? In the near future I had on my radar a DICOM plan create and send to Linac GUI. The utilities within that module will likely either be deprecated or bundled in to that new utility.

**Comment by sjswerdloff** [comment]
ok to wait
just wanted to make sure I understood the intent and that the naming wouldn't lead to confusion
