### ISSUE TITLE
Log prediction ideas

### ISSUE THREAD

**Issue by fishdda** [pymedphys/pymedphys#1289]
Do we have any tools or API for log prediction for each control point e.g. VMAT?
Just using the prior machine data and DICOM data to build up the correlation. If it's feasible,
each planner could see the actual machine delivery state from the prediction emulator without actual delivery action since the implementation of QA would also involve more uncertainties.

Also, machine delivery time, plan complexity, or related metrics could be illustrated for users.

**Comment by SimonBiggs** [comment]
Hi @fishdda,

What do you mean when you say "log prediction". Can you give an example?

Cheers,
Simon

**Comment by fishdda** [comment]
> Hi @fishdda,
> 
> What do you mean when you say "log prediction". Can you give an example?
> 
> Cheers,
> Simon

Just like the current machine learning approach, from the prior plan DICOM and machine delivery log(I suppose it's corresponding to each other), could we in the future to build up models to predict machine log or machine delivery performance from DICOM plan?

**Comment by SimonBiggs** [comment]
> Just like the current machine learning approach

Can you clarify which current machine learning approach you're referring to?
