### ISSUE TITLE
Repo history has been edited

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1297]
Hi @sjswerdloff, @rembishj, @pchlap,

Sensitive information was submitted to PyMedPhys via a pull request. Given that sensitive information sticks around in git history even if it is removed I had to rewrite the history of PyMedPhys. As such, could everyone please delete their local copies of PyMedPhys and then reclone from GitHub the new PyMedPhys history.

**Comment by SimonBiggs** [comment]
And as an extra note, after re-cloning the repo, make sure to run:

```
poetry run pre-commit install
```

**Comment by pchlap** [comment]
Thanks for the heads up @SimonBiggs. Done :)

**Comment by SimonBiggs** [comment]
Thanks @pchlap :)

**Comment by sjswerdloff** [comment]
How should one do this for a GitHub fork?
I started my involvement by working on a social fork, and I still work from that fork.

I typically do the following to ensure my social fork is up to date: (where origin is my fork and upstream is pymedphys)
# if you haven't already added upstream as the original repository from which you forked
# git remote add upstream  <THEIR_REMOTE_URL> 
# git fetch upstream
 git remote -v
 git fetch upstream
 git checkout main
 git reset --hard upstream/main
 git push origin main --force

**Comment by SimonBiggs** [comment]
> How should one do this for a GitHub fork?

Advice from the bfg website (https://rtyley.github.io/bfg-repo-cleaner/) is the following:

> At this point, you're ready for everyone to ditch their old copies of the repo and do fresh clones of the nice, new pristine data. It's best to delete all old clones, as they'll have dirty history that you don't want to risk pushing back into your newly cleaned repo.

So, best option, unfortunately, is likely to delete your repo on GitHub and then refork it.
