### ISSUE TITLE
Have you seen pytorch_lightning?

### ISSUE THREAD

**Issue by matthewdeancooper** [pymedphys/pymedphys#1301]
pytorch_lightning is to pytorch as keras is to tensorflow.

[https://github.com/PyTorchLightning/pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning)

Some additional sprinkles are that it automates switching to 16 bit precision and scaling to multiple gpus with a single line of code.

It also has built in methods for testing. For example, with a single call you can get the model to train on a single batch for multiple epochs to make sure the architecture has enough degrees of freedom to over-fit a small data set.

Fundamentally, it remove a lot of boilerplate code that you need to implement in pytorch. It also provides helpful hints in the console to improve your model

**Comment by SimonBiggs** [comment]
I'd be more than happy if the production version of the auto-contouring was written in pytorch lightning. I don't see myself using it personally anytime soon, but more than happy for it to become a PyMedPhys dependency 🙂
