### ISSUE TITLE
Dependency Tree Work

### ISSUE THREAD

**Issue by maveLC** [pymedphys/pymedphys#1316]
Hi @SimonBiggs,

Like you write in discourse ([discourse user guide](https://pymedphys.discourse.group/t/user-guide-or-manuals/75/3)), I send you a message about the access ;) 

Thanks
Maëva

**Comment by maveLC** [comment]
Thank you for all !

If you do not have the time, do not worry, family and childs are the most important ;) I will see a part, I hope today (depends of other projects).

**Comment by SimonBiggs** [comment]
So :slightly_smiling_face: @maveLC,

I've made progress pulling in the old code. See the following example (with hyperlinks on the nodes):

https://raw.githubusercontent.com/pymedphys/pymedphys/bring-back-dep-tree/lib/pymedphys/docs/trees/pymedphys._dicom.dose.svg

There are a range of other ones also:

https://github.com/pymedphys/pymedphys/tree/bring-back-dep-tree/lib/pymedphys/docs/trees

All of which created by:

https://github.com/pymedphys/pymedphys/blob/64775b7e2f44e22ca332cf74210b9ae40e1733d0/lib/pymedphys/_experimental/tree.py#L40-L56

Which can be run by calling:

```python
from pymedphys._experimental import tree
tree.create_trees()
```

Is this a good spot to hand over to you and let you run with it?

Cheers,
Simon

**Comment by SimonBiggs** [comment]
As a note, here I have chosen to just focus on making graphs for the public API, but, there is a lot more to PyMedPhys than just that. If you can think of a neat way to organise it I wouldn't be opposed to having graphs for all of PyMedPhys.

Also, feel free to adjust those that I have there as much or as little as you like. I'm not attached to them :slightly_smiling_face:.

**Comment by maveLC** [comment]
Hi,

Thank you for all. I will see all ;) Sorry for my late answer, I was very sick last week ...

**Comment by SimonBiggs** [comment]
> Sorry for my late answer, I was very sick last week ...

All good :slightly_smiling_face:
