### ISSUE TITLE
Thoughts on docs

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1334]
Can I suggest that, for the time being, we simplify the docs to showcase _only_ what already exists and what will be added in the near future? The current structure might be best when it is "full", but as it stands now, the docs are filled with empty sections. Also, honestly, the structure/categorisation on the left panel doesn't feel intuitive to me.

The landing/contents page separates the docs into sections for "App Users", "Python Users" (possibly rename to "Library Users"?) and "Contributors". I like this separation, it feels like the natural choice. But I think they ought to be reflected as the top level categories in the left panel. More specifically, I suggest that, for the time being, we:
- remove **Tutorials** entirely (it's empty!) until at least one is written,
- Place **How-to-Guides** under top-level categories. The contributor setup ones under "Contributors", the gamma one under "Library Users", etc.
- Move **Reference** and **Background** docs in a fashion similar to the **How-To-Guides**

The landing page probably has some nice simplification/prettification opportunities too.

What are your thoughts, @SimonBiggs  and @sjswerdloff? Maybe I can open a PR and propose something there for discussion? (I just didn't want to get started if you're not keen, basically).

**Comment by SimonBiggs** [comment]
> * remove **Tutorials** entirely (it's empty!) until at least one is written,

My hope was that the empty slots would almost be a call to action, representing what we wanted it to be, and recognising that it wasn't there yet.

> * Place **How-to-Guides** under top-level categories. The contributor setup ones under "Contributors", the gamma one under "Library Users", etc.
> * Move **Reference** and **Background** docs in a fashion similar to the **How-To-Guides**

Yup, I really like that idea.

> The landing page probably has some nice simplification/prettification opportunities too.

Yup, certainly. All ears :). A low hanging fruit is the link to the mailing list should be changed to the Discourse forum.

> Also, honestly, the structure/categorisation on the left panel doesn't feel intuitive to me.

Yeah, I was struggling with how to sort this out best. I'm quite keen to keep the philosophy of https://documentation.divio.com/, but certainly splitting things out logically by "Contributors", "Library Users", and "App Users" would be great. ... They could even be separate documentation sites :/

**Comment by SimonBiggs** [comment]
> I just didn't want to get started if you're not keen

I'm keen 🚀

**Comment by Matthew-Jennings** [comment]
The Divio structure does look nice :)

That said, perhaps we could treat that structure as an end goal to aim for rather than have a skeleton in place with missing tissue? As Divio itself says, "_if [PyMedPhys'] documentation is not good enough, people will not use it._" If we recognise that:
- for many of us, docs aren't very fun to write!
- we don't want to raise insurmountable barriers-to-entry by insisting that all contributions have applicable Tutorials, How-to-guides _and_ Reference material.
- we want pretty docs _now_ to attract & inspire people.

Maybe we can settle for a simpler structure and expand as material is written?

> My hope was that the empty slots would almost be a call to action, representing what we wanted it to be, and recognising that it wasn't there yet.

I understand :) But perhaps having _Issues_ is good enough? And/or TODO comments in the docs? My humble opinion is that the need for pretty docs overrides this "reminder" point. I feel like it's more likely that people will contribute to docs if they're inspired by their already-apparent beauty rather than by (ugly!) empty sections...

**Comment by SimonBiggs** [comment]
> But perhaps having _Issues_ is good enough? And/or TODO comments in the docs? My humble opinion is that the need for pretty docs overrides this "reminder" point.

I'm happy for you to take charge on this, I certainly would prefer usable pretty docs. Food for thought though, there are people who would be more than capable at creating a beautiful suite of tutorials who won't be looking at GitHub issues. But in saying all that, you are showing far more enthusiasm than myself to make the docs amazing, so I certainly don't want to stand in the way :).

A huge gap at the moment is documentation on how to be a contributor, and also how to be a maintainer, how to review, how to do a release, as well as documentation of the CI server. And then on the user side, how to set up an application server, how to create your own applications in-house, and how to overcome those set up issues that you're having (which I'm sure I can find time this week to help with).

So moral of the story, if you feel strongly regarding something in the docs, I'd prefer to give you autonomy than to stick to my guns about something that I may feel strongly about, but I have not as of yet backed my preferences with significant action.
