### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#134]
Probably high time we locked one in? Can always change later...

**Comment by SimonBiggs** [comment]
Yeah, no need to rush it. We should take your CT idea but implement it
within matplotlib. The snake bit was already done with matplotlib, now we
just need to add the CT and I think it'll be pretty close to done.

**Comment by SimonBiggs** [comment]
I reckon though we could probably get it out over the next couple of days.

**Comment by richardbmx** [comment]
@Centrus007  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by SimonBiggs** [comment]
Hi @richardbmx,

We would massively appreciate that! If it helps, here are some of the original ideas we were throwing around:

https://gitlab.com/pymedphys/pymedphys/issues/81

**Comment by SimonBiggs** [comment]
And here was further discussion:

https://gitlab.com/pymedphys/pymedphys/merge_requests/178

**Comment by SimonBiggs** [comment]
And here is the recent logo work:

https://github.com/pymedphys/pymedphys/pull/137

**Comment by kingrpaul** [comment]
That looks really nice.

**Comment by SimonBiggs** [comment]
@richardbmx I do like those, they are quite nice. I notice that the wave in the middle seams to be just going straight between the peaks?

I might be biased, but I for the time being I think I prefer the following:

![image](https://user-images.githubusercontent.com/6559099/55720043-244f5b80-5a43-11e9-8816-0bb3c7afaa19.png)

Other's thoughts?

**Comment by SimonBiggs** [comment]
I really like how the photon packet is going between the panels. How does that logo look as a favicon?

**Comment by richardbmx** [comment]
a favicon version can be seen like this

![favicon](https://user-images.githubusercontent.com/35604837/55755513-2dc5cd00-5a1d-11e9-8074-678fd7c16e99.png)

**Comment by SimonBiggs** [comment]
What about a 16x16 browser favicon?

**Comment by richardbmx** [comment]
![favicon2](https://user-images.githubusercontent.com/35604837/55757104-2b657200-5a21-11e9-84c8-cd76742c06f0.png)

**Comment by SimonBiggs** [comment]
As in 16x16 pixels...

**Comment by SimonBiggs** [comment]
Can the capitals in PyMedPhys be on the P, M, and the P?

Can the resolution of the gamma wave have a few more samples so that at the end it's less pointy and a little more curved.

Also, I consulted with my significant other (a bit of a better eye than mine, and not subject to the same biases) and she prefers yours @richardbmx :).

**Comment by SimonBiggs** [comment]
One of my concerns is the level of detail will struggle when it is very small.

**Comment by SimonBiggs** [comment]
@Centrus007 what does your independent advisor think :)

**Comment by SimonBiggs** [comment]
@richardbmx see the following for appropriate curvature:

https://en.m.wikipedia.org/wiki/Group_velocity#/media/File%3AWave_packet_propagation_(phase_faster_than_group%2C_nondispersive).gife_faster_than_group%252C_nondispersive%2529.gif

**Comment by SimonBiggs** [comment]
With the design we had originally put together, to create an animated version, I was planning on pulsing the wave packet in beats of two to mimic a heart beat (to further simulate the idea of a heart beat)

I had pictured on initial view of the page, and on mouse over, the logo would propagate the wave twice and then be stationary (until a further mouse over).

You certainly don't need to do that animation now, but how plausible is an animation like that with your method? I used matplotlib to build the previous logo, and animating it should be as simple as adjusting the wave packet function to create each frame...

**Comment by kingrpaul** [comment]
@SimonBiggs if you are going to animate the newer logo, suggest instead of animating the wave packet, let the snake circle a revolution around the outside.

**Comment by SimonBiggs** [comment]
> @SimonBiggs if you are going to animate the newer logo, suggest instead of animating the wave packet, let the snake circle a revolution around the outside.

Makes sense :) I like it.

**Comment by Centrus007** [comment]
Hi @richardbmx, thank you very much for drafting those! I can definitely see the potential. My thoughts so far:

- Love the waveform panels! I also like the narrower pulse line-thickness, though I share Simon's concerns with its visibility at the very small icon level (if you're a chrome user, think the icons in the tabs). 16x16 will be challenging with this design, I think. But, @SimonBiggs, could make do with 32x32?

- I reckon the waveform would like a tad nicer if it took up slightly more space within the ring (i.e. just overall larger). Only slightly. But it's a small point :)

- I also like the two circle design (ring + python) instead of one (just ring).

- I don't think any of them quite hit the mark on colour-scheme. I do still like the Python-themed blue and yellow, but I'm not too keen on the grey. I wonder whether having the encircling python and the waveform coloured blue with the ring coloured yellow would work? Or we can decide on a third colour?

- Agree with @SimonBiggs that the waveform would like a tad nicer if it were more "rounded".

- Agree with @kingrpaul that the snake could revolve around the outside for animation. Also, perhaps the waveform (with its panels) could rotate in the opposite direction?

**Comment by SimonBiggs** [comment]
## 16x16 and 32x32 images of each

![favicon-16x16](https://user-images.githubusercontent.com/6559099/55937589-a9718500-5c7c-11e9-88b7-6a93e069e269.png)

![favicon-32x32](https://user-images.githubusercontent.com/6559099/55937590-a9718500-5c7c-11e9-8da4-234633126af0.png)

![favicon-16x16](https://user-images.githubusercontent.com/6559099/55937966-98754380-5c7d-11e9-93b9-24ef97d04806.png)

![favicon-32x32](https://user-images.githubusercontent.com/6559099/55937967-98754380-5c7d-11e9-83c5-1be9af2aa534.png)

Looking at it like that, I think the small image issue is mostly a non-starter. They both have trouble being seen at 16x16, and both can be seen well enough at 32x32.

## Logo in contexts

Not sure if it helps, but here is the logo I made put in a few contexts...

![Capture](https://user-images.githubusercontent.com/6559099/55937820-42080500-5c7d-11e9-8929-a93709adae1d.PNG)

![Capture](https://user-images.githubusercontent.com/6559099/55937792-34eb1600-5c7d-11e9-9d7a-cb8bb597f23b.PNG)

![Capture](https://user-images.githubusercontent.com/6559099/55937852-53511180-5c7d-11e9-865d-7e502c0f7dd2.PNG)

![Capture](https://user-images.githubusercontent.com/6559099/55937879-606e0080-5c7d-11e9-9baa-73ab253d2cc3.PNG)

## Animation

@kingrpaul @Centrus007 I'm not sure I would know how to animate a plain SVG image. My animation method was just going to use matplotlib. I don't think I could easily animate an SVG by itself...

**Comment by SimonBiggs** [comment]
Seeing the following makes me think it'd be awesome if there was a shadow under the snake that went across the CT...

![Capture](https://user-images.githubusercontent.com/6559099/55937820-42080500-5c7d-11e9-8929-a93709adae1d.PNG)

**Comment by Centrus007** [comment]
Agreed. Could just lock in a white (rather than transparent) ring interior for now?

**Comment by SimonBiggs** [comment]
Making a shadow should be easy enough. It would just be a semi transparent offset grey copy of the CT and snake.

**Comment by SimonBiggs** [comment]
@Centrus007 I showed the small logos 16x16 and 32x32 to Esther and she then said she changed her mind, she preferred mine, because the extra detail of @richardbmx logo was hard to make out at that size, but on mine it was clear enough to see what was going on.

That was a key design goal of mine, to make the wave clear and thick and large keeping in mind the logo needed to be able to handle being both quite large and quite small. It is also a design I often see around the place for most logos.

Given that, and given that we've had no further response from @richardbmx, I suggest we use my logo and move forward on this point. What do others think?

**Comment by Centrus007** [comment]
I say go ahead :)

**Comment by SimonBiggs** [comment]
Thanks Matt :)

**Comment by SimonBiggs** [comment]
The logo size is quite limited by the fact that the snake is coming out side on. Any thoughts on making the snake head slither up with its tail slither down (and maybe wrap around the CT) with the aim to make it so that the bounding box of the logo abuts the CT (allowing the all round size of the logo itself to be greater...)

**Comment by SimonBiggs** [comment]
Hmm.. dunno, anyway, it's not something for right now, but just something I was thinking about.

**Comment by Centrus007** [comment]
At least for now, why not simply shorten the snake's tail and head so that their limits exactly hit the CT outer diameter and scale the pulse accordingly?

I'm reluctant to abandon the pulse.

**Comment by SimonBiggs** [comment]
Fair point, I wasn't thinking of abandoning the pulse, just bending off the tail and head... Not sure how it would look though... I really also don't want to lose the pulse :)

**Comment by richardbmx** [comment]
In my opinion as a designer without mood to offer my proposal, but the idea I used with the snake on the edge of the circle was with the intention of preventing it from going sideways so that they did not have that problem that is presented to them, in the end they observe the wave, the snake is present and all in the same harmonic design

**Comment by SimonBiggs** [comment]
Appreciated your help :) We ended up going with the original logo design in the end.
