### ISSUE TITLE
Implement notebook ideas within animal unet file

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1351]
@matthewdeancooper had a range of suggestions for the lung unet notebook:

https://github.com/pymedphys/pymedphys/pull/1344#pullrequestreview-576832844

For now I'm going to put to one side the lung dataset and stick with the animal dataset notebook. Most of those suggestions apply to the original unet notebook, so I'm going to apply them there.

**Comment by matthewdeancooper** [comment]
Feel free to ping me for a review if required.
