### ISSUE TITLE
Further docs review

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1357]
The release notes should be visible in the main screen list of documents on the general overview page:

https://docs.pymedphys.com/general/index.html

**Comment by Matthew-Jennings** [comment]
Also, what are your thoughts on category order, @SimonBiggs & @sjswerdloff? Should General be at the top? Library above App? I have no real preference, but two very minor points that triggers this question are:

- Release Notes are quite low/deprioritised.
  - Does this matter?
- App is at the top.
  - I put it there thinking that an App Guide will ultimately be the most used section. But it certainly wouldn't be now, and we can 
    change it later?

How it looks at the moment:

![image](https://user-images.githubusercontent.com/19767103/106213163-00fb2f00-621c-11eb-90ce-e8479bd54d43.png)

**Comment by SimonBiggs** [comment]
Yeah, I think we should follow the same theme you've started, prioritise what is most useful now, and adjust later as needs change.

**Comment by Matthew-Jennings** [comment]
So are you thinking:

1. General
2. Library
3. CLI
4. App
5. Contributors

? Or slightly different?

**Comment by SimonBiggs** [comment]
I'm not convinced regarding General at the top. Release notes will primarily be library focused... maybe the release notes can be under library and then have general at the bottom? I'm not convinced with that idea. Happy for you to make the call on this one.

**Comment by SimonBiggs** [comment]
@Matthew-Jennings was this intentionally closed?

**Comment by Matthew-Jennings** [comment]
Sorry, I linked it to #1360 at a time when this Issue was only going to address:

>The release notes should be visible in the main screen list of documents on the general overview page:

This Issue grew in scope and I forgot about the link! 😊
