### ISSUE TITLE
Sort out testing

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1381]
Hi @rembishj,

When you do get the chance, let's sort this one out on a video call:

https://github.com/pymedphys/pymedphys/pull/1374#pullrequestreview-580020165

**Comment by rembishj** [comment]
> Hi @rembishj,
> 
> When you do get the chance, let's sort this one out on a video call:
> 
> [#1374 (review)](https://github.com/pymedphys/pymedphys/pull/1374#pullrequestreview-580020165)

When would be best for you to meet? I can do any afternoon/evening this week.
