### ISSUE TITLE
Inconsistent delivery data from Mosaiq

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1391]
Hi @dg1an3,

I thought you might have some ideas about this one. A while back I was extracting MU, Gantry and Col Angles as well as MLC and Jaw positions from Mosaiq. Intermittently I would get some weird disagreements. So... I made the following work-around:

https://github.com/pymedphys/pymedphys/blob/c5fa262fd5eb927dcbbe1fced3469f13ad7f1a96/lib/pymedphys/_mosaiq/delivery.py#L295-L313

Essentially the gist there is I retrieve the delivery information from Mosaiq twice, and then if the consecutive calls disagree with one another... I retrieve it again... until consecutive calls do agree. ...not a great solution...

I'm not sure if the issue is with Mosaiq, MS-SQL, or FreeTDS (the driver behind pymssql), pymssql, or PyMedPhys.

Here's the SQL code that the database is being queried with:

https://github.com/pymedphys/pymedphys/blob/c5fa262fd5eb927dcbbe1fced3469f13ad7f1a96/lib/pymedphys/_mosaiq/delivery.py#L249-L292

Anyway... figured if you're opening up the PyMedPhys Mosaiq code I should let you know about the skeletons before they fall out and scare you 🙂

---

...and while we're at it... here's probably the other main skeleton in that part of the code base:

https://github.com/pymedphys/pymedphys/blob/c5fa262fd5eb927dcbbe1fced3469f13ad7f1a96/lib/pymedphys/_mosaiq/delivery.py#L172-L196

When loading up the MLCs, in some cases there was a byte missing within the database... so... I tried to make a sensible interpretation to restore the data when loading it.

**Comment by dg1an3** [comment]
Hi @SimonBiggs -- do you know what is changing between the first and second queries?  When I looked more closely at the table definition for TxFieldPoint, it occurred to me that the query:
```
SELECT 
    TxFieldPoint.[Index],
    TxFieldPoint.A_Leaf_Set, 
    TxFieldPoint.B_Leaf_Set, 
    TxFieldPoint.Gantry_Ang, 
    TxFieldPoint.Coll_Ang, 
    TxFieldPoint.Coll_Y1, 
    TxFieldPoint.Coll_Y2 
FROM TxFieldPoint 
WHERE 
    TxFieldPoint.FLD_ID = %(field_id)s
```

doesn't have an ORDER BY clause, so it could it be returning rows in different order between queries?  At first I was thinking you might want to "ORDER BY [Index]", but Index is a decimal field corresponding to..cumulative meterset?.  [Point] maybe a better choice, as it is the numerical index of the control point.

Beyond that, I would look at whether there is anything/anyone changing the rows between queries (haunted database, maybe? :))  If you include the RowVers column in the query, you should be able to tell if the underlying row data had been altered.  RowVers is a timestamp column that is automatically updated by SQL server 
https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver15

so if it has changed between queries, then there is a good chance that someone or something has altered the data.

**Comment by SimonBiggs** [comment]
I'll make a PR to undergo proper logging of the issue whenever it happens. It is quite intermittent. A lack of ORDER BY might just be the issue. I could imaging an intermittent race condition where depending on when I query the database the control points come across in a slightly different order, that would be consistent with the kind of errors I was seeing.

I'll make the PR pull in both `RowVers` and `[Point]` and print those. Once I've seen it happen and have a print out of the issue I'll then set the query to ORDER BY `[Point]`.

Thanks @dg1an3, I'm a bit of a toddler when it comes to SQL. "Know enough to be dangerous".
