### ISSUE TITLE
Alternative to LFS storage

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#14]
@Centrus007 mentioned the following within https://gitlab.com/pymedphys/pymedphys/issues/112:

> Actually, I think a data storage solution that has similar functionality to DropBox would be nice. It's nice to have synchronisation of a shared folder. Can this be achieved with https://archive.org ?

**Comment by SimonBiggs** [comment]
@Centrus007 we have an Enterprise OneDrive account at work with huge data storage allowances. Let me investigate the usage of that.

**Comment by SimonBiggs** [comment]
Should we use something like OneDrive, we should still have a helper function within the library that helps with uploading files to the OneDrive. Once a file is uploaded to OneDrive it shouldn't ever be deleted, and the hash of the file contents should be appended to the filename. That way when a file is changed, a branch that references the old version doesn't get tripped up.

**Comment by SimonBiggs** [comment]
Or maybe we just always append `_vMajor.Minor.Patch` the the file name?

**Comment by SimonBiggs** [comment]
...no, hash is better, that way two people making a change at the same time can't make different files have the same `version`.

**Comment by Centrus007** [comment]
Seems a *little* overkill, but happy to try it.

OneDrive has at least some rudimentary version control: https://support.office.com/en-us/article/restore-a-previous-version-of-a-file-in-onedrive-159cad6d-d76e-4981-88ef-de6e96c93893

**Comment by Centrus007** [comment]
> OneDrive it shouldn't ever be deleted

Why? Don't think I agree with this...

**Comment by SimonBiggs** [comment]
> We risk blowing out the size of the OneDrive (with added time-cost of syncing) for little benefit.

I don't imagine anyone would be given syncing rights, just specific upload download access to a single directory of specific files. I'm not too sure how it would work really. ... The one drive account I'm thinking of currently has upwards of 500 GB in use at the moment...

**Comment by SimonBiggs** [comment]
A better method might be archive.org anyway...

**Comment by SimonBiggs** [comment]
This needs to be bumped up in priority. We've had a few large files commited to the repo and it's beginning to slow things down.

After searching for a good alternative I found the following:

http://developers.zenodo.org/

They allow uploaded files of up to 50GB, they have an upload API. Once uploaded it is saved for public use. It's run by CERN. It's designed for the public sharing of large datasets. It is perfect for our use case.

So, I need to take all of our LFS files and upload them to there.

The plan looks like this. Have a "pymedphys" data directory that is made on the local machine. Certain files, if code ever needs them, will be looked for within that data directory. If not found within that file then they will be downloaded.

Zenodo creates a DOI for every file uploaded.

**Comment by SimonBiggs** [comment]
pymedphys community made at https://zenodo.org/communities/pymedphys/

**Comment by Centrus007** [comment]
It sounds perfect! :)

**Comment by SimonBiggs** [comment]
I have uploaded all of our in use LFS files to zenodo:

https://zenodo.org/communities/pymedphys/?page=1&size=100

Now to build in a tool to map to autodownload the required files based on DOI web address and put them in a cache location on the users computer.

**Comment by SimonBiggs** [comment]
Will track this in https://github.com/pymedphys/pymedphys/issues/441
