### ISSUE TITLE
Conda-forge package doesn't install `pymedphys` command line interface

### ISSUE THREAD

**Issue by fishdda** [pymedphys/pymedphys#141]
Hi Guys have you ever meet "pymedphys command not found" when executing the command line"pymedphys trf to-csv filepath" recommended by the release note .
Seems the environment variable problem, but when I added it, still have this issue.

**Comment by SimonBiggs** [comment]
Hi @fishdda,

Thanks for reaching out. Does the following issue response help you:

https://github.com/pymedphys/pymedphys/issues/142

**Comment by fishdda** [comment]
@SimonBiggs  Hi Thanks for your suggestion and I reinstalled anaconda exe but the same issue still exists. I wanna know if others meet the same situation before? Seems like the command like "pymedphys" couldn't be used in command line.

**Comment by SimonBiggs** [comment]
Did you open a new command prompt after installing? Can you write the following in a command prompt and let me know what it says?

```bat
echo %PATH%
```

**Comment by fishdda** [comment]
![image](https://user-images.githubusercontent.com/23411165/55780359-5790f980-5ada-11e9-99ff-d3b86232c4f9.png)
Could you see the pic?

**Comment by fishdda** [comment]
![image](https://user-images.githubusercontent.com/23411165/55780456-860ed480-5ada-11e9-94be-bfe90ad0bd89.png)

**Comment by SimonBiggs** [comment]
Alright, can you open `C:\Anaconda\Scripts` and see if `pymedphys.exe` is in there?

Also, what version of `pymedphys` do you have?

**Comment by SimonBiggs** [comment]
Actually, gee wiz, that `PATH` is a mighty mess. You really should only have one Python installation, from the looks of that `PATH` you have 6+ scattered all over your machine.

Potentially your `PATH` could even be full...

**Comment by fishdda** [comment]
Ok, I would check it to see if works correctly.

**Comment by fishdda** [comment]
> Actually, gee wiz, that `PATH` is a mighty mess. You really should only have one Python installation, from the looks of that `PATH` you have 6+ scattered all over your machine.
> 
> Potentially your `PATH` could even be full...

Maybe you are right. Before I just use the pure python without anaconda but failed when installing pymedphys.

**Comment by SimonBiggs** [comment]
Did you install PyMedPhys with `conda` or `pip`?

**Comment by fishdda** [comment]
Already checked the C:\Anaconda\Scripts and No pymedphys.exe exists

**Comment by fishdda** [comment]
> Did you install PyMedPhys with `conda` or `pip`?

Sure, I install it using conda

**Comment by fishdda** [comment]
btw I also try to install the pymedphys on my mac, but the same issue occurs. It seems weird.

**Comment by SimonBiggs** [comment]
What happens when you run:

```bat
conda install pymedphys==0.7.2
```

**Comment by fishdda** [comment]
![image](https://user-images.githubusercontent.com/23411165/55782295-87420080-5ade-11e9-99ef-4c85c3e23edd.png)
![image](https://user-images.githubusercontent.com/23411165/55782502-ff102b00-5ade-11e9-98a7-8f864bf4b203.png)

**Comment by SimonBiggs** [comment]
Sure, give that a go.

**Comment by SimonBiggs** [comment]
Maybe it's an issue with `pip` vs `conda`. If that doesn't work, it might be worth trying to run:

```
conda uninstall pymedphys
pip uninstall pymedphys
pip install pymedphys==0.7.2
```

**Comment by SimonBiggs** [comment]
So, stripping it on my machine it seems that the conda distribution isn't activating the command line interface. Only pip will do it. That's unfortunate, I believe running the following on your machines should fix it:

```
conda uninstall pymedphys
pip uninstall pymedphys
pip install pymedphys==0.7.2
```

I'll see if I can fix the conda package. Thanks for the bug report! :)

**Comment by SimonBiggs** [comment]
Attempting to fix with https://github.com/conda-forge/pymedphys-feedstock/pull/12

**Comment by SimonBiggs** [comment]
@fishdda in an hour or so the new conda package will be in the wild. Hopefully that will fix this issue for everyone.

**Comment by SimonBiggs** [comment]
When it's ready the following should successfully install:

```bat
conda install pymedphys==0.7.2=py_1
```

(an hour or so)

**Comment by fishdda** [comment]
OK, really thanks for your careful advice and I am still trying now.

**Comment by SimonBiggs** [comment]
Did the pip method work?

**Comment by SimonBiggs** [comment]
Did you try the following:

https://github.com/pymedphys/pymedphys/issues/141#issuecomment-481144827

**Comment by SimonBiggs** [comment]
I've also just installed `pymedphys` with:

```
conda install pymedphys==0.7.2=py_1
```

And I can verify that with the new build, installed with `conda` the `pymedphys` command now works. @fishdda can you confirm it now works for you?

**Comment by fishdda** [comment]
Pip already works well, really thanks for your help.
![image](https://user-images.githubusercontent.com/23411165/55795003-5c18da80-5af9-11e9-9553-1bb0189a227f.png)

**Comment by SimonBiggs** [comment]
Great to hear :).

I also just tested conda and it now works. Thanks for this report, glad I
could get this issue fixed.
