### ISSUE TITLE
Typo in Pinnacle DICOM references?

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1414]
Hi @pchlap,

Is the following a typo?

https://github.com/pymedphys/pymedphys/blob/4cfec2e5a4d7a55766e97b2e32cecd335d6632fe/lib/pymedphys/_experimental/pinnacle/rtstruct.py#L435

**Comment by sjswerdloff** [comment]
It looks OK to me.
He's referencing the Study Instance UID?
Can you separate out which piece of text you think has the typo?

**Comment by SimonBiggs** [comment]
I certainly don't know much about all this... but with a "novice" eye I would have thought it would have looked like the following:

```diff
    ds.ReferencedStudySequence[0].ReferencedSOPClassUID = "1.2.840.10008.3.1.2.3.2"
    ds.ReferencedStudySequence[
        0
-   ].ReferencedSOPInstanceUID = plan.primary_image.image_info[0]["StudyInstanceUID"]
+   ].ReferencedSOPInstanceUID = plan.primary_image.image_info[0]["SOPInstanceUID"]
    ds.StudyInstanceUID = plan.primary_image.image_info[0]["StudyInstanceUID"]
    ds.SeriesInstanceUID = struct_series_instuid
```
