### ISSUE TITLE
'Failed - No File' when using download feature

### ISSUE THREAD

**Issue by e-tony** [pymedphys/pymedphys#1422]
Hi, 

thanks for implementing the neat download feature! 

I'm getting an error when downloading a file. The file does not download and I get a "Failed - No File" message in the chrome downloads bar.

My code:
```
from pymedphys._streamlit.utilities import download

download("a_text_file.txt", "Some beautiful text!")
```

Setup:
Python: 3.7.6
streamlit: 0.76.0
pymedphys commit version: 56f6ed15f6d870d41a9543fb70bf164a7fe32892

Cheers.

**Comment by SimonBiggs** [comment]
Hi @e-tony,

The download function within PyMedPhys also needs to have a Tornado handler boot up. This Tornado handler is added to the streamlit server when `pymedphys gui` is called from the command line, but I imagine you want to be able to use this download function for a standalone streamlit app? Would that be correct?

If that's the case, I could create a `pymedphys streamlit run ...` CLI command, which will add on the extra server extensions needed...

**Comment by e-tony** [comment]
Ah, that explains it. I was using it as a standalone Streamlit app. I saw the discussion [here](https://github.com/streamlit/streamlit/issues/2722) and thought I'd try it out.

**Comment by SimonBiggs** [comment]
> Does it make sense to wait for a merge within Streamlit itself instead of making a CLI command for that?

It won't take me long to make a CLI like that, and I imagine this won't be the first time we'll be using PyMedPhys as a testing ground for things we push upstream. So, I think it's worth it.

**Comment by SimonBiggs** [comment]
@e-tony would you be able to take the following branch for a spin and see if it does the trick?

https://github.com/pymedphys/pymedphys/pull/1423

I checked to make sure it worked from my end by running:

```
pymedphys streamlit run app.py
```

And then checked to see if the download worked.

**Comment by e-tony** [comment]
@SimonBiggs that works! Thanks a lot for the quick fix :)

**Comment by SimonBiggs** [comment]
My pleasure 🙂
