### ISSUE TITLE
Going on leave

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1425]
Just wanting to give a heads up that I'll be going on leave this Friday. (Last day tomorrow). I'll be back on the 3rd March. I'll leave PyMedPhys in @sjswerdloff's and @Matthew-Jennings's capable hands.

Just wanting to ping @rembishj and @dg1an3 as you'll need to flag @sjswerdloff and @Matthew-Jennings for reviews during that time.

Cheers 🙂,
Simon

**Comment by sjswerdloff** [comment]
Enjoy.
We'll try to "hold down the fort".

**Comment by SimonBiggs** [comment]
> Enjoy.
> We'll try to "hold down the fort".

It's a pretty nice feeling knowing you guys have it while I'm gone. Thank you 🙂
