### ISSUE TITLE
Investigate usage of RT-Utils

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1428]
See

* https://github.com/qurit/RT-Utils
* https://qurit.ca/2021/02/05/generating-rt-structs-in-python-with-rt-utils/
* https://github.com/pydicom/pydicom/issues/1122#issuecomment-776417838

**Comment by SimonBiggs** [comment]
Pinging @pchlap and @matthewdeancooper as you guys might be interested in this...

**Comment by pchlap** [comment]
@SimonBiggs Nice, we have some messy code in platipy which we can probably archive since this looks much better and cleaner. Thanks for sharing!

**Comment by SimonBiggs** [comment]
You're very welcome :)

**Comment by matthewdeancooper** [comment]
@SimonBiggs 
This looks great. *Everyone* is interested in a robust and open-source method for creating rt structure files :1st_place_medal: !

**Comment by pchlap** [comment]
Hi @SimonBiggs and @matthewdeancooper,

it looks like there are a few of these popping up at the moment. A colleague of mine just showed me this: https://github.com/brianmanderson/Dicom_RT_and_Images_to_Mask and they actually have a pre-print article to accompany the repository: https://www.sciencedirect.com/science/article/pii/S1879850021000485
