### ISSUE TITLE
Mac OS Big Sur Install Issue.

### ISSUE THREAD

**Issue by finjoetri** [pymedphys/pymedphys#1433]
I tried to install with PIP in Mac OS Big Sur and I got this error: 
ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pk/64c89q550ml7g13gf7t5__9m0000gn/T/pip-install-vpBrTS/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/pk/64c89q550ml7g13gf7t5__9m0000gn/T/pip-install-vpBrTS/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/pk/64c89q550ml7g13gf7t5__9m0000gn/T/pip-pip-egg-info-Jaq81J
         cwd: /private/var/folders/pk/64c89q550ml7g13gf7t5__9m0000gn/T/pip-install-vpBrTS/shapely/
    Complete output (12 lines):
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pk/64c89q550ml7g13gf7t5__9m0000gn/T/pip-install-vpBrTS/shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 190, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "shapely/_buildcfg.py", line 164, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sjswerdloff** [comment]
Python 2.7?

Please try starting with python 3.7+, ideally staying relatively close to the recommendations/ guidelines in the installation part of the documents, e.g brew, freetds, pyenv... 

I'm not sure if Big Sur is the version used in the CI pipeline.  

The MacOS install is definitely the more challenging one (I have Win10, Ubuntu 20.04 and Catalina... but I think the other maintainers are mostly Win10 or Linux). 

Please let me know if there are further problems when baselining with Python 3.7+ and I can try to help.

**Comment by finjoetri** [comment]
I tried with the latest Python, I used pip install pymedphys I got the same error. When I used pip3 I am getting following error

-MacBook-Air:venv apple$ python --version
Python 3.9.1
-MacBook-Air:venv apple$ pip3 install pymedphys
Collecting pymedphys
  Using cached https://files.pythonhosted.org/packages/62/24/3b766e83a8eadf3567e227492c40b9b2450ed12569489bad95748127273f/pymedphys-0.35.0-py3-none-any.whl
Installing collected packages: pymedphys
**Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7/site-packages/pymedphys'
Consider using the `--user` option or check the permissions.**

You are using pip version 19.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by pchlap** [comment]
Hi @finjoetri,

That last error is a permissions issue. You either need to elevate your permissions to install the library into your system's Python environment, or follow the suggestion in the error message and use the --user flag which will only install it for your user account and won't need elevated permissions.

I'm on MacOS Catalina and I can confirm that pymedphys pip installs without any problem. I do use pyenv though to manage my Python environments.

**Comment by sjswerdloff** [comment]
pip3 install --user pymedphys

**Comment by finjoetri** [comment]
Thanks @pchlap and @sjswerdloff , I am able to install the pymedphys in my Mac.

**Comment by sjswerdloff** [comment]
You might want to try
pip3 install --user pymedphys[user]

This will try to install the dependencies for a lot of the different features in PyMedPhys.  If you have tried to use some parts of PyMedPhys and got messages indicating import failures, the above installation option may be the solution
