### ISSUE TITLE
DICOM Pseudonymisation appears to be reversible in some cases

### ISSUE THREAD

**Issue by JacobMcAloney** [pymedphys/pymedphys#1455]
Not sure if the DICOM Pseudonymisation streamlit function was meant to leave date of birth and gender unchanged, just thought I would mention it as I thought they needed to be replaced also.

**Comment by SimonBiggs** [comment]
Thanks @JacobMcAloney for the report 🙂, I'll let @sjswerdloff jump on this one when he gets a chance.

Cheers

**Comment by sjswerdloff** [comment]
DOB should be jittered, or removed, so that is a defect.  I'll get on that shortly.

Patient Sex is a bit different in my opinion because it can have significant impact on clinical decisions and does not contribute much in terms of reidentification.  If further feedback indicates it would be better to have Patient Sex eliminated or set to O by default, with explanation of the importance, I am ok with changing it.

Thank you very much for the feedback!

**Comment by sjswerdloff** [comment]
Hi @JacobMcAloney I went ahead and tested for Patient's Birth Date and it appears to be getting jittered.
I modified an already pseudonymised sample file, plugged in my birth date and got a value back that was between that and that of my older brother (so... in the ballpark for clinical purposes, but not for identification purposes).
Could you confirm that the DOB is actually unchanged?

**Comment by JacobMcAloney** [comment]
Hi @sjswerdloff, sorry, didn't realise the date of birth was being jittered to return a similar but different entry, that's my bad in not understanding the mechanics. Just checked the patient in question and the DOB had indeed been changed. Thanks for following up on this even if it was a wild goose chase!

**Comment by sjswerdloff** [comment]
An extra pair of eyes is always appreciated.  Receiver Operating Characteristic...  I don't expect 100% sensitivity and 100% specificity.  And for these circumstances, sensitivity is really key. Thank you for investigating, commenting and following up.!

**Comment by SimonBiggs** [comment]
@sjswerdloff is it an issue that the pseudonymisation for birth date (and potentially other fields) can be reliably undone using the following approach?

```python
import datetime
import collections

import pymedphys
from pymedphys._dicom import create
from pymedphys.experimental import pseudonymisation as ps


def get_mapped_date(input_date):
    ds = create.dicom_dataset_from_dict({
        "PatientBirthDate": input_date
    })
    anon_ds = ps.pseudonymise(ds)
    output_date = anon_ds.PatientBirthDate
    
    return output_date


def increment_date(input_date):
    dt = datetime.datetime.strptime(input_date, "%Y%m%d")
    new_dt = dt + datetime.timedelta(days=1)
    
    return new_dt.strftime("%Y%m%d")


current_date = "19200101"
end_date = "20100101"

mapped_dates = {}

while current_date != end_date:
    mapped_dates[current_date] = get_mapped_date(current_date)
    current_date = increment_date(current_date)

inverse_mapping = collections.defaultdict(list)

for identified, anonymised in mapped_dates.items():
    inverse_mapping[anonymised].append(identified)


def re_identify(anonymised):
    options = inverse_mapping[anonymised]
    
    if len(options) == 1:
        return options[0]
    else:
        return options
```

Which then gives the following:

```python
>>> ds = create.dicom_dataset_from_dict({
...     "PatientBirthDate": "19930822"
... })

>>> ds
(0010, 0030) Patient's Birth Date                DA: '19930822'

>>> anon_ds = ps.pseudonymise(ds)

>>> anon_ds
(0010, 0030) Patient's Birth Date                DA: '19890509'

>>> re_identify("19890509")
'19930822'
```

**Comment by rickardcronholm** [comment]
Making this comment from way out of left field, so feel free to disregard if I state something trivial/obvious. There is a DICOM standard for de-identification. Have a look at http://dicom.nema.org/medical/dicom/current/output/html/part15.html#chapter_E Table E.1.1 clearly states which tags should be removed, replaced or kept. 

Going with a configurable allow-list might lead to stripping of type 1 tags and invalid DICOM files.

**Comment by SimonBiggs** [comment]
> Going with a configurable allow-list might lead to stripping of type 1 tags and invalid DICOM files.

Yup certainly, however, the particular anonymisation function I would be creating would be only for internal use by the auto-segmentation tool I am creating for my Radiotherapy AI start-up. All headers items that are removed client side will be restored client side before sending back to the TPS.

So ... As long as my allow-list contains the items I need to run inference on my machine learning model on the server I should be good to go.

**Comment by rickardcronholm** [comment]
I guess I should had added irrelevant to list of reasons to disregard my post.

**Comment by SimonBiggs** [comment]
> I guess I should had added irrelevant to list of reasons to disregard my post.

@rickardcronholm  it's all good :slightly_smiling_face:. It is quite relevant with the information you had. I was posting on the general purpose PyMedPhys libraries issue tracker, so your advice was pertinent and could have been quite helpful in averting a bad design decision.

It's great to see you back here :slightly_smiling_face:. How are you going?

**Comment by rickardcronholm** [comment]
@SimonBiggs It's all good. Funny that you mention RT AI startup doing auto segmentation. I'm at a similar company and we are about to submit FDA 501k application for an AI auto segmentation app within weeks. It's becoming a competitive field. Getting regulatory approvement is not a fun exercise at all.

**Comment by SimonBiggs** [comment]
If you're interested I can quickly spin up the demo of the model I've built and you can take it for a quick spin before I pull it back down again?

**Comment by rickardcronholm** [comment]
I most definitely am! I've done a market review quite recently so I've seen
most of the competition such as Mirada, mVision and Limbus.

**Comment by SimonBiggs** [comment]
https://radiotherapy.ai :slightly_smiling_face:

**Comment by rickardcronholm** [comment]
Not able to connect to the streamlit server. I suppose you might have
pulled the instance down again.

**Comment by SimonBiggs** [comment]
Any chance you might be using an older version of Safari to view the page? Could you try in Chrome or Firefox?

**Comment by rickardcronholm** [comment]
I was on Firefox, a recent version. Got it working after a while.

Really nice way of demoing! I think you've chosen a good set of metrics.
Are the results per slice? Does that infer that the network also operates
on 2d?

**Comment by SimonBiggs** [comment]
Those results there are only for the viewed slice, I should make that clear. I should present the 3D results also though. Under the hood it is a 3D UNet.

**Comment by SimonBiggs** [comment]
@rickardcronholm, can I ask, how did you get it working? What did you find the issue was when trying to first load the web page?

**Comment by rickardcronholm** [comment]
I'm afraid this will not be a very helpful report;
The status was stuck at "connecting to streamlit server". At a later time,
I refreshed the page and then it work. I revisited the page another time
and was again unable to connect to the stremlit server.

**Comment by SimonBiggs** [comment]
> I'm afraid this will not be a very helpful report

I suspect that is quite helpful. For the time being, I'm just hosting this on my own machine locally. I need to get this demo (as well as the API) into the cloud onto a scaling cluster. That way bursts of traffic won't interrupt the demo or the API itself.
