### ISSUE TITLE
Image Position Patient should be adjusted as well as Slice Location when extending CT

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1463]
https://github.com/pymedphys/pymedphys/blob/83f02eac6549ac155c6963e0a8d1f9284359b652/lib/pymedphys/_dicom/ct/extend.py#L138

Similar logic needs to be applied.
Take the vector difference of the image position patient with the adjacent slice, and increment using that.

**Comment by SimonBiggs** [comment]
I believe it was being applied both in the old version and the one in the new PR:

https://github.com/pymedphys/pymedphys/blob/0ddb92232bf497841182a6af6bf542bd42c1ffc5/lib/pymedphys/_dicom/ct/extend.py#L96

**Comment by sjswerdloff** [comment]
> I believe it was being applied both in the old version and the one in the new PR:
> 
> https://github.com/pymedphys/pymedphys/blob/0ddb92232bf497841182a6af6bf542bd42c1ffc5/lib/pymedphys/_dicom/ct/extend.py#L92-L96

Ah... I see now. It must have gotten folded due to being unchanged.
