### ISSUE TITLE
Improve wording within Elekta project doc

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#147]
Need to improve the following wording:

> These logfiles can be extracted and then associated to a patient’s record using Mosaiq SQL. This is achieved by aligning the logfile to the recorded delivery time as well as other parameters such as field ID and description the logfile is aligned to Patient Name and ID. Example SQL to achieve this looks like the following

**Comment by mchamberland** [comment]
You can query the Mosaiq database with Python?! Do you have any documentation on this? What are the capabilities? Could you, e.g., get all the parameters of a scheduled treatment plan and compare them to the DICOM RT files exported from a TPS?

**Comment by SimonBiggs** [comment]
Certainly can, there is a whole module in PyMedPhys supporting just that workflow:

https://github.com/pymedphys/pymedphys/tree/master/src/pymedphys/msq

A useful function is the following:

https://github.com/pymedphys/pymedphys/blob/master/src/pymedphys/msq/_level2/msqdelivery.py#L344

Its usage would be something like the following (excuse mistakes, just writing this on my phone, I'll check it next time I'm at a PC):

```python
from pymedphys.msq import mosaiq_connect, delivery_data_from_mosaiq

mosaiq_hostname = 'something'
with mosaiq_connect(mosaiq_hostname) as cursor:
    delivery_data = delivery_data_from_mosaiq(cursor, field_id)
```

To get a list of MOSAIQ field IDs for a given patient ID use the following function as so 

https://github.com/pymedphys/pymedphys/blob/master/src/pymedphys/msq/_level2/msqhelpers.py#L65

```python
from pymedphys.msq import mosaiq_connect, get_patient_fields

mosaiq_hostname = 'something'
with mosaiq_connect(mosaiq_hostname) as cursor:
    patient_fields = get_patient_fields(cursor, patient_id)
```

**Comment by SimonBiggs** [comment]
As a note, MOSAIQ doesn't like having its connection opened and closed lots of times. Don't enough and you'll be temporarily blocked.

Best idea is to do everything you want with MOSAIQ in one swoop within one block of `with mosaiq_connect(mosaiq_hostname) as cursor:`

**Comment by SimonBiggs** [comment]
Also, when you go to connect to MOSAIQ for the first time you'll be prompted for a username and password. I recommend using the reports user. It only has data reader access, not write access. That's an important layer of protection, not allowing any code you or others write to edit the database.

**Comment by mchamberland** [comment]
This is a game changer! Thanks a lot!

**Comment by SimonBiggs** [comment]
You're very welcome. If you do build things with it, consider making your own section within the labs within PyMedPhys:

http://pymedphys.com/en/stable/developer/labs.html

It would be great to be able to get the ball rolling on a collaboration with what we can do with these sorts of things.

**Comment by SimonBiggs** [comment]
I'd be more than happy to help you out getting started.

**Comment by mchamberland** [comment]
Awesome, thanks! I'm a big believer in free open source projects such as this one. I hope to contribute a few things.

By the way, would a toolkit for EGSnrc be relevant to PyMedPhys? I've put it up [here](https://bitbucket.org/marcchamberland/egs_tools/src/master/).

**Comment by SimonBiggs** [comment]
@mchamberland certainly some of the tools you've got in there. For example, I could imagine the following conversion between RT DICOM dose and EGS 3ddose files would certainly be appropriate:

https://bitbucket.org/marcchamberland/egs_tools/src/2ab4757f4aaa9cdd54807107d40123288c312a3c/dose_distribution/dose3d.py?at=master&fileviewer=file-view-default#dose3d.py-229:269

It would require that a range of tests are created that appropriately covered the functions, but apart from that I think some key parts of that library would be brilliant additions. For testing examples see files such as:

https://github.com/pymedphys/pymedphys/blob/master/tests/test_dicom/test_header_tweaks.py

**Comment by SimonBiggs** [comment]
I personally have had very little to do with EGS, but I think it would be quite nice to have a whole section of PyMedPhys dedicated to Python EGS tools. Might even be able to use docker within the PyMedPhys library to make the installation rather seamless...

**Comment by SimonBiggs** [comment]
For example... we could turn this:

https://github.com/nrc-cnrc/EGSnrc/wiki/install-EGSnrc-on-windows

Into something closer to this:

* Install Python
* Install Docker
* Install PyMedPhys
* Run `pymedphys docker egsnrc` to have access to a range of tools hosted within your browser using a Jupyter Lab + EGSnrc

**Comment by mchamberland** [comment]
@SimonBiggs  Very good ideas. Let me get through my board exam first! (Scheduled for mid-May.) I'll have more time once that's done.

**Comment by SimonBiggs** [comment]
Sounds like a plan. I'll be up at ICCR in Montreal in June. Will you be going?

**Comment by mchamberland** [comment]
I’ll probably be there for MCMA and the day of overlap with ICCR.

**Comment by mchamberland** [comment]
@SimonBiggs  I don't know much about the Mosaiq backend and SQL. Is the reports user a standard user account for SQL databases? If I ask my IT team for the reports user credentials, will they know what I'm talking about? Or is it something that needs to be setup?

Also, I briefly glanced at the Mosaiq stuff, but it seems like I only need a hostname and port (and user account, of course) for SQL access?

**Comment by SimonBiggs** [comment]
That's right. Hostname, port (which is usually default, so you can usually
leave that out), username and password. You supply hostname and port to the
function, then it requests a username / password from you which it will
remember for future runs.

The reports user is a default account that Elekta builds in to MOSAIQ for
every release. There's a chance that anyone who uses crystal reports in
your centre would know that login. Otherwise IT might know, or they might
make a new account. As long as the account has only read-only access that
is fine. Read only access is called something like db_data_reader access or
something like that.

If those people can't help, calling someone from Elekta should work also.

Cheers,
Simon

**Comment by mchamberland** [comment]
@SimonBiggs  It works! Thanks a lot!

**Comment by SimonBiggs** [comment]
You are very welcome :). As you're using the API let me know if you're having any issues/pain points recommendations. That's am API I'm going to want to stabilise sooner rather than later. But it would be nice to have it gone through its paces with more than just me.

**Comment by SimonBiggs** [comment]
Also, some other work that is required with this one is I need to have a neat way to test it. I was thinking of building a dummy MOSAIQ database that can be used by pytest.

At the moment that part of the library is not within the automated testing suite. If you have some key use cases of this code maybe submit some tests that cover your usecases. That way there is a bit of assurance that I'm not going to break something that works for you?

**Comment by mchamberland** [comment]
Sure. As I work with it, I'll report back on how I'm using and try to submit tests for it.

On a related note (for my future use cases), I will need [DICOM RT Plan support](https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_dicom/src/pymedphys_dicom/dicom/_level3/dicom_collection.py#L175), which seems to not be implemented yet. Is anyone working on it?

Before finding out about this project, I had been looking into [DVH-Analytics ](https://github.com/cutright/DVH-Analytics/blob/master/dvh/modules/tools/io/database/dicom/parser.py#L68) and [dicompyler-core ](https://github.com/dicompyler/dicompyler-core/blob/master/dicompylercore/dicomparser.py#L796). Those may be useful to see how other people have handled it.

**Comment by SimonBiggs** [comment]
Yup, that is most certainly in the pipeline. There is already some experimental code that achieves this:

* https://github.com/pymedphys/pymedphys/blob/master/notebooks/logfiles/Varian_mudensity/01-mu-density-for-dicom-plan.ipynb
* https://github.com/pymedphys/pymedphys/blob/master/notebooks/dcmplan/13-abstract-figures.ipynb

Also the logfile --> DICOM RT direction for recalcing of plans within TPS or independent calc software is what I am presenting on at ICCR:

https://easychair.org/smart-program/ICCRMCMA2019/2019-06-20.html#talk:96088

**Comment by SimonBiggs** [comment]
No guarantee that some of the APIs in those notebooks are still there... the notebooks themselves are not run through our testing suite.
