### ISSUE TITLE
Documentation contribution doc

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#148]
* provide a link to the original contributor docs
* Ask users to install `pip install -e .[docs]` as that will get the dependencies from setup.py

**Comment by Centrus007** [comment]
See #149

**Comment by SimonBiggs** [comment]
Awesome! Thanks Matt :). I was scrolling through the docs on my phone this morning, wasn't near a computer when I thought of the issues, figured it was worth making an issue before I forgot.

Fixed in https://github.com/pymedphys/pymedphys/pull/149

**Comment by Centrus007** [comment]
No worries :)
