### ISSUE TITLE
Running the docs tests locally

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#151]
Quick question: how do I run the doc tests locally?

**Comment by SimonBiggs** [comment]
`sphinx-build -W` should do the trick. Possibly even `sphinx-autobuild -W docs docs/_build/html` will also work, meaning you can have live feedback on your changes in the console.

**Comment by SimonBiggs** [comment]
...that's worth adding to the docs potentially...

**Comment by SimonBiggs** [comment]
> ...that's worth adding to the docs potentially...

Just added it to the most recent pull request you did. :)

**Comment by Centrus007** [comment]
Perfect!
