### ISSUE TITLE
Document how to extract the logfiles from the backups

### ISSUE THREAD

**Issue by randomaztec** [pymedphys/pymedphys#153]
removed query answered elsewhere
trf files are not available on synergy models as per presentation below

http://chapter.aapm.org/nccaapm/z_meetings/2017-04-07/04_Agenda_and_Presentations/1145_Wiesmeyer_2017-Spring-Meeting.pdf

**Comment by SimonBiggs** [comment]
Hi @randomaztec

We have an Elekta Synergy with an Agility head. Not sure if the Agility head makes the difference, but our logfiles are accessible as long as the diagnostics backups are running.

I have created a tool that automatically pulls from the backup shared drive, then queries MOSAIQ to index them. I need to get the chance to write up the documentation for using those tools. Once that documentation is ready it shall appear at https://pymedphys.com/en/stable/projects/elekta-logfiles.html#basic-implementation

As a stop gap, before that documentation arrives, here is a method to manually extract those logfiles.

Run the diagnostics backups, either on a schedule, or trigger the backup manually.

Download the diagnostics backups from the NSS shared drive.

To get this NSS backup, let me explain a few things:

The Linac has two networks. It has an internal network and a hospital network. The NSS is the firewall between the two. The NSS has an IP address on the hospital network. All you need to do is type in the IP address of the NSS on another computer into a file browser that is also on the hospital network and then you should be able to access the backup files. The address in your file browser you want to write might look something like:

\\192.168.1.40\Backup\TCS

At that point you need to provide an NSS password on your personal computer. Precede the user name with a backwards slash. 

For example, if the user name password combinations on the NSS is "george", "macdonald" then you would write within username on your PC's login prompt "\george", and password you would write "macdonald".

You'll need to talk to someone in your centre, that Elekta engineer would be perfect, for one of those user/password combinations.

From there, as long as a diagnostic backup has been run, you'll find some files that start with SDD and end in .zip. You can then copy those, and extract them to your local machine. These trf zip files are not encrypted. The TRF files themselves can then be decoded with my TRF decoder tool. A bunch of the files in there are .trf files, they're the ones that can be decoded.

I have written tools that automatically pull these SDD files, then use MOSAIQ SQL to index them by patient ID. They are in the process of having docs written up also. But the first parts of the docs for that tool can be found at https://pymedphys.com/en/stable/user/interfaces/cli/logfile.html

**Comment by SimonBiggs** [comment]
Also, wanted to add, this is the perfect forum for questions. See:

http://pymedphys.com/en/stable/getting-started/faq.html#i-need-help-how-do-i-ask-for-help

**Comment by mchamberland** [comment]
@SimonBiggs Hey, in the process of trying to push dicom files to Service Mode for Winston-Lutz (see #584), I ended up enabling the NSS shared drive, so I have access to trf files now!

Is there any documentation about logfiles analysis? Or can you give me a just a very quick rundown of the tools available right now? I can figure out most of it by looking through the repo, but you may be able to give me a head start.

**Comment by SimonBiggs** [comment]
Certainly :) How bout I describe our setup.

At `D:\LinacLogFiles` on a server that can access the diagnostic backups I have the following files:

[config.zip](https://github.com/pymedphys/pymedphys/files/4042844/config.zip)

Of importance, within Windows credential manager on the computer running the logfile code the NSS share login needs to be saved. The `.bat` file in there is set within Windows scheduler to run each night. It searches each of the Linac IPs detailed, it downloads the diagnostic backups, extracts the `.trf` files, and then logs in to Mosaiq to identify them.

Once you have identified logfiles we then run the following notebook to log into mosaiq, look at our QCLs, and then based on the outstanding QCLs we go and read the MLC shapes directly our of Monaco's `tel.1` files and compare them to the logfile record via a sort of fluence comparison:

https://github.com/pymedphys/pymedphys/blob/master/examples/site-specific/cancer-care-associates/production/Logfiles/MU%20Density/QCL%20Based%20Logfile%20to%20Monaco%20Comparison.ipynb

Hopefully that gives you a bit of a kick start :).

**Comment by SimonBiggs** [comment]
If you did want to throw your experience in a document of some sort I would absolutely love to be able to add that to the documentation.......

**Comment by mchamberland** [comment]
Thanks, very helpful!

I'll try to keep notes on what I do. Still not sure what I want or can do with those log files, so this is all exploratory.

**Comment by SimonBiggs** [comment]
I also have some code that maps the log file to a DICOM plan file for sending back to the TPS if that is helpful.

**Comment by SimonBiggs** [comment]
Also, within those backups is also an `RMX` file. I have only had an initial investigation, but I believe that file contains the record of all of the Linac set numbers (2RI Ctrl etc). It would be quite great to be able to decode those into a human readable format.

**Comment by Son21042022** [comment]
> Hi @randomaztec
> 
> We have an Elekta Synergy with an Agility head. Not sure if the Agility head makes the difference, but our logfiles are accessible as long as the diagnostics backups are running.
> 
> I have created a tool that automatically pulls from the backup shared drive, then queries MOSAIQ to index them. I need to get the chance to write up the documentation for using those tools. Once that documentation is ready it shall appear at https://pymedphys.com/en/stable/projects/elekta-logfiles.html#basic-implementation
> 
> As a stop gap, before that documentation arrives, here is a method to manually extract those logfiles.
> 
> Run the diagnostics backups, either on a schedule, or trigger the backup manually.
> 
> Download the diagnostics backups from the NSS shared drive.
> 
> To get this NSS backup, let me explain a few things:
> 
> The Linac has two networks. It has an internal network and a hospital network. The NSS is the firewall between the two. The NSS has an IP address on both the hospital network and the Linac network. For our purposes here we are interested in the NSS hospital network IP. All you need to do is type into a file browser the hospital network IP address of the NSS on another (non-Elekta) computer that is also on the hospital network and then you should be able to access the backup files. The address in your file browser you want to write will look something like:
> 
> ```
> \\[NSS Hospital IP]\Backup\TCS
> ```
> 
> For example, if your NSS Hospital IP is 192.168.1.40 then you would write:
> 
> ```
> \\192.168.1.40\Backup\TCS
> ```
> 
> At that point you need to provide an NSS password on your personal computer. Precede the user name with a backwards slash.
> 
> For example, if the user name password combinations on the NSS is "george", "macdonald" then you would write within username on your PC's login prompt "\george", and password you would write "macdonald".
> 
> You'll need to talk to someone in your centre, that Elekta engineer would be perfect, for one of those user/password combinations.
> 
> From there, as long as a diagnostic backup has been run, you'll find some files that start with `SDD` and end in `.zip`. You can then copy those, and extract them to your local machine. These trf zip files are not encrypted. The TRF files themselves can then be decoded with the `pymedphys` TRF decoder tool. A bunch of the files in there are `.trf` files, they're the ones that can be decoded.
> 
> I have written tools that automatically pull these SDD files, then use MOSAIQ SQL to index them by patient ID. They are in the process of having docs written up also. But the first parts of the docs for that tool can be found at https://pymedphys.com/en/stable/user/interfaces/cli/logfile.html

Hi @SimonBiggs, I tried extracting the log file your way, but we only get the .dat file but not the .trf file. We hope to have your support to be able to extract the trf log file. Best regards

**Comment by SimonBiggs** [comment]
@mchamberland, do you have any idea what might be going on here for @Son21042022?

**Comment by Son21042022** [comment]
Dear Mr Simon Biggs,
I have exported the trf files; however, I am encountering difficulties when
trying to convert them into csv files that contain the necessary MLC,
gantry, and CP information.
I would greatly appreciate your assistance in facilitating this conversion
process, as it is quite important for my work.
I am looking forward to your prompt response so that I can proceed further.
Thank you for your attention to this matter.
Best regards,
Nguyen Khac Son
Medical Physicist
Lam Dong Hospital, Vietnam


Vào Th 6, 10 thg 5, 2024 vào lúc 12:30 Simon Biggs <
***@***.***> đã viết:

**Comment by SimonBiggs** [comment]
Hi Nguyen Khac Son,

Can you provide details of your error messages and an overview of what you have tried as well as a minimum reproducible example:
https://stackoverflow.com/help/minimal-reproducible-example

May you also do this in a fresh issue, as this issue you have posted on is currently closed.

**Comment by Son21042022** [comment]
Dear Mr Simon Biggs,
Thank you for your support.
After carefully reviewing the instructions provided by pymedphys, we
successfully converted the trf file to csv file format.
Thank you again very much.
Best regards,
Nguyen Khac Son
Medical Physicist
Lam Dong Hospital, Vietnam

Vào Th 4, 25 thg 9, 2024 vào lúc 02:54 Simon Biggs <
***@***.***> đã viết:

**Comment by SimonBiggs** [comment]
I am glad to hear it :)

**Comment by Son21042022** [comment]
Dear Mr Simon,
We successfully converted the trf file to csv file format. However, in csv
file, there is no information about control point, all control point values
are equal to 1, how can we extract control point values?
Look forward to hearing from you!
Best regards,
Nguyen Khac Son
Medical Physicist
Lam Dong Hospital, Vietnam

Vào Th 5, 26 thg 9, 2024 vào lúc 02:00 Simon Biggs <
***@***.***> đã viết:

**Comment by SimonBiggs** [comment]
Hi Nguyen Khac Son,

Can you provide a minimal reproducible example (data included):
https://stackoverflow.com/help/minimal-reproducible-example

May you also provide this in a fresh issue, as this issue you have posted on is currently closed.
