### ISSUE TITLE
`zyx_and_dose_from_dataset` gives incorrect coords for non-square pixel values

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1570]
See https://pymedphys.discourse.group/t/gamma-index-calculation-possible-issues/191 for the full details.

Thanks @cedricbelanger for the report and subsequent investigation into the cause.

For reference, here is the section of code which needs adjustment:

https://github.com/pymedphys/pymedphys/blob/17b99b22bc5868666648fd23fb0dfcd3e39de761/lib/pymedphys/_dicom/coords.py#L132-L136

**Comment by SimonBiggs** [comment]
@pchlap might you be in a position to help me onboard @cedricbelanger into creating a PR to fix this issue?

**Comment by pchlap** [comment]
@SimonBiggs Yep sure I'd be happy to help however I can :)

**Comment by SimonBiggs** [comment]
Awesome :slightly_smiling_face:, thanks @pchlap

**Comment by Matthew-Jennings** [comment]
I'm sorry I missed this. I think this is a relatively serious error and ought to be fixed ASAP.

@cedricbelanger, would you like to do the honours? Very happy to help if you would. But if not, let us know and I'll rectify asap.

**Comment by SimonBiggs** [comment]
Hi @Matthew-Jennings,

This was actually all fixed up over in:

https://github.com/pymedphys/pymedphys/pull/1575 :slightly_smiling_face:

So, we can actually close this one :slightly_smiling_face:.

**Comment by SimonBiggs** [comment]
The original PR came from @cedricbelanger:

https://github.com/pymedphys/pymedphys/pull/1571

**Comment by Matthew-Jennings** [comment]
Gotcha, sorry, I should've checked more carefully!

**Comment by SimonBiggs** [comment]
> Gotcha, sorry, I should've checked more carefully!

All good :slightly_smiling_face:, the issue was open so reasonable to assume the issue still exists without needing to dive too much into it :slightly_smiling_face:.

**Comment by SimonBiggs** [comment]
By the way, the discussion over at https://pymedphys.discourse.group/t/gamma-index-calculation-possible-issues/191 is a pretty amazing read. @cedricbelanger did some brilliant detective work, as well as produced the fix. It was a great testament to the mistakes we can make, as well as the benefit of having an open source repository like PyMedPhys where we can fix each other's mistakes.
