### ISSUE TITLE
Issue on page /lib/howto/gamma/from-dicom.html

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1581]
Hello,

If I only want to compare two 1-D data in ASCII, what should I do using the gamma function?'

Thank you so much!

Fada

**Comment by SimonBiggs** [comment]
Hi @guanfada,

Can you give an example of the data?

Cheers,
Simon

**Comment by SimonBiggs** [comment]
For others following along this issue was discussed and solved over at:

https://pymedphys.discourse.group/t/gamma-index-for-1d-data/194?u=simonbiggs

**Comment by SimonBiggs** [comment]
Also, @guanfada, would you be interested in uploading your 1D gamma example to the docs as a notebook?

**Comment by guanfada** [comment]
@SimonBiggs 
Hi Simon, sure thing. I will do that later today or tomorrow. Let me learn how to upload notebook first :-)

**Comment by SimonBiggs** [comment]
Did you want a hand?

It might be best to learn to use git if you're planning on contributing
more. I could jump on a video call and show you the ropes if you like?

**Comment by guanfada** [comment]
Hi Simon, 
Sorry for my late reponse. I had a super busy weekend. I will try it myself first and then let you know :-)

**Comment by guanfada** [comment]
I have this error when I run 
poetry install -E dev
on Windows 10 using powershell
![image](https://user-images.githubusercontent.com/25382578/144978878-b9f73e16-bebd-4763-a70b-d23a13a74d5a.png)

**Comment by guanfada** [comment]
I have python 3.9 from Microsoft store

**Comment by SimonBiggs** [comment]
I think the most painful thing about poetry is its non-helpful error
messages.

I can't immediately work out what's going wrong when you show me that.

There is also a requirement-dev.txt file, might you be able to install that
instead with pip install -r requirements-dev.txt?

**Comment by guanfada** [comment]
I tried pip install -r requirements-dev.txt
and then got this error

![image](https://user-images.githubusercontent.com/25382578/145061133-6410385f-eb80-40af-9bc2-f4c3e18c80d2.png)

**Comment by SimonBiggs** [comment]
Can you do:

pip install setuptools

And then try again?

**Comment by SimonBiggs** [comment]
Also, before running `pip install setuptools` to attempt to fix the issue, can you make a new issue on GitHub that says something like "unable to install development version of pymedphys" and then copy in the error message text as plain text (instead of an image). That way when someone Google searches for that particular error message they will be able to find the issue with the solution :) (once we've solved it :) )

**Comment by guanfada** [comment]
sure, will do. thank you.

**Comment by guanfada** [comment]
after a long try, I finally solved the issues. I will open a new issue to post the problems and the solutions.

**Comment by SimonBiggs** [comment]
Thanks @guanfada :slightly_smiling_face:.

The following document is quite empty:

https://github.com/pymedphys/pymedphys/blob/main/CONTRIBUTING.md

If you there are some additions for there that you think could help someone like yourself get started in the future (even just a small couple of additions), it'd be awesome if you could add them in.

**Comment by guanfada** [comment]
Once I gain more experience, I will be happy to contribute to this page.
Pls give me some time to learn first, LOL

**Comment by SimonBiggs** [comment]
> Pls give me some time to learn first, LOL

Of course :slightly_smiling_face:
