### ISSUE TITLE
A logo...

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1586]
So, I figured, in preparation for this new PyMedPhys release I should actually get around to making a logo for my new company so that it can be on the team page. So, my wife and I got to making something last night. I'd be pretty keen for some feedback from you guys to see what you think :slightly_smiling_face:

![logo-draft](https://user-images.githubusercontent.com/6559099/144734333-546adfa6-2233-48f5-a628-c09282d013d7.png)

Keen for your thoughts :slightly_smiling_face:. 

Cheers,
Simon

**Comment by pchlap** [comment]
Not bad @SimonBiggs, if I'm honest it took me a minute to interpret it. But now I see AI written using some RT Beams...!? Perhaps a physicist might have seen that a bit quicker than me :D

**Comment by SimonBiggs** [comment]
Maybe if I made the logo be grey scale instead? I'm not sure... And maybe
the AI beams need to be more clearly looking like isodoses...

Hmm... Certainly more work to go on that one...

**Comment by SimonBiggs** [comment]
I think I'll give the logo a pass for this release. Maybe in time for the next release :slightly_smiling_face:.
