### ISSUE TITLE
[solved] unable to install development version of pymedphys on Windows 10 & solutions

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1587]
https://docs.pymedphys.com/contrib/setups/setup-win.html

(1) I tried to follow the guide here to install the development version of pymedphys on Windows 10.
I first installed the latest version of Anaconda (Anaconda3-2021.11-Windows-x86_64.exe) which has python 3.9
I set its installation folder "anaconda3" and its sub folder "anaconda3\Scripts" in path environmental variable. 

(2) Then I tried to install poetry in cmd
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
it always shows this error: 
**Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings**

(3) I searched online, the solution is:
go to Manage App Execution Aliases and turn off Python.exe and Python3.exe there. 
![image](https://user-images.githubusercontent.com/25382578/145136724-9a06bf62-35cc-477e-9359-3064a23429da.png)

(4)
now the installation of poetry is ok, but after installation, when I typed
poetry --version
Then I got the below error:
**ModuleNotFoundError: No module named 'cleo'**

(5)then I guessed it may be anaconda3's issues, so I installed the python 3.10 and later 3.9 from python.org, but this still has the same issue No module named 'cleo'** for poetry --version.

(6) I then installed the python3.7.5 form python.org and set its installation and Scripts directories to path environmental variable. 
now poetry --version gave me Poetry version 1.1.12

(7) then I followed 

git clone https://github.com/pymedphys/pymedphys.git

cd to the pymedphys directory
below two commands worked fine

poetry install -E dev
poetry run pre-commit install

**Comment by SimonBiggs** [comment]
I think we need to change from recommending an Anaconda install to instead recommend just directly installing from the Microsoft Store.

**Comment by guanfada** [comment]
The **"No module named 'cleo'** " for poetry --version** issue is caused by python 3.9 or python 3.10.
Using python 3.7 can solve it.

**Comment by SimonBiggs** [comment]
> The **"No module named 'cleo'** " for poetry --version** issue is caused by python 3.9 or python 3.10.
> Using python 3.7 can solve it.

That's painful... hmmm... we can't really have a PyMedPhys development environment for Windows stuck on Python 3.7 ...

Maybe for Windows we recommend not using poetry at all? Instead using the requirements files? Hmm, not sure.

**Comment by guanfada** [comment]
Let's see :-)

**Comment by sjswerdloff** [comment]
See https://github.com/python-poetry/poetry/issues/3345

which discusses the inability to import cleo in various circumstances and environments, as well as asdf

I don't know if the solution is there, but it is worth a look.
