### ISSUE TITLE
add the 1D gamma analysis example to PyMedPhys

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1593]
Hi Simon,

As we discussed before, I would like to add one example page for 1D gamma analysis.
https://pymedphys.discourse.group/t/gamma-index-for-1d-data/194/7

Please advise what I should do to add this page.

Fada

**Comment by SimonBiggs** [comment]
All you need to do is create a Jupyter Notebook file with Jupyter Lab that has your demo in it, and then drop that file in the same directory as the other gamma code, and then lastly, add the path to your file in the following location:

https://github.com/pymedphys/pymedphys/blame/main/lib/pymedphys/docs/index.rst#L45

Cheers :),
Simon

**Comment by guanfada** [comment]
Nice!
Will do. Thank you :-)

**Comment by guanfada** [comment]
Where should I put the two input .csv files containing the reference and evaluation dose data in 1D?

**Comment by SimonBiggs** [comment]
If they're small enough you might be able to just be able to copy the data
into the notebook? If that's too messy, I'll give you a separate approach.
Let me know :)

**Comment by guanfada** [comment]
Please tell me the separate approach to store these two input files:-)

**Comment by SimonBiggs** [comment]
Upload the files to the following repo:

https://github.com/pymedphys/data

Then use the online link to those files:

https://github.com/pymedphys/data/raw/<commit-hash-goes-here>/<filename-goes-here>

As a means to download them within a notebook using the following steps:

```python
url = 'https://github.com/pymedphys/data/raw/<commit-hash-goes-here>/<filename-goes-here>.csv'
save_filepath = 'the-download-filename.csv'

urllib.request.urlretrieve(url, save_filepath)
```

Then you can load up the csv files as desired :).

See the following notebook where I used that approach:

https://colab.research.google.com/github/RadiotherapyAI/unet-workshop/blob/4595ed6be68134ce3707e8628d2532a8a1119ea9/unet.ipynb#scrollTo=8f980fd7

**Comment by guanfada** [comment]
![image](https://user-images.githubusercontent.com/25382578/145516737-c560596e-d221-494c-9f49-7d3a24366f21.png)

**Comment by SimonBiggs** [comment]
Just sent an org invite, that should fix it

**Comment by guanfada** [comment]
just uploaded two .csv files. Thank you.
next question is where to get the commit-hash?

**Comment by SimonBiggs** [comment]
Click here:

![image](https://user-images.githubusercontent.com/6559099/145517920-c5a6a46a-c3ee-46ee-9e8f-7a55f9695304.png)

Then you have the hash here:

![image](https://user-images.githubusercontent.com/6559099/145517963-64b32cc3-694e-4bf6-9f20-3ee5cb3cfaaa.png)

**Comment by guanfada** [comment]
Got it. Thanks.
next, 
![image](https://user-images.githubusercontent.com/25382578/145518409-cf5a8d76-d68f-4af4-91a9-ac732266e648.png)
I could not edit this page to insert a line like
lib/howto/gamma/from-1D-ascii

**Comment by SimonBiggs** [comment]
You could edit it locally on your own machine, or use the edit button at
the following links:

[image: image.png]
https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/docs/lib/howto/index.md
https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/docs/index.rst

**Comment by SimonBiggs** [comment]
Probably best doing it locally though so that you can build the docs and
see that they look how you desire

**Comment by guanfada** [comment]
copy that.

**Comment by guanfada** [comment]
I modified the index.rst in pymedphys\lib\pymedphys\docs
![image](https://user-images.githubusercontent.com/25382578/145526417-62dc14ce-18c3-4981-b9f8-06dca13eb012.png)
and
pymedphys\lib\pymedphys\docs\lib\howto\gamma
![image](https://user-images.githubusercontent.com/25382578/145526696-63b85237-ae0d-4f45-85f9-e60ed6ca885e.png)

I don't think I need to modify this file index.md in pymedphys\lib\pymedphys\docs\lib\howto

but after
`poetry run pymedphys dev docs`

I can see its HTML 
![image](https://user-images.githubusercontent.com/25382578/145527993-58fa08c5-35a5-49a2-a3ea-cfa94cc6c55b.png)

But I could not see the links to it under "How-To" and "How-to guides"

**Comment by SimonBiggs** [comment]
You may need to run poetry run pymedphys docs --clean first

**Comment by guanfada** [comment]
I run
poetry run pymedphys dev docs --clean

then
poetry run pymedphys dev docs

but still no luck :-(

**Comment by SimonBiggs** [comment]
I'm going to have to get back to this over the weekend. Let me get back to
you then :)

**Comment by guanfada** [comment]
No problem. Thank you.

**Comment by guanfada** [comment]
Any updates on this? 
I still couldn’t figure it out.
Thank you.

**Comment by SimonBiggs** [comment]
@Matthew-Jennings might you be able to jump in and help here?

**Comment by Matthew-Jennings** [comment]
Hi there, @guanfada.

How have you made these edits? Have you created a new git branch? If so, could you please publish it to Github and create a new Pull Request?

**Comment by guanfada** [comment]
I just uploaded this new 1D gamma example Jupyther file and created a new pull request. Thank you! @Matthew-Jennings @SimonBiggs

**Comment by SimonBiggs** [comment]
Yup, that all looks good :) Once the tests pass I'll merge it, and ~10 mins after that the new page will be live on the docs :)
