### ISSUE TITLE
Multiple dependencies dropped Python 3.7

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1618]
We'll be needing to follow suite for version 0.39.0.

To-do list when dropping Python 3.7:

- [x] Verify docs build on Windows on > Python 3.7
- [x] Remove libjpeg pinning https://github.com/pymedphys/pymedphys/pull/1619#event-6055169151
- [x] Flag with CCA the dropping of 3.7

**Comment by Matthew-Jennings** [comment]
See #1645 for point 1.

**Comment by Matthew-Jennings** [comment]
Point 2 resolved in #1648

**Comment by SimonBiggs** [comment]
Heads up @msobolewski and @JacobMcAloney,

The next release of PyMedPhys will no longer support Python 3.7 which is what is deployed across CCA. So, to use any updates that come through, Python will also need to be updated.

Also might be worth noting that the Python 3.7 end of life is in 12 months (27 June 2023). After that point Python 3.7 will no longer be receiving security updates.

Cheers :),
Simon

**Comment by SimonBiggs** [comment]
Thanks @Matthew-Jennings for your work here :slightly_smiling_face:
