### ISSUE TITLE
Make end of contributor docs use code sections instead of italics

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#162]
See https://photos.app.goo.gl/Rd9HWijRfDmcvRWy6

**Comment by Centrus007** [comment]
You prefer scrolling over wrapping???

Seems a little contradictory to your love of 80 char line length :stuck_out_tongue:

**Comment by SimonBiggs** [comment]
Oh I just meant replacing `text` with ``text``
