### ISSUE TITLE
Should we include instructions on creating and working within a conda environment in the developer guide?

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#163]

**Comment by SimonBiggs** [comment]
What's the use case?

**Comment by Centrus007** [comment]
If the developer has any other Python projects (which is very likely), separating them into their own environments avoids incompatible packages and conveniently facilitates multiple, well-organised Python installations. For example, I have a Python 2.7 environment for RayStation scripts, I have an environment that requires pydicom < 1.0, etc.

Similarly, I think it would simplify deployment when the time comes. E.g. using an environment.yml file to deploy a specific environment onto an existing Python/Conda installation, which may consist of other, potentially clashing, environments.

I'm generally a believer in performing all development from within isolated environments. It's kinda the whole point of conda...

**Comment by SimonBiggs** [comment]
> Isn't it basically the whole point of conda (vs. pip)?

`pip` has `virtualenv` so it certainly isn't a differentiator between the two. The primary difference between the two is `conda` has people compiling sets of packages along with all of their dependencies. Essentially it boils down to `conda` is easier if your using a non-developer oriented operating system (Windows).

I think once we get to making recommendations for environment handling we should defer to other resources. Here are two good examples:

* pip and virtualenv -- https://docs.python-guide.org/dev/virtualenvs/
* conda -- https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-python

But it would certainly be worthwhile having a link :)

**Comment by Centrus007** [comment]
Hmm, I agree that we ought not to provide a *tutorial* as such, more like a recommendation and simple instructions to get started along with the existing ones. for example, we have done similar for the following:

- Recommended VS Code (not at all necessary) and provided relatively detailed installation instructions
- Recommended Chocolatey (not at all necessary) to install Git, etc. and provided an install link
- Recommended Cmder (not at all necessary) and provided a couple of specific installation instructions
- Provided simple instructions for using git, e.g. how to:
  - Clone the repo, with commands
  - Stage, commit and push changes to GitHub.
  but included a recommendation to read up and learn more, with links.

I guess I'm proposing we do something similar for conda to what we did for Git. Namely that we add a `conda env create` as part of the `pymedphys` install process, briefly explain that this provides an isolated environment within which to do pymedphys coding, and then provide links to further reading on the subject

**Comment by Centrus007** [comment]
You're right, I'd forgotten `venv`. Been using `conda` far too long now, hehe.

There's no harm in picking one to recommend and provide instructions for though - we did exactly that for VS Code and Cmder.

**Comment by SimonBiggs** [comment]
There is one difference though, everything we laid out is needed knowledge
to get someone up and running.

...handling an environment adds an extra layer of complication that
strictly isn't required to meet those aims.

But, granted, the concept is helpful... Maybe there is value in having a
separate document similar to how we have the documentation one?

**Comment by Centrus007** [comment]
> There is one difference though, everything we laid out is needed knowledge to get someone up and running.

I dunno about that. E.g., I don't think a terminal is strictly needed.

**Comment by SimonBiggs** [comment]
> I dunno about that. E.g., I don't think a terminal is strictly needed.

Touche :). Would you be happy with the idea to have the environment docs be
a separate document as opposed to combined with the primary contribution
docs?

**Comment by Centrus007** [comment]
Adding it at all is s strong preference of mine. But I do think that, if we do add it, it doesn't *really* warrant another page (I'm talking about maybe 6-7 lines of text here.) and might even add to confusion enough that it's better not to have it at all...

I'm imagining the following:

A budding PyMedPhys contributor makes it to the developer-setup page. They make it through the setup and are all like "Alright, I'm all set up, yay!" They explore the docs further and come across the separate conda environments page. They read it and soon they get confused: "Wait, I was supposed to create an environment and install pymedphys in there? Why wasn't this in the setup page?"

It will directly contradict the setup page if not embedded within it. And since we're talking such little text...

As for confusion, I would cheekily point out that handling environments is a walk in the park compared to our levelling system! From personal experience, I've found new pythonistas embrace and understand environments pretty quickly, if taught well. I'm not seeing much of a downside here...

**Comment by SimonBiggs** [comment]
> (I'm talking about maybe 6-7 lines of text here)

> It will directly contradict the setup page if not embedded within it. And since we're talking such little text...

> From personal experience, I've found new pythonistas embrace and understand environments pretty quickly, if taught well. I'm not seeing much of a downside here...

Sounds good :). I'm convinced.
