### ISSUE TITLE
Complexity index VMAT

### ISSUE THREAD

**Issue by zism** [pymedphys/pymedphys#1631]
Hi, I'm looking to calculate segment area and total beam area from a DicomRT VMAT plan. could someone help me?

**Comment by Matthew-Jennings** [comment]
Hi there @zism

A quick search of _"python mlc segment area"_ of Github yields many python-based implementations of this. They would be good places to start!

@remsky's [PredictingSRSQAFailues](https://github.com/remsky/PredictingSRSQAFailures) looks like a good example. Pay particular attention to [`calc_control_point_aperture_area()`](https://github.com/remsky/PredictingSRSQAFailures/blob/57fafda2ab24a9b3565d8f1a35946e6c9e0f2ba2/complexity_metric_utilities.py#L611) and [`calc_leaf_width_matrix()`](https://github.com/remsky/PredictingSRSQAFailures/blob/57fafda2ab24a9b3565d8f1a35946e6c9e0f2ba2/complexity_metric_utilities.py#L578)
