### ISSUE TITLE
Poetry install of numpy fails on Windows + Python 3.10.4

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1639]
Just a note that I was unable to successfully run `poetry install -E dev` on a Windows machine running Python 3.10.4 (official distro)

I think it might be a bug with Poetry itself - poetry was trying to build the numpy wheel locally rather than source a suitable pre-built one. I haven't investigated too deeply, but I believe that building numpy wheels locally requires a C compiler on your machine (along with non-trivial configuration, no doubt!).

Downgrading to Python 3.9.13 worked - I believe in this case, Poetry was able to find a suitable pre-built wheel to download and install

**Comment by SimonBiggs** [comment]
Yup, way back when I couldn't get the CI to run either:

https://github.com/pymedphys/pymedphys/pull/1559

Potentially we need to make the hard decision to drop a dependency if it isn't keep up with the Python versions and it is restricting the capacity to install.

**Comment by SimonBiggs** [comment]
The path forward here is to get to the bottom of which dependency is holding things back, determine how important it is. Then decide which of the following options is more appropriate:

* Provide upstream support to that dependency to help them be more compatible (did that with shapely and others way back when) and fix the issue
* Surgically remove dependent code from PyMedPhys that depends upon it, while hopefully remaining backwards compatible with our current public API
* Wait... and hope the problem sorts itself out...

Happy for you to jump in and try one of those options... ... ... I've been running with option three at the moment...

**Comment by Matthew-Jennings** [comment]
Well, for now I'm just happy running 3.9. Just figured it would be worth noting the issue.

Maybe I can add a note to the installation instructions? What do you think?

**Comment by SimonBiggs** [comment]
Yup, that's certainly worth it. Potentially mentioning that although
PyMedPhys works with 3.10, not all the dependencies do, and therefore, 3.7,
3.8, or 3.9 are the way to go for now.

**Comment by nlambriICH** [comment]
@SimonBiggs I would be happy to work on this, although it is completely new to me, so I'll most probably need some help.

**Comment by SimonBiggs** [comment]
That's all good, more than happy to help skill you up. Probably the best course of action is to try and install PyMedPhys locally using Python 3.10 with all of the dependencies and find out where it struggles. We'll have a better idea for the best course of action once that's targetted.

We have a bunch of tests that run for different operating systems and different python versions. The versions used are defined over at:

https://github.com/pymedphys/pymedphys/blob/ea9bfe6d6555a2a6d73da4fa6c0290dc0f644f98/.github/workflows/library.yml#L105-L114

The end goal is to be able to change one of those versions to 3.10 and have the tests still pass :)

**Comment by Matthew-Jennings** [comment]
I believe this now works after a `scipy` upgrade. See #1648

**Comment by nlambriICH** [comment]
I was going to work on this but I see @Matthew-Jennings already did the job, so I'll move to other issues :)

**Comment by Matthew-Jennings** [comment]
Hi @nlambriICH, yes, I'm sorry - I run into a speedbump trying to add another package for a different purpose. Dropping python 3.7 solved that (and was a standing item for maintenance from earlier) and this in turn ended up being closely tied to supporting python 3.10.

**Comment by SimonBiggs** [comment]
I believe this is now fixed :slightly_smiling_face:
