### ISSUE TITLE
Maintenance tasks (as of May 2022)

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1644]
* Dependencies need updating due to a security issue and the update tests which are currently failing need rectifying
* Python 3.10 installation
* Prune old and stale issues, make it so that the only issues that are open are ones that are actually helpful to have open on the issue tracker
* Merge in (or close) all open PRs

**Comment by nlambriICH** [comment]
Can we make this as a task-list and write who is working on which item? I think it would make the maintenance status more clear

**Comment by SimonBiggs** [comment]
> Can we make this as a task-list and write who is working on which item? I think it would make the maintenance status more clear

Yup, beautiful. I have just made a project, added you as to the PyMedPhys organisation, and then given all members of the PyMedPhys org write access:

https://github.com/orgs/pymedphys/projects/1

On there we can add in tasks, update their status, link them to issues if desired, and self assign ourselves if we're going to take it on.

**Comment by Matthew-Jennings** [comment]
Is dropping python 3.7 worth chucking in there too?

WHat would bve needed to do that, beyond verifying docs build on Windows and adjusting docs/badges etc.?

**Comment by nlambriICH** [comment]
@SimonBiggs I think it's neat, but I cannot find a way to easily access it from the pymedphys github page. Am I missing something?

**Comment by SimonBiggs** [comment]
> Is dropping python 3.7 worth chucking in there too?
> 
> What would be needed to do that, beyond verifying docs build on Windows and adjusting docs/badges etc.?

The main change is to change the following to `^3.8`:

https://github.com/pymedphys/pymedphys/blob/c9ff95f002e8497351b966cf130993474bc1f0bf/pyproject.toml#L33-L34

**Comment by SimonBiggs** [comment]
> @SimonBiggs I think it's neat, but I cannot find a way to easily access it from the pymedphys github main page. Am I missing something?

It finds itself under the org page:

https://github.com/pymedphys

![image](https://user-images.githubusercontent.com/6559099/170828263-5cfcb442-f03f-4897-a45d-b05ba48ac6af.png)

But I agree, it is obscure. I'll pin this issue, and make the link at the top of this issue to make it a bit easier to find.

**Comment by SimonBiggs** [comment]
Actually, I'll keep the record of this issue unadjusted, and pin a separate one:

https://github.com/pymedphys/pymedphys/issues/1646

(and close this one)

**Comment by SimonBiggs** [comment]
> Is dropping python 3.7 worth chucking in there too?

@Matthew-Jennings, go for it. Feel free to add items to the list, adjust them, update them, adjust the status, assign yourself etc.
