### ISSUE TITLE
Outputs from new tutorial not being rendered

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1662]
Normally the docs server should run the notebook and render the outputs, that hasn't happened for the new notebook though:

https://docs.pymedphys.com/lib/tutes/gamma/gamma_tutorial.html

**Comment by Matthew-Jennings** [comment]
To help diagnose this issue, are you in a position to outline in some detail the infrastructure behind the docs? I.e.,
- what tools?
- what features of those tools?
- known issues or decisions made with reasons

And we could work on including them in the docs for bus-factor purposes?

I ask because I'm really at a loss where to start here. Some of this I used to know but have forgotten.

**Comment by SimonBiggs** [comment]
> are you in a position @SimonBiggs to outline in some detail the infrastructure behind the docs?

Yup, happy to :slightly_smiling_face: 

> * what tools?

The top level tool is Jupyter Book:

https://jupyterbook.org/en/stable/intro.html

Under the hood it uses Sphinx. But, at the end of the day Jupyter Book's docs (linked above) should help us find the answers we seek.

> * what features of those tools?

Pretty much just its default setup

> * known issues or decisions made with reasons

As much as possible trying to use vanilla Jupyter Book so as to minimise bus-factor issues due to weird customisation :slightly_smiling_face:.

Let me know if you want more detail. At the end of the day calling `pymedphys dev docs` actually just calls the following under the hood now:

https://github.com/pymedphys/pymedphys/blob/b573874a05d8929b8f93a2370521835ec5775499/lib/pymedphys/_dev/docs.py#L31-L42

So really, you could just call `poetry run jupyter-book build lib/pymedphys/docs/` and it should get a very similar result. See https://jupyterbook.org/en/stable/start/build.html for more details.

**Comment by nlambriICH** [comment]
Just to flag this as a "bus-factor" and avoid the same issue in future tutorials, what was the root cause?

**Comment by Matthew-Jennings** [comment]
>The original "passing" Windows docs test actually complained of a bad kernelspec in the gamma tute JPN [here](https://github.com/pymedphys/pymedphys/runs/6835612399?check_suite_focus=true#step:44:88). This was not present before. Frustratingly, it didn't actually flag as a "fail" in the CLI and consequently went unnoticed.

>
>I've changed the relevant lines in the gamma tute notebook metadata [here](https://github.com/pymedphys/pymedphys/blob/b573874a05d8929b8f93a2370521835ec5775499/lib/pymedphys/docs/lib/tutes/gamma/gamma_tutorial.ipynb?short_path=8cdecde#L556-L560) to match [those in a working notebook](https://github.com/pymedphys/pymedphys/blob/b573874a05d8929b8f93a2370521835ec5775499/lib/pymedphys/docs/lib/howto/gamma/effect-of-noise.ipynb?short_path=76f3583#L366-L370)

Perhaps a couple of TODOs could be:
- introduce a doctest that checks for JPN output display? (not sure on feasbility - never written one)
   - or perhaps at least include in contributor docs on writing documentation?
- introduce some sort of test (or pre-commit hook?) that checks JPN metadata

**Comment by nlambriICH** [comment]
> introduce some sort of test (or pre-commit hook?) that checks JPN metadata

I think this should be the way to go (although I don't have any experience to implement it)

**Comment by SimonBiggs** [comment]
Actually we can pass the `-w` flag to the jupyter book build command. This makes all warnings become errors and will mean we will pick up this and other issues...

Only thing is, right now, we have quite a few warnings to deal with  before we can begin turning that flag on. Ideal scenario, the docs builds with no warnings, and then we set the `-w` flag, and then whenever we do something that brings in a warning we know about it right away...
