### ISSUE TITLE
JOSS paper review

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1667]
Current status: 
~~PRE-REVIEW~~
~~REVIEW~~
**PUBLISHED**

See [#4470](https://github.com/openjournals/joss-reviews/issues/4470)

**Comment by sjswerdloff** [comment]
The feedback was that they could not understand from the readme file what this software does. 
I looked at a JOSS paper at (pseudo) random, and it was for software that calculated a very particular approach to solving a Riemann Problem.  
If the readme needs to describe "when I use this software I solve this specific problem with it", then we might want to list what specific tasks people use it for.

Just glancing over the list of directories in the library subdirectory, and trying to describe it to someone who is technical, but not medical, it seems like 

PyMedPhys is used to convert data from a variety of proprietary formats in to either an internal/common representation, or in to a standard format, and then provides the means for performing a variety of common Quality Assurance tasks.   The QA task most commonly performed with the software is the calculation of the Gamma index, which 
 _quantifies the difference between measured and calculated dose distributions on a point-by-point basis in terms of both dose and distance to agreement (DTA) differences_

I'll get over my profound sense of personal loss </sarcasm>at not having pseudonymisation listed in the Summary.
In other words, I propose we put something in there that can be reviewed by someone who can use a search engine and can read Python, and not try to worry too much about how much we don't tell people about what it can do.

The last time I tried to describe the breadth of what I do (and what I can do) to a management type, I got the response "you are a freak of nature".   There is a warm place in my heart for that person, but it also makes the point that if you need to explain to someone what you do in twenty five words or less at a party, and they've already had a beverage, something simple like "Software for Radiation Therapy for Cancer Care" is good enough, and if they want to get more specific, they need to get another beverage and pull up a chair.  I think we need to try to get to a level of specificity without going so deep that they need to actually *understand* Medical Physics.

**Comment by Matthew-Jennings** [comment]
> The feedback was that they could not understand from the readme file what this software does. I looked at a JOSS paper at (pseudo) random, and it was for software that calculated a very particular approach to solving a Riemann Problem. If the readme needs to describe "when I use this software I solve this specific problem with it", then we might want to list what specific tasks people use it for.
> 
> Just glancing over the list of directories in the library subdirectory, and trying to describe it to someone who is technical, but not medical, it seems like
> 
> PyMedPhys is used to convert data from a variety of proprietary formats in to either an internal/common representation, or in to a standard format, and then provides the means for performing a variety of common Quality Assurance tasks. The QA task most commonly performed with the software is the calculation of the Gamma index, which _quantifies the difference between measured and calculated dose distributions on a point-by-point basis in terms of both dose and distance to agreement (DTA) differences_
> 
> I'll get over my profound sense of personal loss (sarcasm) at not having pseudonymisation listed in the Summary. In other words, I propose we put something in there that can be reviewed by someone who can use a search engine and can read Python, and not try to worry too much about how much we don't tell people about what it can do.
> 
> The last time I tried to describe the breadth of what I do (and what I can do) to a management type, I got the response "you are a freak of nature". There is a warm place in my heart for that person, but it also makes the point that if you need to explain to someone what you do in twenty five words or less at a party, and they've already had a beverage, something simple like "Software for Radiation Therapy for Cancer Care" is good enough, and if they want to get more specific, they need to get another beverage and pull up a chair. I think we need to try to get to a level of specificity without going so deep that they need to actually _understand_ Medical Physics.


You beat me to the punch! I agree, and I like your wording.

One example that is perhaps not _too_ different from PyMedPhys is [GEMMI: A library for structural biology](https://joss.theoj.org/papers/10.21105/joss.04200). In their paper (which is hardly any larger than our own submission), they do state:

> The library covers three main areas, which overlap and contain common elements...

and then give a two-or-three sentence description of each of those three areas.

There are other papers that flesh out their software a lot more, like [SpeechPy - A Library for Speech Processing and Recognition](https://joss.theoj.org/papers/10.21105/joss.00749), but this may not be necessary for us. Honestly, it just represents a doubling up of text that should otherwise exist in the docs, with _all_ of the disadvantages of it not being a live document.

Perhaps we could do something similar to Gemini for each of the modules listed in the library technical reference? Gamma does predominate, but it's not the other useful module in there and who knows how the other modules (or entirely new ones) will fare if/as they get built out.

**Comment by sjswerdloff** [comment]
I would prefer to abstract it a bit.  the library technical reference is oriented towards individual tasks.
I would prefer to abstract to these three kinds of tasks:

Data Conversion/extraction from the proprietary formats of a variety of Radiotherapy systems:
   Two treatment planning systems (I thought I saw Monaco conversion in there somewhere, and Pinnacle is clearly addressed)
   One Oncology Informatics System (MOSAIQ, but the actual work done is extraction of the meter set map)
   One Linear accelerator vendor family of systems (log/TRF files as well as iCOM listener)   

Manipulation of standard format Radiation Therapy data to address scenarios that are otherwise time consuming and awkward to do with the commercial clinical tools, and for which those commercial tools are not really intended.
  Anonymisation, extraction of dose information to CSV for plotting, manipulation of contour files to merge them or to adjust scaling of relative electron density, and switching treatment machine names in plans to migrate to a matching machine. 

Calculation of the Gamma Index
 
And maybe someone can put the above and what I mentioned before together

**Comment by Matthew-Jennings** [comment]
> I would prefer to abstract it a bit. the library technical reference is oriented towards individual tasks. I would prefer to abstract to these three kinds of tasks:
> 
> Data Conversion/extraction from the proprietary formats of a variety of Radiotherapy systems: Two treatment planning systems (I thought I saw Monaco conversion in there somewhere, and Pinnacle is clearly addressed) One Oncology Informatics System (MOSAIQ, but the actual work done is extraction of the meter set map) One Linear accelerator vendor family of systems (log/TRF files as well as iCOM listener)
> 
> Manipulation of standard format Radiation Therapy data to address scenarios that are otherwise time consuming and awkward to do with the commercial clinical tools, and for which those commercial tools are not really intended. Anonymisation, extraction of dose information to CSV for plotting, manipulation of contour files to merge them or to adjust scaling of relative electron density, and switching treatment machine names in plans to migrate to a matching machine.
> 
> Calculation of the Gamma Index

Fair enough. I think that all sounds great!

> 
> And maybe someone can put the above and what I mentioned before together

I _might_ have some time today.

**Comment by Matthew-Jennings** [comment]
******** Status updated to **REVIEW** ********

**Comment by Matthew-Jennings** [comment]
Hi all,

We're published!!!

https://joss.theoj.org/papers/10.21105/joss.04555

@SimonBiggs @sjswerdloff @pchlap @dg1an3 @rembishj @JacobMcAloney @kingrpaul @ayalalazaro @guanfada @nlambriICH @crcrewso @msobolewski

**Comment by guanfada** [comment]
Congratulations to everyone!

**Comment by SimonBiggs** [comment]
For those interested, JOSS flagged that they would appreciate more reviewers. See the following post for details:

https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1280033189

**Comment by sjswerdloff** [comment]
> For those interested, JOSS flagged that they would appreciate more reviewers. See the following comment for details:
> 
> [openjournals/joss-reviews#4555 (comment)](https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1280033189)

I signed up and donated (but requested that my name not show up on donation lists, I don't want to get hit up by every web scraper on the planet).

Congrats and thanks to all contributors!

**Comment by ayalalazaro** [comment]
Congratulations!!
