### ISSUE TITLE
request to be added as a contributor

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1670]
Hello, @pchlap @SimonBiggs 
Can you please add me to the active contributor list?
Thanks!

Fada

**Comment by SimonBiggs** [comment]
Hehe, just a small tweak @guanfada, it's a bit of a "right of passage" to fumble through the land of git and GitHub (and PyMedPhys overly complicated and in need of simplification propagate system).

So you'll be adding yourself :) and we'll be reviewing and approving the addition. But also, more than happy to help you through the process. (Also... @nlambriICH is also going to do the same and plans on documenting the tutorial for achieving it within the contributor section of the docs).

**Comment by pchlap** [comment]
> so @pchlap, might you be able to help @guanfada here?

Definitely happy to help here @guanfada. I see you previously already forked the pymedphys repo and put through a pull request with some changes? This will work in the same way:
1. Make sure you're on the `main` branch and make sure you're up-to-date with all the latest changes: `git pull`
2. Find the main [`README.rst`](https://github.com/pymedphys/pymedphys/blob/main/README.rst) file and find the section where the contributors are defined
3. This file is written in Rich Structured Text format, if you're not familiar with the syntax you should be able to copy the lines from one of the other contributors and replace with your details.
4. Optionally you can add a logo of your organisation. If you'd like to do this let me know and I can help you with that
5. Commit the changes to the `README.rst` file and create a pull request from your fork into the main pymedphys repo (like last time).

Let me know if you need any further clarification on any of this or if there are any other questions.

**Comment by guanfada** [comment]
@pchlap will do it tomorrow. Thanks a lot!

**Comment by Matthew-Jennings** [comment]
Addressed in #1698
