### ISSUE TITLE
Some gamma values being skipped/ignored

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1671]
My understanding is the len(valid_gamma) is the # of points with dose >= lower_percent_dose_cutoff * np.max(dose_reference).
It is the # of non-nan gamma points. 
So the gamma pass criteria won't impact the value of len(valid_gamma).
However, I recently found that for some DICOM files (not all of my DICOM files), changing from (2%/2mm) to (1%/1mm) can get a smaller # of valid gamma points. 
But if I use 1D gamma, I don't see a change in the # of valid gamma points. 
I need to do more investigations. 
I just want to confirm with you @SimonBiggs that this len(valid_gamma) is only determined by lower_percent_dose_cutoff * np.max(dose_reference), right? 
Thanks.

![Global gamma_histogram](https://user-images.githubusercontent.com/25382578/173726274-23bebe4c-4231-41c7-9cb2-1330cf99e4c6.png)
![Global gamma_histogram](https://user-images.githubusercontent.com/25382578/173726334-c6a5fca6-b184-4507-8f21-a632a208ba70.png)

**Comment by SimonBiggs** [comment]
Essentially anything that can cause the result to be NaN would result in it being removed from `valid_gamma`. If everything is going according to plan that should only be due to the `lower_percent_dose_cutoff`. If you have a case where that isn't true it would be very helpful to be able to replicate it as a bug within a test.

**Comment by guanfada** [comment]
let's see another case. No change in # of valid gamma points between 2%/2mm and 1%/1mm.
![Global gamma_histogram](https://user-images.githubusercontent.com/25382578/173726521-b1289ba2-5332-4d40-a7d0-296044ed92fb.png)
![Global gamma_histogram](https://user-images.githubusercontent.com/25382578/173726542-304c42c2-9328-4d44-8d47-f80b240cdcc6.png)

**Comment by SimonBiggs** [comment]
I think to help with the investigation if you select some slices where it is NaN in one but not the other and see if there is any pattern?

One thought might be some mishandling of points near the edge of the image.

**Comment by guanfada** [comment]
Yep, I did check the slices and found some obvious errors. For example, see below.
The 1%/1mm gamma map is not correct because the target region (high dose) does not show gamma at all. 
![dose maps and Global gamma results_sliceZ106](https://user-images.githubusercontent.com/25382578/173727406-cb5d3591-860a-4419-9572-11f0accb2597.png)
![dose maps and Global gamma results_sliceZ106](https://user-images.githubusercontent.com/25382578/173727457-0773a61c-cafb-4f2e-9eeb-bcff2cac9865.png)

**Comment by SimonBiggs** [comment]
> The 1%/1mm gamma map is not correct because the target region (high dose) does not show gamma at all.

That _is_ concerning. Out of interest is this right at the end (or very close to the end) either superiorly or inferiorly?

**Comment by SimonBiggs** [comment]
> Yep, I did check the slices and found something strange. For example, see below.
> The 1%/1mm gamma map is not correct because the target region (high dose) does not show gamma at a

Would you be able to print out what those values there are in fact? Are they `np.nan` or are they `np.inf`?

https://github.com/pymedphys/pymedphys/blob/6937133f456d63e38583c1521d9b79de3c3b45e2/lib/pymedphys/_gamma/implementation/shell.py#L271-L276

**Comment by SimonBiggs** [comment]
I think a good path forward to fixing this is to first write up the failing test with some dummy data. For example pass two quite small 3D made up dose distributions with one shifted / scaled a bit. And potentially just have the test be running gamma with both 1%/1mm and 2%/2mm and assert that they have the same `valid_gamma` counts (which then fails to produce the failing test initially).

**Comment by guanfada** [comment]
@SimonBiggs Good idea! I will work on it later this week.

**Comment by guanfada** [comment]
@SimonBiggs 
For the 1%/1 mm case, when I change the 'interp_fraction': 10,  # Should be 10 or more for more accurate results
from 10 to 5, the calculated # of valid gamma points is the same as (2%/2 mm with 'interp_fraction': 10.) and gamma value maps on different slices are reasonable. 
So I believe, in 1%/1mm, the super fine evaluation grid size of 0.1mm (1mm/10) can bring some issues, but NOT for all cases as described above.

**Comment by guanfada** [comment]
@SimonBiggs 
In pymedphys 0.38.0, in the shell.py, logging.info("**Computing** the gamma using global normalisation point")
But when I run my gamma analysis jobs, the output is still the old one "Calcing using global normalisation point for gamma"

I checked my version and am sure that I am using pymedphys 0.38.0

**Comment by guanfada** [comment]
@SimonBiggs 
This completely drives me mad.
(1)
I just did the 1%/1mm, with 'interp_fraction': 10 on my Windows laptop, the # of valid gamma is the same as 2%/2mm. My Python is 3.7.5, and pymedphys is 0.38.0.
Only when I used a Linux cluster to do calculations, the 1%/1mm, 'interp_fraction': 10 could give strange results (for some cases, not ALL) It has Python 3.7.0 and pymedphys0.38.0

(2)
I used pandas.DataFrame.to_csv to export the gamma_slice, but no way to know if it is nan or inf because they are all treated as the missing values.
When I use PyCharm, yes, I can see, all of these NON-Valid gamma points have "nan". No "inf" was found. But now the calculation results are reasonable on Windows. 

So, now, I am not sure if it is a bug of pymedphys because the issue only occurs on the Linux cluster I use. 
I need to do more investigations.

**Comment by SimonBiggs** [comment]
That is very intriguing :/. Something important to grab is what the scipy and numpy versions are on the cluster in question.

Once you have something to replicate it I can run it on my Linux machine here too...

**Comment by SimonBiggs** [comment]
Even if it only happens sometimes we really should have a test to replicate it, even if just to flag it should it happen on one of our test environments.

**Comment by guanfada** [comment]
I am going to submit a calculation job to Linux cluster now.
I will check the version of scipy and numpy soon.

**Comment by SimonBiggs** [comment]
It would also be worthwhile finding out what dtype is being used for the
dose and coordinates data storage. If it's using something weird like a 16
bit float (
https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.float16)
that might be why it throws a wobbly when you interpolate it...

It also might be something worth trying locally. Force the dose grid to be
saved as a float16 and see if that causes the issue...

**Comment by guanfada** [comment]
In the Linux cluster:
numpy 1.16.1
scipy 1.2.0

On my Windows laptop:
numpy 1.21.4
scipy 1.7.3

**Comment by guanfada** [comment]
I just tested the 1%/1mm, 'interp_fraction': 10 in the Linux cluster and the results are reasonable. 
It's strange. 
Last time's incorrect results are not repeatable.

**Comment by SimonBiggs** [comment]
> Last time's incorrect results are not repeatable.

That is very weird. If you can manage to repeat it that would be amazing to be able to try and protect against the issue...

**Comment by SimonBiggs** [comment]
Does every node on the cluster have the same scipy version?

**Comment by guanfada** [comment]
I just upgraded them to numpy-1.21.6 and scipy-1.7.3 on the Linux cluster.
I think the computation nodes all invoke the user version of scipy and numpy packages. 
So, I think now they are all using the latest version. (in the past, the system's old versions were used)
I just submitted jobs for running. Let's see.

**Comment by guanfada** [comment]
All of my most recent calculations in the Linux cluster for 1%/1mm have the same # of valid gamma points as in 2%/2mm.
So, we may close this issue because I can't prove it is a bug in PyMedPhys.

**Comment by SimonBiggs** [comment]
> All of my most recent calculations in the Linux cluster for 1%/1mm have the same # of valid gamma points as in 2%/2mm. So, we may close this issue because I can't prove it is a bug in PyMedPhys.

kk, thanks for letting us no @guanfada. I think it would be worth us keeping an eye on it. It would be quite the serious issue if it was true.
