### ISSUE TITLE
Gamma speed-up howto - random subset

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1686]
Hi @nlambriICH and @SimonBiggs,

I've just happened to notice that the example used to demonstrate the speed-up potential of using `random-subset` is not very compelling. I.e., for a 10% sample rate (which is arguably fairly aggressive), the howto only demonstrates a 20% reduction in gamma calculation time - hardly worth it.

I think we should use a 3D example. In my previous experience, use of the default gamma parameters to compare a full 3D planned dose distribution on an 8 GB RAM workstation required many minutes of calculation time. I'm almost certain that calculating for a full factor of 10 fewer points should result in a much better time improvement. 

In the existing howto, a 2D slice is used for deonstration. It's possible that interpolation doesn't even dominate the calculation time in this scenario, and the need for speeding up gamma is largely not there.

**Comment by SimonBiggs** [comment]
> required many minutes of calculation time

Were you using `max_gamma` when that happened?

**Comment by Matthew-Jennings** [comment]
> > required many minutes of calculation time
> 
> Were you using `max_gamma` when that happened?

We're talking about a long time ago, but my best recollection is that both `max_gamma` and `random_subset` _independently_ improved calculation times markedly, with `random_subset` proving the more effective (which I think would make sense for dosegrids that are expected to match relatively well).

**Comment by nlambriICH** [comment]
Yup, I used a 2D slice to avoid dealing with large computation times which increase really fast.

@Matthew-Jennings I'm kinda busy right now... Might you be interested to test it locally using the whole 3D dose (or a subset)?

**Comment by Matthew-Jennings** [comment]
> Yup, I used a 2D slice to avoid dealing with large computation times which increase really fast.
> 
> @Matthew-Jennings I'm kinda busy right now... Might you be interested to test it locally using the whole 3D dose (or a subset)?

Sorry @nlambriICH & @SimonBiggs, I'll be travelling and out of action, development-wise, for the next two weeks. Should still be able to review though.

I don't think this is particularly urgent or anything, just a proposed improvement upon an otherwise lovely howto.

**Comment by nlambriICH** [comment]
I did some testing using the 10 slices above and below the maximum dose mismatch of the 3D distribution (and shifting the evaluation dose as in the how-to).

The following are the computation times I obtained on my machine:

1. Using default gamma parameters: 9min 39s
2. Using `max_gamma=1.01`: 7min 11s
3. Using random_subset to sample 1/10th of the points: ~10min 15s (tried twice)

Do you have any idea why the random subset made the computation slightly slower?

**Comment by SimonBiggs** [comment]
Wow... That is interesting about the random subset... It also shows just how slow it can end up getting. Do you think people are often going to want to compare distributions with gamma pass rates that low?

Does your machine happen to have a GPU?

**Comment by nlambriICH** [comment]
> Do you think people are often going to want to compare distributions with gamma pass rates that low?

The pass rate in the how-to is Indeed really low... In the new tests I run it raised above 50%. I think it's still too low compared to real applications (I could try find a value in the shift of the dose reference for which the pass rate is near 90%).

> Does your machine happen to have a GPU?

It does have one but is not vert performing (I can't remember right now the model name)

**Comment by SimonBiggs** [comment]
Hi @SimonJSchmidt,

Most definitely. Especially given the one of the key computation bottlenecks in the gamma calculation is the tri-linear interpolation (which can be calculated with an array convolution, a GPU friendly approach).

If you'd be keen to give it a try and make a pull request, let us know! 🙂

**Comment by crcrewso** [comment]
I've looked into a lot of different GPU solutions for gamma comparisons, and I've found them lacking. There's a discussion about parallelizing linear interpolation from [StackExchange](https://stackoverflow.com/questions/41220617/python-3d-interpolation-speedup) that might allow for CPU interpolation. 

For GPU's the array either needs to be preloaded, or the calculation needs to be so CPU intensive that memory load and unload take a comparatively insignificant amount of time, while also being small enough to fit in 1/4 the GPU's memory. 

In C# (plugging my own code [DicomStrictCompare](https://github.com/crcrewso/DicomStrictCompare) ) it's been hard to find a solution. But the 512^3 voxel solution comparisons would complete in less time then the memory transactions each way. 

I'd also like to point out most GPU's have relatively few double precision floating point calc units.  If you find a library that can overcome all of these issues I would happily help every way I can.

**Comment by SimonBiggs** [comment]
Utilising `jax.jit` code that looks very similar to numpy can be compiled to run parallelised on the CPU or compiled to be sped up on the GPU:

https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html

If we're going for tool choice, `jax` would certainly be hands down my preference.

**Comment by nlambriICH** [comment]
Just to give you an update on this. I have experimented with jax trying to speed up the gamma, but... no good news unfortunately. I could run some tests only on CPU.

I tried going through the code and substitute numpy with jax.numpy where possible, but the computation time increased 😕 

I'm also struggling to add jax.jit because:

- most functions would require a refactoring as they accept parameters whose type is not supported by jax (e.g., _GammaInternalFixedOptions_, _RegularGridInterpolator_)
- arrays whose length is known only at runtime (e.g., when using `np.linspace`, `np.arange`) cannot be jitted

I didn't want to rewrite the code, and I think this is something that should be addressed in the future if necessary (or if someone better skilled than me wants to give it a crack 😃).

**Comment by SimonBiggs** [comment]
> * RegularGridInterpolator

Yeah, I suspect that's where the gold lies. JAX has a "scipy api":
https://jax.readthedocs.io/en/latest/jax.scipy.html

Potentially the best path forward would be to create a "JAXified" version of `RegularGridInterpolator` over at the JAX repo, with the help of the JAX maintainers. And then, I suspect, if we just utilise that within our repo, we will have quite a win.

**Comment by SimonBiggs** [comment]
@nlambriICH, maybe the use of the following library could be really helpful?

https://aesara.readthedocs.io/en/latest/introduction.html#introduction

**Comment by SimonBiggs** [comment]
So, with all my love for JAX... turns out they don't yet provide native pip install support for windows:

https://github.com/google/jax/issues/5795

...that's an absolute deal breaker for using JAX as a dependency of PyMedPhys...

**Comment by nlambriICH** [comment]
What about these links:

- [jax docs](https://jax.readthedocs.io/en/latest/developer.html#building-or-installing-jaxlib)
- [builder](https://github.com/cloudhan/jax-windows-builder) (created by a microsoft employee 😃)?

**Comment by SimonBiggs** [comment]
True, but one of the "requirements" of PyMedPhys in my mind is "it and its dependencies should just install with pip on Windows, MacOS and Linux". There shouldn't be any extra fuss to get it working. I would be more than happy for a package outside of PyMedPhys to utilise JAX, and then, once JAX works with Windows via pip then pull that package in...

**Comment by sjswerdloff** [comment]
> True, but one of the "requirements" of PyMedPhys in my mind is "it and its dependencies should just install with pip on Windows, MacOS and Linux". There shouldn't be any extra fuss to get it working. I would be more than happy for a package outside of PyMedPhys to utilise JAX, and then, once JAX works with Windows via pip then pull that package in...

This seems like it could fit in with "experimental".  
But it would certainly be easier if a separate package were to *use* PyMedPhys and substitute in a "JAXified" version of RegularGridInterpolator, and then we just wait until JAX gets packaged for PyPi

**Comment by SimonBiggs** [comment]
> This seems like it could fit in with "experimental".

Fair point. It would mean that the dependencies wouldn't be so simple to handle the experimental install. But you're right, experimental is probably a good way to go.

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, @sjswerdloff Perhaps #1761 goes far enough here? Shall we close this or keep it open as a reminder for further refinement?

**Comment by sjswerdloff** [comment]
> @SimonBiggs, @sjswerdloff, @ crcrewso, @SimonJSchmidt:
> 
> Perhaps #1761 goes far enough here? Shall we close this or keep it open as a reminder for further refinement?
> 
> It might be useful to have someone else test the implementation in #1761

I'd say this can be closed.
You have (from what I read) a better than 2x performance improvement in #1761 , so if someone wants to go further, they can open a new Issue.
Otherwise performance improvements can go on forever.
Additional, separate attempts are fine.  But keeping one issue open indefinitely when something very significant has been done seems counterproductive.  Also known as "claim victory and move on".
