### ISSUE TITLE
Pinnacle warning on the CLI page also

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1696]
Make the pinnacle warning display within the CLI part of the docs also:

We need to have this warning:
https://docs.pymedphys.com/en/latest/users/ref/lib/experimental/pinnacle.html

Also display at:
https://docs.pymedphys.com/en/latest/users/ref/cli/pinnacle.html

@crcrewso, might you be interested in taking this one? Also, @crcrewso, we need to get you onto [the team list on the front page](https://github.com/pymedphys/pymedphys#active-contributors) :slightly_smiling_face: Feel free to put a pull request to make that happen too :slightly_smiling_face:

**Comment by crcrewso** [comment]
That looks like something I could do in the very near future. Please assign it to me.

**Comment by SimonBiggs** [comment]
Beautiful, thanks @crcrewso :).
