### ISSUE TITLE
Split PyMedPhys across multiple packages

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#171]
When the following pull request lands:

https://github.com/iodide-project/pyodide/pull/147

Python libraries that are pure python can be pulled by pyodide and used within the browser's virtual machine. This includes tools such as pydicom. Therefore tools such as DICOM anonymise within PyMedPhys could theoretically be run within a browser, completely client side. No server involved in the computation. This would be a brilliant way to expose applications. No installation required, directly linkable from the docs (or embedded as interactive python within the docs...).

However a subset of our current dependencies are not pure python.
So in it's current form, because of PyMedPhys's structure although some modules would be just fine being used by pyodide, because of PyMedPhys's current all or nothing architecture, the weight of those non-pure-python dependencies is holding back all the modules.

Pyodide isn't the only use case that could benefit from a siloed packages with a limited dependency set. I imagine there are other cases where the dependencies of PyMedPhys full aren't appropriate, but a user just wants one module only.

I propose introducing the third levelling depth now. And introducing as fully fledged python packages. Here is how it might work.

Modules that are closely related are spun off into their own python package. Each python package name is prepended with pymedphys. So we might, for example, have pymedphys-dicom, pymedphys-mosaiq, pymedphys-elektalogfiles.

Installing pymedphys itself will simply install all of the packages and provide a seamless top level API to all of the individual packages.

All if these packages shall still reside within the PyMedPhys repo, just within their own directory tree. Each with their own test suite and semantic versioning.

Back to the original point, this then solves the pyodide case, as those modules with only pure python dependencies are able to be directly used by pyodide. Those without pure python dependencies cannot.

How do we decide where modules should go? I think the main driver should be minimisation of external dependencies. If there is one small piece that is requiring a whole new external dependency that is then a candidate for creating another package. That way if a user doesn't want that external dependency, then they don't install that piece.

For the standard user, they will just install `pymedphys` only, it will grab all of the packages (because all of the packages will be listed as dependencies of `pymedphys`) our top level API will be built into that top level package.

Every package will be separately versioned based on its API. The top level `pymedphys` package won't need a major version bump unless its top level API changes (which should be rarely). Each release of pymedphys top should come with lower bounds on each of the sub packages within its setup.py, that way upgrading pymedphys itself will be sufficient to force upgrade all of its underlings. We should also have within pymedphys setup.py a default upper limit of less than the next major version, that way we symbolise that for any pymedphys download it can't go and download a breaking change. While packages are at the 0.x.x stage they should be limited to be less than the next minor version.

This also means that we can progressively release certain packages as 1.0.0. Once a package is tested, once its API has been well defined and limited to a sustainable subset of its total logic, that package can be released as 1.0.0.

This seems like a way to introduce our final third depth of layering, and it does so in such a way that meets an important need of dependency limitation.

There is quite a degree of infrastructure required to achieve this. Most importantly is automation of package release infrastructure.

**Comment by SimonBiggs** [comment]
Keen for your thoughts @Centrus007

**Comment by SimonBiggs** [comment]
Firstly, here are our external dependencies by module level. * means not yet dependent on, but expect it will depend on that in the future.  | is the internal module dependency. - means its a dependency but I suspect it shouldn't be.

It's this sort of tree I would like to have auto generated and displayed within the documentation...

```
        # Module Level 4
        - logfile -- numpy, matplotlib, pandas, -attrs, |deliverydata, |utilities, |msq, |mudensity, |trf, |filehash

        # Module Level 3
        - gamma -- numpy, scipy, -psutil, -|dicom (the DICOM interface should be a different package, therefore pure gamma can be a level 1 module...)
        - plancompare -- numpy, matplotlib, |msq, |mudensity
        - trf -- numpy, pandas, |msq
        - xlwings -- numpy, scipy, *matplotlib, pydicom, xlwings, |utilities, |dicom, |mephysto

        # Module Level 2
        - dicom -- numpy, pydicom, scipy, matplotlib, |utilities
        - film -- numpy, |geometry
        - msq -- keyring, pymssql, numpy, pandas, |deliverydata, -attrs,
        - mudensity -- numpy, matplotlib, |deliverydata, |plt, |coll, -pydicom, -|xarray
        - profiles -- numpy, scipy, matplotlib, |xarray

        # Module Level 1
        - coll -- nil
        - coordinates -- numpy
        - deliverydata -- numpy
        - electronfactors -- numpy, scipy, shapely, matplotlib
        - filehash -- hashlib
        - geometry -- numpy, matplotlib
        - plt -- numpy *matplotlib
        - utilities -- nil
        - xarray -- numpy, xarray

        # Module Level 0
        - libutils -- nil
```



-- Need to add mephysto package to the levelling file.

**Comment by SimonBiggs** [comment]
So here are some names, we can iterate from here.

* pymedphys-utilities (everything with no external dependencies)
  * libutils
  * utilities
  * coll
* pymedphys-base (a set of objects that are used throughout pymedphys)
  * coordinates
  * deliverydata
* pymedphys-hashing
  * filehash
* pymedphys-analysis  (numpy, scipy, pandas, and matplotlib only)
  * plt
  * geometry
  * film
  * mudensity
  * gamma
  * profiles
* pymedphys-electronfactors
  * electronfactors
* pymedphys-filereaders
  * mephysto
* pymedphys-mosaiq
  * mosaiq
  * plancompare
* pymedphys-excel
  * xlwings
* pymedphys-logfiles
  * elekta
  * orchestrate



And here are planned external dependencies:

### Module Level 4
- logfile -- numpy, matplotlib, pandas, keyring, pymssql, hashlib

### Module Level 3
- plancompare -- numpy, matplotlib, keyring, pymssql
- trf -- numpy, pandas, keyring, pymssql
- xlwings -- numpy, scipy, matplotlib, pydicom, xlwings, pandas

### Module Level 2
- dicom -- numpy, pydicom, scipy, matplotlib
- film -- numpy, matplotlib
- msq -- keyring, pymssql, numpy, pandas
- mudensity -- numpy, matplotlib
- profiles -- numpy, scipy, matplotlib

### Module Level 1
- coll -- nil
- coordinates -- numpy
- deliverydata -- numpy
- electronfactors -- numpy, scipy, shapely, matplotlib
- filehash -- hashlib
- gamma -- numpy, scipy
- geometry -- numpy, matplotlib
- mephysto -- numpy, pandas
- plt -- numpy *matplotlib
- utilities -- nil

### Module Level 0
- libutils -- nil

**Comment by SimonBiggs** [comment]
We need to read the following. There is seems that for this particular use case underscores are not so bad...

https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by SimonBiggs** [comment]
Of interest:

https://blueprints.launchpad.net/oslo-incubator/+spec/drop-namespace-packages

And

https://specs.openstack.org/openstack/oslo-specs/specs/kilo/drop-namespace-packages.html

**Comment by SimonBiggs** [comment]
Then again, that says "Python 3 has better native namespace package support, so we could review the decision when we move to Python 3."

... we only are using namespacing in Python 3, so native namespacing might not have the issues described above...

**Comment by SimonBiggs** [comment]
Hmmm... and this:

https://stackoverflow.com/a/27586272

**Comment by SimonBiggs** [comment]
So, further thought and working through the issues. I don't want to use Python's native namespaces. It closes out some options to us in the future. The recommended way to achieve namespacing without using Python's namespacing features is to use underscores:

> However, namespace packages come with several caveats and are not appropriate in all cases. A simple alternative is to use a prefix on all of your distributions such as import mynamespace_subpackage_a (you could even use import mynamespace_subpackage_a as subpackage_a to keep the import object short).

https://packaging.python.org/guides/packaging-namespace-packages/

... so underscores it is ...

**Comment by SimonBiggs** [comment]
Timeline for this is I'll begin the rework in July (after ICCR)

**Comment by SimonBiggs** [comment]
@Centrus007 another benefit for this method is, should we wish to provide parts of the library under a different license only, as long as that part of the library has no AGPL or GPL dependencies, then it can be marked as Apache-2.0 for example.

A dependency tree diagram could also have on each package its license so it is quite clear if you just pick a certain package, and not pymedphys total, you may use it under different licensing conditions.

We could certainly discuss having `pymedphys_dicom` be released completely under an Apache-2.0 license if you wish. Up to you though.

**Comment by Centrus007** [comment]
> another benefit for this method is, should we wish to provide parts of the library under a different license only, as long as that part of the library has no AGPL or GPL dependencies, then it can be marked as Apache-2.0. This is then a very clear way that people can pull in only parts of pymedphys and be able to use that library as a dependency for a closed source derivative.

Excellent observation!

> We could certainly discuss having pymedphys_dicom be released completely under an Apache-2.0 license if you wish. Up to you though.

I think I'm happy with AGPLv3. But not against changing it if it's now your preference? :)

**Comment by SimonBiggs** [comment]
I'd rather it be AGPL to be honest, it was more of an option if you were
keen for it.

**Comment by SimonBiggs** [comment]
I've been thinking further, this shouldn't be too hard to make this change... Potentially I just make the change in the next couple of days, then at least we can see how it works in practice. We can always change it back if we don't like it...

**Comment by SimonBiggs** [comment]
At the park at the moment, maybe tonight I'll dive in and craft a pull request. We can iterate on the package names and divisions within that pull request. Once we're happy, we can merge it in and I'll attempt a release under the new infrastructure.

**Comment by SimonBiggs** [comment]
Will continue working on this over at https://github.com/pymedphys/pymedphys/pull/181
