### ISSUE TITLE
Consider moving Statement of Need out of README.

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1716]
> Can we have this elsewhere within the documentation, and simply link to it within the readme?

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/pull/1701#discussion_r937388583_

**Comment by Matthew-Jennings** [comment]
I can see that @SimonBiggs has removed this from the README, but it _does_ still need to be in the documentation _somewhere_, and probably referenced from the README.

@nlambriICH & @guanfada, how is this going?

**Comment by guanfada** [comment]
@Matthew-Jennings Do you want to put "statement of need" on a separate page, and then add a link in the paragraph of "What is PyMedPhys?"

**Comment by Matthew-Jennings** [comment]
@guanfada, yep, I think that sounds reasonable :)

**Comment by guanfada** [comment]
@Matthew-Jennings @SimonBiggs 
How can I synchronize with the main branch, so that I can work on editing Readme.rst? Thanks.
My readme.rst still has "statement of need" paragraph. 

![image](https://user-images.githubusercontent.com/25382578/184465947-b1552334-50a6-4c81-a619-de83a3d7e606.png)

**Comment by Matthew-Jennings** [comment]
On your local workstation, open a terminal, navigate (`cd`) to the `pymedphys` directory and run:

``` bash
git checkout main
git pull
git checkout guanfada-patch-1 // or whichever branch you're using
git merge main
```

You may or may not need to resolve merge conflicts. Try the above first and let me know if you have trouble. :)

**Comment by guanfada** [comment]
@Matthew-Jennings I have to use "git stash" before "git checkout main"

**Comment by Matthew-Jennings** [comment]
Hi @guanfada

Honestly, the simplest approach might be to start again with a new branch. You might need be able to save some time applying your stashed changes to the new branch, but I doubt even that is worth it.

If you want to go the "merge conflict resolution" route, I'd suggest one of the many, many (mostly free) git tutorials available online. A decent understanding of Git, including resolving merge conflicts, is really a core requirement for contributing to Github projects.

**Comment by SimonBiggs** [comment]
Hi @guanfada,

I'm happy to jump in and help here. @Matthew-Jennings' advice above won't work in this specific case due to your  `guanfada/pymedphys` fork's main branch diverging. I'd recommend doing the following:

```bash
git stash
git checkout main
git remote add upstream https://github.com/pymedphys/pymedphys.git
git fetch upstream
git reset --hard upstream/main
git push origin main --force
```

As a heads up this is a bit "nuclear" in the sense that it deletes all changes in your locally forked repo. To make things a bit easier on yourself in the future make sure to make your fork's main branch be kept a bit sacred. Never make changes directly in main, instead do the following:

```bash
git checkout main  # change to your local main branch
git pull upstream main  # make your local main branch up to date with upstream
git push  # make your online fork up to date with upstream
git checkout -b your-new-branch-name  # Now, make any changes, only within a branch (never within main itself)
```

**Comment by guanfada** [comment]
@SimonBiggs @Matthew-Jennings I will be working on it later. Cheers guys.

**Comment by SimonBiggs** [comment]
I take it back, it appears that your `main` branch hasn't diverged:

![image](https://user-images.githubusercontent.com/6559099/185251192-b5b0bf29-9107-4f28-b765-cefd55c64cf5.png)

So, @Matthew-Jennings' advice will work mostly as is. Doing the following will work well:

```
git stash
git checkout main
git remote add upstream https://github.com/pymedphys/pymedphys.git
git pull upstream main
git push
git checkout -b your-new-branch-name
```

**Comment by SimonBiggs** [comment]
![image](https://user-images.githubusercontent.com/6559099/185251523-996bcd90-1236-4f93-b212-42944fd61d60.png)
