### ISSUE TITLE
Document "Automated Tests"

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1717]
> ... @SimonBiggs I see that most of the contributions in lib\pymedphys\tests came from you and other past contributors... I can try having a look at the tests, but I think it will require time and guidance.

_Originally posted by @nlambriICH in https://github.com/pymedphys/pymedphys/issues/1701#issuecomment-1195115931_

Referring to the review checklist:

>  Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1187692538

**Comment by SimonBiggs** [comment]
Essentially, just need a document that says, to run the tests, run `poetry run pymedphys dev tests`

**Comment by SimonBiggs** [comment]
We really just need to add something like the following to the bottom of our readme:

https://github.com/ReactiveX/RxPY#development

**Comment by crcrewso** [comment]
I think it's also time to include a requirements-dev even if it just references requirements.txt, poetry, and pandoc.

**Comment by nlambriICH** [comment]
Hi guys, I took some days off, but I wanted to contribute to this issue as it was opened due to my comment.

I have added a section in the readme, as in the link posted by @SimonBiggs.

Let me know what you think in the PR I've opened. 😃
