### ISSUE TITLE
Command line anonymise fails

### ISSUE THREAD

**Issue by neurolabusc** [pymedphys/pymedphys#1731]
The function anonymise_with_pseudo_cli() only creates the variable `identifying_keywords_for_pseudo` is only assigned if the user runs with the [pseudo](https://docs.pymedphys.com/en/latest/users/ref/cli/pseudonymisation.html) argument. 

Calling with pseudo succeeds:

```
pymedphys experimental dicom anonymise -p -o ~/out --pseudo ~/in
2022-09-09 12:07:04 WARNING  Keyword PatientSex has Value Representation CS and may require special processing to avoid breaking DICOM conformance or interoperability
/Users/cr/miniforge3/lib/python3.9/site-packages/pydicom/valuerep.py:290: UserWarning: The PN component length (129) exceeds the maximum allowed length of 64.
  warnings.warn(msg)
/Users/cr/in/in.dcm --> /Users/cr/out/MR.1.2.826.0.1.3680043.10.188.3003408011454037282787330082552200494_Anonymised.dcm
```

Calling without pseudo crashes:

```
$pymedphys experimental dicom anonymise -p -o ~/out ~/in         
Traceback (most recent call last):
  File "/Users/cr/miniforge3/bin/pymedphys", line 8, in <module>
    sys.exit(main())
  File "/Users/cr/miniforge3/lib/python3.9/site-packages/pymedphys/cli/__init__.py", line 148, in pymedphys_cli
    args.func(args)
  File "/Users/cr/miniforge3/lib/python3.9/site-packages/pymedphys/_experimental/pseudonymisation/__init__.py", line 116, in anonymise_with_pseudo_cli
    identifying_keywords=identifying_keywords_for_pseudo,
UnboundLocalError: local variable 'identifying_keywords_for_pseudo' referenced before assignment
```

**Comment by SimonBiggs** [comment]
Hi @neurolabusc,

What if you don't use the experimental API?

```
pymedphys dicom anonymise -p -o ~/out ~/in    
```

**Comment by neurolabusc** [comment]
@SimonBiggs that does seem to work. Can you [update the documentation](https://docs.pymedphys.com/en/latest/users/ref/cli/pseudonymisation.html) if this is the proper usage. That would close the issue.

**Comment by SimonBiggs** [comment]
@neurolabusc, do you think a comment like the following would have helped you?

https://github.com/pymedphys/pymedphys/pull/1733/files

Cheers,
Simon

**Comment by neurolabusc** [comment]
I would not have seen this, as a web search led me to the [documentation](https://docs.pymedphys.com/en/latest/users/ref/cli/pseudonymisation.html). I suggest updating the documentation to provide guidance on usage.

**Comment by SimonBiggs** [comment]
Hi @neurolabusc,

That is actually what is rendered as the documentation on that page in question.

**Comment by neurolabusc** [comment]
The documentation [says](https://docs.pymedphys.com/en/latest/users/ref/cli/pseudonymisation.html) 

```
usage: pymedphys experimental dicom anonymise
```

It suggests that the argument `experimental` is required not optional, and does not warn the user that the argument `experimental` only works if the optional argument `pseudo` is included.

**Comment by SimonBiggs** [comment]
May you please submit a PR that addresses your concern?

**Comment by neurolabusc** [comment]
Sorry, I am not familiar with the structure of this project 's documentation structure and philosophy. The rationale for the `experimental` clause in both the code and in the documentation path is unclear to me. It is likely that any PR I created would have unintended consequences. I encountered this issue trying to help @mcraig-ibme  with their [corrupted anonymized DICOM](https://github.com/rordenlab/dcm2niix/issues/633), so maybe he can help.

**Comment by sjswerdloff** [comment]
I will look at addressing behaviour in response to the combination of experimental with anonymise and without --pseudo (I will create a Pull Request).  I don't think I can get to this before the weekend.

**Comment by SimonBiggs** [comment]
Thanks @sjswerdloff :slightly_smiling_face:

**Comment by sjswerdloff** [comment]
I think the history of this (bear with me) is that anonymise was moved out of experimental, and the default behaviour within experimental was switched to psuedonymise (that's all that was available because anonymise wasn't in experimental anymore).
So the use of --pseudo is either redundant (pseudonymisation is going to get called from experimental) and I alter the setting of the variable in question so that it isn't dependant on the --pseudo argument (it just happens), or I print a message to screen saying something like "you called for experimental anonymisation, but you didn't specify --pseudo, so nothing is going to happen" (rather than crashing).  The latter seems a bit LBYL, but the former might leave someone thinking they were going to get anonymisation and then they actually get pseudonymisation.
Any preferences?

**Comment by SimonBiggs** [comment]
Another option, psudonumisation gets moved out of experimental?

**Comment by SimonBiggs** [comment]
@neurolabusc, are you in a position to install pymedphys from source and verify that @sjswerdloff's fix has addressed your issue?

**Comment by neurolabusc** [comment]
Sorry, unable to test in a timely manner. Feel free to close the issue if the updated code will anonymize DICOMs using the default settings of the documents. 

Feel free to use the DICOM images from [dcm_qa](https://github.com/neurolabusc/dcm_qa). These include the Siemens proprietary CSA header. Using pymedphys I was unable to replicate the [CSA data corruption](https://github.com/rordenlab/dcm2niix/issues/633) seen with data provided by @mcraig-ibme. His sample did report `DCMPseudonymiser` for tag 0002,0016, but perhaps it was an earlier version, or the corruption was caused by some other tool.
