### ISSUE TITLE
Final steps before paper acceptance

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1735]
From https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1247632276:

> @Matthew-Jennings, after fixing the above issue, could you:
> 
> * [ ]  Make a tagged release of your software, and list the version tag of the archived version here.
> * [ ]  Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
> * [ ]  Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
> * [ ]  Please list the DOI of the archived version here.
> 
> I can then move forward with accepting the submission.

@SimonBiggs (and anyone else interested), I might need your help with this - haven't made a release in a while!

**Comment by SimonBiggs** [comment]
Thanks @Matthew-Jennings for continuing to spearhead the paper submission 🙂 

I had my ear drum burst today... And I suspect I'll continue to be out of action for the next few days.

@pchlap helped me with the most recent one, he might be in a position to help? Also, there was a recent poetry update to version 1.2.0. I think it might be worth updating to 1.2.0 locally, running a `poetry update` with the new version and updating the version number within the GitHub CI before making the release.

The biggest issue before the release will be getting to the bottom of the updates CI failure. That will need to be done first.

**Comment by SimonBiggs** [comment]
Also, seeing everyone solve these things gives me hope that the PyMedPhys bus factor is growing 🙂. So, thank you everyone 🙂.

**Comment by pchlap** [comment]
Hi @SimonBiggs & @Matthew-Jennings,

Also agree, thanks @Matthew-Jennings and all for moving the paper submission forward!

I'm definitely happy to work on preparing the pymedphys release. I'll also update poetry first as @SimonBiggs suggests.

@SimonBiggs I don't suppose we had prepared any docs on the release process last time did we? I don't think we did so I'll go back and check what we did to start preparing the next release. I may need you (or someone else) to help remind me of a step or two along the way. I'll try to document as I go as well. :)

P.S. @SimonBiggs burst eardrum does not sound fun :( Hope you feel better soon!

**Comment by Matthew-Jennings** [comment]
Thanks, @pchlap, that would be great!

If you do feel like documenting along the way, I think a useful place might be a new docs page (e.g. "Making a release") under _Contributors Guide / Repository Information_. Even a very simply formatted dot point list would be quite helpful, I think.

**Comment by Matthew-Jennings** [comment]
> I think it might be worth updating to 1.2.0 locally, running a poetry update with the new version and updating the version number within the GitHub CI before making the release.

@SimonBiggs, given the issues faced in #1739, is there an alternative "patch" release pathway that we can take to avoid further delay in paper acceptance?

**Comment by pchlap** [comment]
> As long as poetry upgrade has been run without issue then we can leave poetry at v1.1.

I'd just add that I think the main problem I've been facing there is the upgrades of streamlit and pandas which are causing problems with pylint. I'd expect these to happen even without the upgrade to poetry.

At this stage the only easy solution to that is to upper pin them which isn't ideal. There do seem to be breaking changes for streamlit (pandas should be fine to just add in pylint disables). But I'm not very familiar with streamlit so I might be way off on this.

**Comment by SimonBiggs** [comment]
> At this stage the only easy solution to that is to upper pin them which isn't ideal.

Given streamlit is a part of our "application" and less a "library package"... I'd be okay for more leniency on being able to upper pin streamlit. If that gives you an easy fix, happy for you to run with that option for this release.

**Comment by nlambriICH** [comment]
Hi all and thanks for your efforts!

I just wanted to ask do we plan to add the authors' ORCID before final revision?

**Comment by Matthew-Jennings** [comment]
> Hi all and thanks for your efforts!
> 
> I just wanted to ask do we plan to add the authors' ORCID before final revision?

Yes, good point.

@SimonBiggs, @sjswerdloff, @pchlap, @dg1an3, @rembishj, @JacobMcAloney, @kingrpaul, @ayalalazaro, @guanfada, @nlambriICH, @crcrewso, @msobolewski: if any of you would like to add your ORCID to the JOSS article, could you please provide it here asap?

**Comment by pchlap** [comment]
> if any of you would like to add your ORCID to the JOSS article, could you please provide it here asap?

0000-0002-6517-8745

**Comment by nlambriICH** [comment]
> if any of you would like to add your ORCID to the JOSS article, could you please provide it here asap?

0000-0001-8706-6480

**Comment by sjswerdloff** [comment]
0000-0003-0754-4679

**Comment by SimonBiggs** [comment]
0000-0003-2058-7868

**Comment by ayalalazaro** [comment]
0000-0001-6925-6176

Thank you!

------- Original Message -------

**Comment by guanfada** [comment]
@Matthew-Jennings 
Mine is 
0000-0001-8477-7391

**Comment by dg1an3** [comment]
Mine is 0000-0002-4148-1213

**Comment by SimonBiggs** [comment]
Here's the Zenodo DOI:
https://doi.org/10.5281/zenodo.7126882

However, the paper in that release won't have these ORCIDs. If we want that, we'll need to release a v0.39.1 of PyMedPhys and have it make a new Zenodo release.

**Comment by JacobMcAloney** [comment]
0000-0001-8060-6907

**Comment by kingrpaul** [comment]
I have one now and it is 0000-0001-6748-4538
