### ISSUE TITLE
Presentation on PyMedPhys for QLD Scripting Symposium (Australia) - 7th October

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1740]
Hi all,

The Queensland Branch of the ACPSEM is hosting a scripting-themed symposium on Friday 7th October 2022. I've been invited to talk about PyMedPhys at the symposium. The talk has a 15 minute timeslot allocated, inclusive of questions. I believe that virtual attendance is possible, though I'm not sure on the details yet. Here is the registration [link](https://www.acpsem.org.au/ccms.r?pageid=6017&tenid=ACPSEM&NavCMD=Nextpage|2&K1=&F1=&F2=&F3=&F4=&F5=&F6=Search&F7=&F8=&F9=Search&F10=&M1=&Y1=&W1=&SearchLast=0&SearchCmd=&ROXY=0x000000001f40c013)

I just wanted to:

1. Let everyone know about the event in case they wanted to attend, and
2. Ask you all what you think it would be nice to focus on in the talk. E.g.
   - Current features/tools
   - Current and past contributors
   - Forthcoming exciting features (the app?)
   - Stats on PyMedPhys ysage
   - Benefits of contributing to PyMedPhys
      - Quality of code
      - Educational value
3. Ask if anyone has a local implementation of PyMedPhys upon which they've built additional functionality/features/aesthetics that they'd be interested to have showcased in a slide or two?

Thanks all!

@SimonBiggs @sjswerdloff @pchlap @ayalalazaro @cedricbelanger @crcrewso @dg1an3 @guanfada @JacobMcAloney @jasqs @kingrpaul @manorina @matthewdeancooper @mchamberland @nlambriICH @peterg1t @rembishj

**Comment by SimonBiggs** [comment]
> Ask you all what you think it would be nice to focus on in the talk.

My main comment is it would be great if it was interactive and people actually use the library during the workshop. For example, spin up a Google Colab, pip install, and come away having achieved something.

**Comment by guanfada** [comment]
@SimonBiggs 
Do you want me to give a demo then? 
I can (1) use Jupyter to run our online example, and (2) use PyCharm to run my actual case with two DICOM files. This script is slightly different from the online example. I added more output files.

**Comment by SimonBiggs** [comment]
@guanfada, I suspect it would be simpler presented in-person, but I'll leave the decision to @Matthew-Jennings given he's running the time-slot.

**Comment by guanfada** [comment]
@SimonBiggs Got it.
Maybe time is an issue for me. We have 14 hours difference.

**Comment by SimonBiggs** [comment]
Also, I'm not sure the gamma example is the best choice... I just wanted to give an example of my preference for some interactivity. Really, I don't mind what is chosen, as long as there is an element of interactivity.

**Comment by Matthew-Jennings** [comment]
> > Ask you all what you think it would be nice to focus on in the talk.
> 
> My main comment is it would be great if it was interactive and people actually use the library during the workshop. For example, spin up a Google Colab, pip install, and come away having achieved something.
> 
> Generally a great approach to encourage interactivity, is provide a small example, then ask them to solve a problem that slightly expands on it.
> 
> A bit constricted in 15 mins, but still possible, for example there could be 5 mins for showing how to do something, then a 10 mins example for applying this to a slightly different scenario.
> 
> An example could be, loading up two DICOM files and calculating gamma between them and plotting the dose diff and gamma and histogram for the worst gamma slice. Then the exercise could be to run it again on a different set of two DICOM files. (Very small change needed for the question vs the original example, but in the 10 mins you can run around and give people help).
> 
> Without having an example, people can listen to the talk and think they can go away and do it. But actually opening up the code, being forced to make a change and achieve something to see if it works, really tests if people can walk away and use the tool.

I agree with all of this and I really did want to achieve something like this, but unfortunately it's a "symposium", not a "workshop". In-person attendees will not have access to computers or the internet. Moreover, 15 min is unlikely to achieve something particularly useful.

Rather than force a workshop-style this time around, I'm hoping to organise a true multi-day workshop next year - something like the AI workshop back in... 2018?

Unfortunately, for now, I think it needs to just be a "show and tell".

**Comment by Matthew-Jennings** [comment]
> @Matthew-Jennings @SimonBiggs Do you want me to give a demo then? I can (1) use Jupyter to run our online example, and (2) use PyCharm to run my actual case with two DICOM files. This script is slightly different from the online example. I added more output files.

Thank you for the offer, @gyanfada! I think I'll stick to simply presenting myself. I'll have additional things to present and I think it'll be too difficult to co-ordinate multiple presenters, especially one remote, in a single short session.

I was thinking more along the lines of presenting a specific department's implementation _for_ them as an example of what's can be achieved by using PyMedPhys as a library, with appropriate acknowledgements of the persons and department of course!

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, @lipteck might be keen for his use case to be presented. He had a poster at the recent world congress:

https://www.linkedin.com/feed/update/urn:li:activity:6942750559909089282?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A6942750559909089282%29

**Comment by guanfada** [comment]
> > @Matthew-Jennings @SimonBiggs Do you want me to give a demo then? I can (1) use Jupyter to run our online example, and (2) use PyCharm to run my actual case with two DICOM files. This script is slightly different from the online example. I added more output files.
> 
> Thank you for the offer, @gyanfada! I think I'll stick to simply presenting myself. I'll have additional things to present and I think it'll be too difficult to co-ordinate multiple presenters, especially one remote, in a single short session.
> 
> I was thinking more along the lines of presenting a specific department's implementation _for_ them as an example of what's can be achieved by using PyMedPhys as a library, with appropriate acknowledgements of the persons and department of course!

@Matthew-Jennings sounds good! Have fun there!

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, what about devoting some of the time on gathering interest around a regular online PyMedPhys meetup? https://pymedphys.discourse.group/t/potential-for-a-regular-gather-town-meetup/214/5

**Comment by lipteck** [comment]
Hi Matthew,

I am happy to share our experience on the implementation of pymedphys on
the metersetmap comparison.

We have used the gui for manual comparison in our work as described in the
WC2022 poster. We have written a script that is possible to do mass TRF
with dicom comparison and provide boxplot. It has been uploaded to GitHub.

We are working towards reconstructing the TRF back to DICOM rtplan for
delivery and plan comparison
In Monaco.

Regards
Lip Teck

**Comment by Matthew-Jennings** [comment]
Thank you, @lipteck! Could you please link to the GitHub project in question? And perhaps any screenshots or figures that you think would be suitable for a PowerPoint slide to showcase your experience?

**Comment by lipteck** [comment]
Hi Matthew

Please find attached pdf A3 poster presented at the World Congress 2022.

Regards
Lip Teck
