### ISSUE TITLE
Better guidance for missing packages

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1746]
> > Yup, by design. If you run `pip install pymedphys[user,tests]` that should be sufficient.
> 
> OK great, the only thing is the error message to the user says to simply install `pip install pymedphys[user]`, is this intended?

Yeah... that should cover most use cases. It potentially could be worth some further logic to detect if the user needs to install other optional dependencies also... But... if a user is "using" the pymedphys library then that install message should cover all of those use cases.

...if they are testing, then `pymedphys[user]` is not enough. 

The fix for this could be, to have a dependency list created from the requirements files that is saved into the python package via propagate, and then read out the following `modname` variable:

https://github.com/pymedphys/pymedphys/blob/778e33769ead3ed6a6b366fd816f59aa8a2d8e76/lib/pymedphys/_vendor/apipkg/__init__.py#L248-L256

And then, if that `modname` variable is within the `user` dependency list, then ask the user to run `pip install pymedphys[user]`. If it is in the tests dependency list, then ask them to run `pip install pymedphys[user,tests]`...

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/issues/1744#issuecomment-1261938089_

**Comment by SimonBiggs** [comment]
@nlambriICH, might you want to try and give this a punt?

**Comment by nlambriICH** [comment]
Hi @SimonBiggs!

Is this something urgent? I'm quite swamped at the moment and I don't want to stale this issue.
If not I can of course take a look into it!

**Comment by SimonBiggs** [comment]
Not urgent at all. Feel free to pick it up when you'd like to take something in PyMedPhys for a spin.

Essentially, this is the error message users are shown when they try to use one of the optional dependencies and it is not installed. It's something that would be quite helpful for new users, but not something that has an urgent deadline.

**Comment by nlambriICH** [comment]
Hi @SimonBiggs

I would like to finally fix this issue. I need some guidance on where I should look in the code.

So far I've stepped through the code [here ](https://github.com/pymedphys/pymedphys/blob/778e33769ead3ed6a6b366fd816f59aa8a2d8e76/lib/pymedphys/_vendor/apipkg/__init__.py), but I couldn't understand when these line of code are excuted:

https://github.com/pymedphys/pymedphys/blob/778e33769ead3ed6a6b366fd816f59aa8a2d8e76/lib/pymedphys/_vendor/apipkg/__init__.py#L229-L256

Can you give me some hints on how to test this? Thank you

**Comment by SimonBiggs** [comment]
Yup :). These lines of code are executed whenever a new module from pymedphys._imports is imported (and had not previously been imported).

Drop a `print("boo")` within that file and observe when it pops up if you run `from pymedphys._imports import pydicom` :)

**Comment by nlambriICH** [comment]
I'm trying to push the changes to my fork and open a PR, but I get this error from pre-commit due to isort:

![Capture](https://github.com/pymedphys/pymedphys/assets/101093472/6e20346f-b3e0-44f2-92a4-43d306175acb)

I thought pymedphys required python >=3.8. Am I missing something?

**Comment by SimonBiggs** [comment]
Can you run:

```
poetry run pre-commit install
```

And try again?

**Comment by SimonBiggs** [comment]
Otherwise, if that doesn't work, can you bump the version here to the latest?

https://github.com/pymedphys/pymedphys/blob/f6acdf9bd2e8a32e372966879284fbd71c612358/.pre-commit-config.yaml#L20

**Comment by nlambriICH** [comment]
> Can you run:
> 
> ```
> poetry run pre-commit install
> ```
> 
> And try again?

Thanks, this did the trick.
