### ISSUE TITLE
Worthwhile paying attention to the pdf build of the docs?

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#175]
Interestingly when one searches "pymedphys" in Google they are taken to the pdf version of the docs before the website version.

Here is the current latest pdf version:

https://readthedocs.org/projects/pymedphys/downloads/pdf/latest

We can choose to not produce a pdf version at all, but I suspect that there might be value in it. So it then begs the question, if we are producing it as a version of the docs we should probably give it some love. Potentially even include it within the pipeline tests?

From a quick scan I can pick up a few glaring issues:

* The chapters are not defined properly 
* Our logos flow off of the page
* We should make labs not appear within the pdf version

**Comment by Centrus007** [comment]
Under what circumstances do you think we need the PDF version? It just seems a little counter to CI/CD. We want to be in a position to frequently release, meaning any PDF is likely to be obsolete very quickly...

**Comment by SimonBiggs** [comment]
Someone might want to download a specific version, and then also download
the docs as a pdf with it. Freeze things on their end and have an offline
set of docs for their specific version...

Not sure though.

It can certainly be disabled. Readthedocs makes it by default.

**Comment by Centrus007** [comment]
Maybe I'm overestimating this, but it seems to me that this will force annoying formatting compromises on the docs...

If so, is it worth it?

**Comment by SimonBiggs** [comment]
I'm not sure. I'm happy to disable it for now.

**Comment by Centrus007** [comment]
> I'm not sure. I'm happy to disable it for now.

I think that's probably the best route for now...

**Comment by SimonBiggs** [comment]
Done. Old versions of the docs will still probably hang around for a while.
