### ISSUE TITLE
Use a higher res logo for SA Health

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#176]
@Centrus007 what about if we used the following logo?

https://www.healthdirect.gov.au/partners/sa-health

**Comment by Centrus007** [comment]
Sure. :)

**Comment by Centrus007** [comment]
I'm having a play and the aspect ratio makes pretty formatting a bit of a challenge...

**Comment by Centrus007** [comment]
How's this? Matching width means other logos will be dwarfed by GOSA

![image](https://user-images.githubusercontent.com/19767103/56450654-b5d59c00-6366-11e9-8ef4-7ac1c2247367.png)

**Comment by Centrus007** [comment]
Might be nice to centre the logos based on the text width...

**Comment by Centrus007** [comment]
Actually, the standard sphinx `:align: center` seems to have worked well enough.

Half screen:

![image](https://user-images.githubusercontent.com/19767103/56450728-28df1280-6367-11e9-83be-946014acac97.png)

Full screen:

![image](https://user-images.githubusercontent.com/19767103/56450731-37c5c500-6367-11e9-82df-c7b9f68c0590.png)

**Comment by SimonBiggs** [comment]
Yup, looks good to me.
