### ISSUE TITLE
PyMedPhys visibility from Google search

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#180]
Following on from what @SimonBiggs discovered (that the PDF version of the docs is listed ahead of readthedocs), I've noticed this is the results order - for me at least - when I search for "pymedphys"

![image](https://user-images.githubusercontent.com/19767103/56450988-a1929e80-6368-11e9-8a6b-2d638ceba581.png)

Ideally, RTD would appear nearer the top, as would the GitHub page. It'd be nice if the GitLab page disappeared altogether.

Not sure if there's anything we can do about this, but even if we could somehow deprioritise GitLab, that would help avoid confusion, I think...

**Comment by SimonBiggs** [comment]
That's interesting, well, if we cancel the pdf version it'll drop off on any search so that's helpful. I could mark the girls repo as archived and read only. Google might pick up on that...

**Comment by SimonBiggs** [comment]
I've archived the GitLab repo, hopefully in a few weeks that repo will fall down the list as a result.

**Comment by SimonBiggs** [comment]
The GitLab repo was archived and it now links to the GitHub repo.
