### ISSUE TITLE
a problem when convert my logfiles to csv files.

### ISSUE THREAD

**Issue by daliDuans** [pymedphys/pymedphys#1815]
I have successfully installed PyMedPhys in my Win 10 computer, as shown in Figure 1-4. I want to convert my logfiles to csv files using the installed code. The files and file locations are showed in Figure 5. Howeve, the command prompt has some bug reports when i run the CLI code. As a result, the convertion was failure. The bug report is showed in the Figure 6. Could you help me solve my problem? Thank you very much!

Figure 1:
![Figure 1](https://github.com/pymedphys/pymedphys/assets/152958108/1dccf03b-2dce-40bc-be13-4c2864578d45)

Figure 2:
![Figure 2](https://github.com/pymedphys/pymedphys/assets/152958108/d1f83679-6ff7-49c5-b516-94dce7346e11)

Figure 3:
![Figure 3](https://github.com/pymedphys/pymedphys/assets/152958108/19bb2470-2308-4afa-a1fc-f021cd13520b)

Figure 4:
![Figure 4](https://github.com/pymedphys/pymedphys/assets/152958108/0ec6180c-e784-4fc3-bc41-f854651b68cf)

Figire 5:
![files location](https://github.com/pymedphys/pymedphys/assets/152958108/61c8cecc-8e2b-402c-8dcb-4bcc4a898b06)

Figure 6:
![报错](https://github.com/pymedphys/pymedphys/assets/152958108/c566078a-98ca-40ee-b321-6cc5c44a8ab4)

**Comment by daliDuans** [comment]
&nbsp;I am looking forward to seeing your release!&nbsp; please let me&nbsp; known once the fix was released. Thank you very much!



---Original---
From: "Simon ***@***.***&gt;
Date: Tue, Dec 5, 2023 16:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pymedphys/pymedphys] a problem when convert my logfiles to csvfiles. (Issue #1815)




 
Yup, these have been fixed with the GitHub repo itself. We just need to do a release. There are a few other things I want to do prior to a release. I'll see if I get a chance this weekend

**Comment by SimonBiggs** [comment]
Would you be able to install the latest development release by running the following and letting me know if it works?

```
pip install pymedphys[user]==0.40.0-dev3
```

**Comment by daliDuans** [comment]
The latest development release was&nbsp;successfully installed using "pip install pymedphys[user]==0.40.0-dev3". My logfiles was successfully&nbsp;converted to csv files using the updated codes.&nbsp; Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pymedphys/pymedphys"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pymedphys/pymedphys] a problem when convert my logfiles to csv files. (Issue #1815)





 
Would you be able to install the latest development release by running the following and letting me know if it works?
 pip install pymedphys[user]==0.40.0-dev3

**Comment by SimonBiggs** [comment]
My pleasure ☺️

**Comment by daliDuans** [comment]
Dear SimonBiggs, I have a new problem when convert my logfiles to csv files. Could you help me solve my problem? Thank you very much! The bug reports and the trf file to be converted were attached as following,

![Fig1](https://github.com/pymedphys/pymedphys/assets/152958108/7a66b99a-eba7-4fb6-a9ea-ad81ef91850e)
[24_01_27 11_41_01 Z AR_AR.zip](https://github.com/pymedphys/pymedphys/files/14106761/24_01_27.11_41_01.Z.AR_AR.zip)

**Comment by SimonBiggs** [comment]
Hi @daliDuans,

I missed this one. Did you get your issue fixed?

**Comment by daliDuans** [comment]
It has been fixed, thanks!



---Original---
From: "Simon ***@***.***&gt;
Date: Thu, May 2, 2024 13:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pymedphys/pymedphys] a problem when convert my logfiles to csvfiles. (Issue #1815)




 
Hi @daliDuans,
 
I missed this one. Did you get your issue fixed?
