### ISSUE TITLE
Forge a release

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1819]
@Matthew-Jennings, might you want to cut a release for PyMedPhys?

**Comment by Matthew-Jennings** [comment]
Sure :)

Is the CHANGELOG up to date though? I think more might have changed than updating gamma to use [Econforge's interpolation](https://github.com/EconForge/interpolation.py) by default. I can take a look, but could do with a bit of help here.

**Comment by SimonBiggs** [comment]
Are you able to do a diff between the last release and master? (GitHub
let's you compare between commits)
