### ISSUE TITLE
PyMedPhys Gui issue

### ISSUE THREAD

**Issue by zism** [pymedphys/pymedphys#1821]
Hello,
I cannot launch the gui on Ubuntu 22.04. I'm getting the following message:
-> pymedphys gui
Traceback (most recent call last):
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_vendor/apipkg/__init__.py", line 238, in __getattribute__
    return getattr(getmod(), name)
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_vendor/apipkg/__init__.py", line 216, in getmod
    x = importobj(modpath, None)
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_vendor/apipkg/__init__.py", line 103, in importobj
    module = __import__(modpath, None, None, ["__doc__"])
  File "/home/medphys/.local/lib/python3.10/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/medphys/.local/lib/python3.10/site-packages/streamlit/delta_generator.py", line 90, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/medphys/.local/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py", line 27, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medphys/.local/bin/pymedphys", line 8, in <module>
    sys.exit(main())
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/cli/__init__.py", line 148, in pymedphys_cli
    args.func(args)
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_gui.py", line 44, in main
    start.start_streamlit_server(streamlit_script_path, config)
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_streamlit/server/start.py", line 26, in start_streamlit_server
    st.bootstrap.load_config_options(flag_options=config)
  File "/home/medphys/.local/lib/python3.10/site-packages/pymedphys/_vendor/apipkg/__init__.py", line 248, in __getattribute__
    raise ModuleNotFoundError(
ModuleNotFoundError:
                    PyMedPhys was unable to import "streamlit.bootstrap.load_config_options".
                    The easiest way to fix this issue is to use the "[user]"
                    option when installing PyMedPhys. For example,
                    with pip this can be done by calling
                    "pip install pymedphys[user]==0.39.3".

**Comment by SimonBiggs** [comment]
Ahh, yes, Streamlit adjusted their API here. This will need to be fixed in the next version. As a workaround would you be able to install the version of Streamlit within here:

https://github.com/pymedphys/pymedphys/blob/main/requirements.txt

**Comment by zism** [comment]
It's working. Thank you

**Comment by SimonBiggs** [comment]
You're very welcome :)

**Comment by zism** [comment]
Hi, I'm having this message when loading a multi Arc plan via the gui:
"Unable to automatically determine whether angle is 180 or -180"
How to resolve it?

**Comment by sjswerdloff** [comment]
> Hi, I'm having this message when loading a multi Arc plan via the gui: "Unable to automatically determine whether angle is 180 or -180" How to resolve it?

Can you attach an anonymised version of the plan?
In general, it's tough to tell the difference without understanding the characteristics of the machine, but assuming that the machine is limited to a gantry angle of -180 <= x <= 180 we might be able to determine this based on the gantry rotation direction value.

**Comment by zism** [comment]
[1~242424.zip](https://github.com/pymedphys/pymedphys/files/14853432/1.242424.zip)

**Comment by zism** [comment]
[1~242424.zip](https://github.com/pymedphys/pymedphys/files/14853501/1.242424.zip)

**Comment by sjswerdloff** [comment]
Ah... Monaco data, not my forte.
However, the full error message is generated in **lib/pymedphys/_utilities/transforms/bipolar.py**, 
from the function **convert_IEC_angle_to_bipolar(...)** 
and the error should look like:

> While trying to convert IEC angles to bipolar angles, unable to automatically determine whether angle is 180 or  -180. The input angles were {input_angle}
        
So it would be helpful to know what value was shown for {input_angle}.

Further, I scripted the following (stealing from one of the tests):
I rounded the angles just to make it easier to read through them...

```
import pymedphys
# full path to the Monaco  tel file
tel_path='/Users/stuartswerdloff/Downloads/1~242424/plan/70gy/tel.1'
delivery_monaco = pymedphys.Delivery.from_monaco(tel_path)
rounded_gantry_angles = [ round(x) for x in delivery_monaco.gantry ]
print(rounded_gantry_angles)

```
and saw that there were multiple turnarounds (-177, -180, -180, -177); (176, 180, 180, 175) etc.

but those have already gone *through* the conversion from IEC to bipolar, so it didn't fail in being read from the Monaco tel.1 file.  It would help to have a full stack trace to rule out that it's a problem in the trf vs Monaco tel file data.

Do you have the option of converting this to DICOM, and then using the pymedphys GUI and load the plan as DICOM?

As an aside, I've been told that one usually scripts these Arcs so that the end point is not exactly 180 or -180 (rather 179.5 and -179.5 or something like that for bipolar definition, it would be 179.5 and 180.5 for IEC and you would not increase past 179.5 nor decrease below 180.5 from those angles respectively).

**Comment by zism** [comment]
I exported .dcm from Monaco and I get this message: ValueError: Expected input to be either LASTNAME^FIRSTNAME or LASTNAME, FIRSTNAME.

**Comment by zism** [comment]
I exported .dcm from Monaco and I get this message: WrongFileType: Does not appear to be a photon DICOM plan

**Comment by sjswerdloff** [comment]
> I exported .dcm from Monaco and I get this message: WrongFileType: Does not appear to be a photon DICOM plan

For that I suggest getting support from the vendor through their support channel.
Did you try running the script I included in my previous comment?

**Comment by zism** [comment]
> I exported .dcm from Monaco and I get this message: WrongFileType: Does not appear to be a photon DICOM plan

I removed setup fields and it works now.

**Comment by zism** [comment]
I moved to the version 0.4 and I'm getting this message when uploading .trf file: "tuple indices must be integers or slices, not str".
I'm not having this issue on the last version. Any solution?

**Comment by sjswerdloff** [comment]
> I moved to the version 0.4 and I'm getting this message when uploading .trf file: "tuple indices must be integers or slices, not str". I'm not having this issue on the last version. Any solution?

please attach the (anonymised) photon DICOM plan, and the full stack trace of the error message.
If it worked in 0.39.x, you might want to revert to that to continue your work.

**Comment by zism** [comment]
> > I moved to the version 0.4 and I'm getting this message when uploading .trf file: "tuple indices must be integers or slices, not str". I'm not having this issue on the last version. Any solution?
> 
> please attach the (anonymised) photon DICOM plan, and the full stack trace of the error message. If it worked in 0.39.x, you might want to revert to that to continue your work.

It's working on 0.39.3

**Comment by zism** [comment]
I'm having this error when implementing MetersetMap Comparison on version 0.39.3: 
OSError: cannot write mode F as PNG

**Comment by sjswerdloff** [comment]
> I'm having this error when implementing MetersetMap Comparison on version 0.39.3: OSError: cannot write mode F as PNG

without sample data and a full stack trace, it's not feasible to provide assistance.
Please copy the text of the full stack trace and attach the files used for comparison.  If the TRF file is the same as in the zip above, please state that is the case.
