### ISSUE TITLE
Independent dose calculation of Brachytherapy Dicom files

### ISSUE THREAD

**Issue by Suman-c21** [pymedphys/pymedphys#1824]
Hi 

Do you guys know what is the tag for Catheter coordinates? It is mention in the below code at 0x300f, 0x1000, but i couldn't see in my DICOM files.  It is mention in the code but still not making sense to me.

I have attached the code and error. Please suggest me.

![indep](https://github.com/pymedphys/pymedphys/assets/58918870/75096b55-071c-40e0-9ac2-a3238f4f8e45)
![ind2](https://github.com/pymedphys/pymedphys/assets/58918870/f285a1ab-a7ee-4c21-8129-689121038525)

**Comment by sjswerdloff** [comment]
300a,02d2 is type 1 relative position 
or
300a,02d4 is type 3, 3D position
both are in
https://dicom.innolitics.com/ciods/rt-plan/rt-brachy-application-setups/300a0230/300a0280/300a02d0

**Comment by sjswerdloff** [comment]
300f is a private block, so not standard DICOM

**Comment by sjswerdloff** [comment]
@Suman-c21 was the code you screenshot part of pymedphys?
Was there any pymedphys in use or intended to be used?
The elements that would be accessed from the private element looked more like RT Structure set content.
What kind of object is in use?  I initially assumed you were reading in an RT Plan file but I don't think any assumptions can be made.

**Comment by Suman-c21** [comment]
yes, it was a part of pymedphys. I was trying to calcaulte with my dataset using that code, but still the error persists. This code was from TG43 Implmentation.ipynb (notebook file), In34 Determine dwell directions. They are using the RT plan file.dcm

The above error was from RT plan file. Could you please explain me in details what is happening there? I am new with those scripts.

**Comment by sjswerdloff** [comment]
There's a bit more to accessing the information...  The previous code accessing a private element was expecting an entire tree of elements underneath it that are the equivalent of information that comes in RT Structure Set. 
If your data has no PHI, you could attach it for review (to see whether the data you are looking for is anywhere *in* your DICOM object).  Or, you could use PyMedPhys to *anonymise* the data (and then attach that anonymised plan).
