### ISSUE TITLE
Add filter to Claude prompt

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1839]
I realise we may be in a weird scenario where every new prompt to Claude results in an entire record of the conversation being included in each of Claude's responses. Might be worth filtering out the "details" tag when sending follow up comments to Claude 

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/pull/1838#discussion_r1536599257_

**Comment by SimonBiggs** [comment]
Let's do a demonstration (I imagine it could get costly quick...). Hi Claude, could you please summarise what you know about PyMedPhys?

**Comment by SimonBiggs** [comment]
Ooo, the way the prompt is formatted, Matt, Claude thought that you posted that message. We may find more success by formatting the issue history more like a chat transcript.

**Comment by SimonBiggs** [comment]
Ooo, and we can see, if you click "details" above that there is indeed a nested set of details were every response includes a copy of every response... 

Claude, that's going to end up exploding in the number of tokens that we send to you...

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, perhaps the simplest solution for now is to omit the prompt details. There would still be some duplication, but it would at least avoid nesting.

The prompt would remain visible in the CI.

**Comment by Matthew-Jennings** [comment]
Maybe we could start with that and then implement a solution that filters out text with the prompts' tags.

**Comment by SimonBiggs** [comment]
Fixed
