### ISSUE TITLE
Use DicomBytesIO when writing file tests with DICOM

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#185]
Heya @Centrus007 

I always learn something when contributing to upstream projects:

https://github.com/pydicom/pydicom/pull/835#discussion_r277179099

We should be using DicomBytesIO when making tests that use DICOM files.

https://github.com/pydicom/pydicom/pull/836#issue-272250630

**Comment by SimonBiggs** [comment]
Here is @darcymason test which neatly gets around a lot of our DICOM file testing issues:

https://github.com/pydicom/pydicom/blob/ef0a20d0b194ba34bb4c6155f9670097d4482a40/pydicom/tests/test_dataset.py#L71-L90

**Comment by Centrus007** [comment]
That is better, for sure! But still doesn't *necessarily* abate my preference to use verified DICOM compliant files for certain tests, e.g. "anonymise_file()". 

Note that `pydicom` does have quite the suite of [DICOM test files](https://github.com/pydicom/pydicom/tree/master/pydicom/data/test_files), and does tend to use them in tests:
https://github.com/pydicom/pydicom/blob/ef0a20d0b194ba34bb4c6155f9670097d4482a40/pydicom/tests/test_dataset.py#L880
https://github.com/pydicom/pydicom/blob/ef0a20d0b194ba34bb4c6155f9670097d4482a40/pydicom/tests/test_dataset.py#L1189
https://github.com/pydicom/pydicom/blob/ef0a20d0b194ba34bb4c6155f9670097d4482a40/pydicom/tests/test_dataset.py#L1206
etc.

**Comment by SimonBiggs** [comment]
Oh yes, certainly. I was just referring to the times when we create DICOM
files on disk and have concurrency issues. Probably speed the test up quite
a bit too...

**Comment by Centrus007** [comment]
> Oh yes, certainly. I was just referring to the times when we create DICOM
files on disk and have concurrency issues.

Very good point.
