### ISSUE TITLE
Consider moving away from readthedocs in favour of GitHub pages

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#200]
It might be time to move away from readthedocs. Here are my current two reasons:

* Directly integrating pyodide applications within the documentation may be quite difficult with readthedocs, not sure, but I have suspicions.
* Orchestration of all of our install and build steps with lerna with yarn will be quite nice. I don't believe we can get yarn on readthedocs.

**Comment by Centrus007** [comment]
I'm certainly open to it. A cursory search through Google and GitHub seems to tilt slightly in GitHub Pages' favour.

Would ou also move to a markdown solution? Our current need to support both rst & markdown for some of our docs does introduce certain formatting frustrations... but I haven't really looked at markdown-based auto-doc generators..

**Comment by Centrus007** [comment]
There's [Mkdocs](https://github.com/mkdocs/mkdocs/).

**Comment by SimonBiggs** [comment]
There are some huge benefits from using `Sphinx`. Sphinx of course can use markdown instead of rst. Things like the following however are a huge boon for rst:

https://raw.githubusercontent.com/pymedphys/pymedphys/master/docs/getting-started/about.rst

**Comment by SimonBiggs** [comment]
And things like argparse in the following are `Sphinx` specific:

https://raw.githubusercontent.com/pymedphys/pymedphys/master/docs/user/interfaces/cli/trf.rst

**Comment by SimonBiggs** [comment]
Open to Markdown, but I imagine that can be dealt with separately as an orthogonal issue.

**Comment by Centrus007** [comment]
> I'm open to a switch to Markdown, but I imagine that can be dealt with separately as an orthogonal issue.

I'm not pushing hard for it. My complaints are minor, and it seems as though the benefits you outline strongly outweigh my complaints.

**Comment by SimonBiggs** [comment]
Swapped to netlify
