### ISSUE TITLE
conda activate command doesn't work in `yarn`

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#204]
So the problem I was having was that, not matter how I try to slice it, I *cannot* get a `conda activate` command to run via yarn. EVen in it's own command, even using the various different syntax options.

My batch files *did* work, just saying... ;)

**Comment by SimonBiggs** [comment]
:) sounds good. How about a small compromise. Have a bat file that says something like the following:

```batch
yarn conda:create
call conda activate pmp
yarn bootstrap
```

**Comment by SimonBiggs** [comment]
We'll have to edit `yarn conda:create` of course first.
