### ISSUE TITLE
Release patch workflow

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#206]
Hi @SimonBiggs 

I think we basically agreed to this over the phone, but just so it's documented and here for reference:

I think the solution to our "can't merge a release branch into `master` once the two branches have diverged" problem is to:

1. Create a new branch from the release branch (e.g. `fix-docs-typo` from `0.8.x`)
2. Commit fixes to `fix docs typo`
3. Merge `fix docs typo` into both `master` and `0.8.x`

That works, right?

**Comment by SimonBiggs** [comment]
The method I've used in the past has been:

* Work directly in `0.8.x`, make the changes, make the release.
* Once happy with release, run `git checkout 0.8.x && git checkout -b intermediary-branch`
* Then merge `intermediary-branch` into master.

**Comment by Centrus007** [comment]
Sure, that works too :)
