### ISSUE TITLE
Azure DevOps 

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#21]
So, I have set up testing for Windows, macOS, and Linux. The tests are currently failing and my pipelines need a bit more work. But I'm getting there:

https://dev.azure.com/pymedphys/pymedphys/_build/results?buildId=26

**Comment by SimonBiggs** [comment]
@Centrus007 something of interest is that there is a deploy to Windows Store option:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azdevops

**Comment by SimonBiggs** [comment]
Woohoo! So I got one to pass. macOS of all the options :/

https://dev.azure.com/pymedphys/pymedphys/_build/results?buildId=104

**Comment by Centrus007** [comment]
> macOS of all the options :/

Ironic, ha!

**Comment by SimonBiggs** [comment]
Now passing on all three OSs :)

**Comment by Centrus007** [comment]
Great!

**Comment by SimonBiggs** [comment]
It's helpful already. Today, I was working on my windows machine at work.
Everything was working locally. I pushed the branch, online Windows passes,
but Linux and Mac failed... I'll have to get to the bottom of that
tomorrow. Multi OS tests has been worth the effort.
