### ISSUE TITLE
A project that might help with multi package orchestration

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#212]
https://github.com/dephell/dephell

**Comment by orsinium** [comment]
How is it going? I'm the author of DepHell. If you have troubles with dephell integration, you can write here your questions, and I will help you :)

**Comment by SimonBiggs** [comment]
Hi @orsinium,

Haven't actually tried out your tool yet. Thanks for popping by though! :)

**Comment by SimonBiggs** [comment]
Steering away from multiple packages, so this is no longer needed.
