### ISSUE TITLE
Sustainable Open Source

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#213]
Consider building a revenue model for PyMedPhys based upon the successes of the Ghost platform, with the goal to eventually, one day, attract high quality software engineers to provide full time maintenance and support for PyMedPhys:

https://ghost.org/about/

![image](https://user-images.githubusercontent.com/6559099/56776575-70a2e580-6810-11e9-8a1c-7f31faa10ab9.png)

They have a foundation, and their financial data is public:

![image](https://user-images.githubusercontent.com/6559099/56776590-916b3b00-6810-11e9-8020-1018598910f2.png)

To begin stepping into this space I propose we start by implementing **non-intrusive** advertising on the documentation, but also within any applications built. May I repeat, any adverts on any PyMedPhys product, throughout the lifetime of PyMedPhys, need to be non-intrusive. In practice this means that adverts are to be out of the way, visible, but small, no movement, as well as being relevant to Medical Physicists. Adverts should always have a "I don't want to see this ad again" link below it as well as a little link to a page that explains why we have ads and how it helps make the open source software sustainable.

To achieve this in an efficient and transparent way some of the following tools will be helpful:

* Advertising bidding -- https://github.com/integralads/Prebid.js
* Viewable Impressions
  * https://integralads.com/news/integral-ad-science-partners-google-others-open-source-viewability/
  * https://www.thinkwithgoogle.com/feature/viewability/#/demo
  * https://kahwee.github.io/viewability/timer.html

There would also be value in having a "supporters page", which collates all of the adverts in one place, so that people can go there and browse quality adverts for products sold by the companies that have chosen to support PyMedPhys through paying for advertising.

**Comment by SimonBiggs** [comment]
Wrote the following at https://github.com/pymedphys/pymedphys/pull/222#issuecomment-488176524

It belongs here though.

Anyway, my steps are the following:

* Implement the ability to login to the docs with GitHub, will use [Firebase to facilitate this](https://firebase.google.com/docs/auth/web/github-auth).
  * Have a list of GitHub users that are marked as developers
  * Make it so that advertising shows, but isn't recorded against the viewable impressions tally if there is a developer.
* Implement viewable impressions on the advertising spot as well as the sponsor page
* Implement click through tracking
* Implement user location classification
* Implement pulling advertising images, click url, and prices paid from a database (once again using Firebase)
  * Have these ads be displayed on the website by user location, and prioritised by who is paying the most -- need to sort out the algorithm here, potentially included a little bit of randomisation so that 1c extra advertising spend doesn't result in only those ads being seen.
* Implement the ability for advertisers to log in, create an advert, and have it be uploaded to the database.
  * Advert would consist of an image for the advertising spot, the company's logo for the sponsors page, a url for the advert, and a url for the company's logo.
* Implement payment with stripe.
* Display to advertisers a report of click through rates, impressions, location of users who have seen the ads, as well as the number of impressions seen by developers that were not counted to the tally.
* When sponsors are going to pay they can see what others have paid, and have it be clear that those who pay the most have their advertising prioritised over those who haven't paid as much.

**Comment by Centrus007** [comment]
Look at all this unused real estate!

![image](https://user-images.githubusercontent.com/19767103/57012342-1efdbf00-6c45-11e9-87c1-27f9d28015d1.png)

**Comment by SimonBiggs** [comment]
... which would be exceptionally distracting if it was used with
advertising...

**Comment by Centrus007** [comment]
I don't think so. I'm not proposing the entire width of the thing. But a vertical ad bar would do nicely j think.

To be honest, I don't really see distraction as that much of a problem. People are getting an awesome library for FREE. They can put up with a little distraction.

**Comment by SimonBiggs** [comment]
I was actually thinking of putting a chat window there... Something like
gitter? The ability for people to live chat with others (and us) right
within the docs...

**Comment by SimonBiggs** [comment]
I dunno, I might be able to come around. We would have to be very strict on ads that we let go there. For now, I am far more comfortable with the ad that will always be seen within the navigation panel whenever someone scrolls down a little. But still doesn't detract from the page as a whole when you first load it up.

**Comment by Centrus007** [comment]
> navigation panel whenever someone scrolls down a little

I think the requirement to scroll down on the navbar to see it severely limits its visibility while providing a very, very minor reduction in "distraction".

Some of the most visited websites in the *world* have far, far, far more "intrusive" ads, both on the side and in the main text! C.f. Google, Facebook, any news site... I don't think there is much evidence to suggest it really detracts from the experience. Ad clutter is a problem, yes, but I'm getting the impression that your level of comfort might be quite far from actually hitting a demonstrably problematic threshold (i.e. a level of ad clutter that actually produces a reduction in page visits).

I promise I'm not advocating for a massive clickbait approach, but I think there's little reason to be overly cautious and slow to ramp up ad real estate...

**Comment by SimonBiggs** [comment]
Okay. Would you be in a position to create a pull request with some placeholders, much the same as the current placeholder, of where you think there should be advertising spots? Bear in mind how the ad is displayed for multiple screen resolutions and device formats...

Then we can play around with previews of those placeholders and see whether or not they are intrusive...

**Comment by Centrus007** [comment]
My HTML/CSS is very poor, but I can give it a go! There's no time like now to skill up :)

**Comment by SimonBiggs** [comment]
For a bump in the right direction here is the commit where I added in the current advert placeholder:

https://github.com/pymedphys/pymedphys/pull/230/commits/51d5efdeb1b56a923e1763c3a1c3436080951ddc?file-filters%5B%5D=.html#diff-cac3dc3bfd42bc240bc9eb924f8dbfdd

Pressing Ctrl + Shift + I within chrome is a useful way to iterate.

Within that panel you can directly edit the style sheet and see the changes on the page so that you can know what impact your changes will have. For example, I have made the background of the ad placeholder red in the following screenshot:

![image](https://user-images.githubusercontent.com/6559099/57054245-a5aeac80-6cd6-11e9-9b50-8d56df576792.png)

**Comment by SimonBiggs** [comment]
I have also attached the [gimp](https://www.gimp.org/) file that I used to create the placeholder. That way we can keep a consistent style across the placeholders.

[placeholder.zip](https://github.com/pymedphys/pymedphys/files/3136573/placeholder.zip)

**Comment by SimonBiggs** [comment]
...maybe we should commit our xcf files somewhere...

**Comment by SimonBiggs** [comment]
Also, just a note here (from my phone) while I remember we should probably
add the following maintenance tasks to the list:

* Training and onboarding new contributors
* Maintaining up to date documentation

**Comment by Centrus007** [comment]
Thank you! Just a quick question... how do I make the existing sidebar placeholder "sticky"? Embarrassingly struggling so far...

**Comment by SimonBiggs** [comment]
All good :) I believe position fixed is way you're after:

https://www.w3schools.com/css/css_positioning.asp

**Comment by SimonBiggs** [comment]
What*

**Comment by SimonBiggs** [comment]
Or maybe position sticky? (Described within that same link) Up to you.

**Comment by SimonBiggs** [comment]
In that chrome developers console there is also a button that can be
pressed to convert the page into different screen sizes. Need to make sure
that the element appropriately sits on the screen no matter what the screen
size. Potentially for any screen or browser size that is smaller than the
main docs area + ad width could just hide the ad?

Need to use media queries to achieve that. Something like screen width less
than x set element display to none.

**Comment by SimonBiggs** [comment]
Here is some info on media queries:

https://www.w3schools.com/css/css_rwd_mediaqueries.asp

**Comment by SimonBiggs** [comment]
@Centrus007 how'd you go?

**Comment by Centrus007** [comment]
No deal so far. I think the img might need to be in another `<div>` block?

**Comment by SimonBiggs** [comment]
Many ways to skin a cat.

**Comment by Centrus007** [comment]
I'm sorry. Without a bit more tutelage, I'm not going to get anywhere.

I tried a lot of things, like placing a div below the side-scroll div, but I can't get it to fixed (it just disappears or remains unchanged. I wondered whether it was an overlap problem, but I haven't verified and it's difficult to do so without even a basic knowledge of html/css structure. I'm really bumbling in the dark here, and it's probably a waste of time until I'm more up to speed with the basics.

**Comment by SimonBiggs** [comment]
kk, sorry about that.

**Comment by Centrus007** [comment]
Don't be sorry! I just need to up my web-dev game :)

**Comment by SimonBiggs** [comment]
By removing js from the repo this option, in this way, is closed for now.

Of interest, the poetry docs appear quite customised (https://poetry.eustace.io/docs/) with no js in that repo (https://github.com/sdispater/poetry/tree/master/docs/theme).

So there are options open to us, just not in the way detailed in this issue.

Personally, I am becoming more convinced to steer clear of monetisation... but that is a separate issue to what is being detailed here.
