### ISSUE TITLE
Installation instructions - should install nbstripout in conda base if working in an env 

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#234]
Anaconda's base python interpreter is added to PATH, whereas interpreters within environments aren't. nbstripout needs to be on PATH for VS code to be able to commit due to recent commit hook addition, even if an environment that contains nbstripout is activated.

Propose that we include instructions to install nbstripout in base AND env for those using envs. Could instead get users to add env to PATH, but I'm inclined the think the former solution is better. What do you think?

**Comment by SimonBiggs** [comment]
I would say that this isn't because of the recent hook, it's just that the recent hook has brought it to our attention. I imagine without this hook it just wouldn't have used nbstripout... Is this true?

... this is beginning to step into the realm where I would rather move away from the recommendation to "use environments by default" stance.

**Comment by SimonBiggs** [comment]
Also, when an environment is activated the PATH variable is adjusted so that the environment interpreter is added to the PATH.

For example:

```python
conda deactivate
echo %PATH%
conda activate pmp
echo %PATH%
```

**Comment by Centrus007** [comment]
> Also, when an environment is activated the PATH variable is adjusted so that the environment interpreter is added to the PATH.

Is this not terminal specific? Env activation is terminal specific...

Here's what I noticed:

- I have an env called `pmp`
- `nbstripout` was definitely installed in `pmp`
- Git commits in Cmder with `pmp` activated worked fine. I'm relatively confident `nbstripout` was working, since I could see `husky` related text in commit's printed output.
- Git commits in VS Code failed with `pmp` activated, and I could see that `nbstripout` was an unrecognised command.
  - VS Code seems to run a new instance of CMD when performing git commands. Perhaps this instance of CMD simply doesn't activate the environment...

**Comment by SimonBiggs** [comment]
> VS Code seems to run a new instance of CMD when performing git commands. Perhaps this instance of CMD simply doesn't activate the environment...

It's probably that, that should be addressed...

**Comment by Centrus007** [comment]
> ... this is beginning to step into the realm where I would rather move away from the recommendation to "use environments by default" stance.

I've been thinking that we might want to include, say, RayStation scripts in PyMedPhys. Presently, RayStation required python 2.7 (admittedly they have said they expect to transition to python 3), so we'd need to support at least one other interpreter. Separate environments can facilitate this.

**Comment by Centrus007** [comment]
> It's probably that, that should be addressed...

Well... I sort of agree. But I do kinda think that Git is a rather separate beast from any installed python interpreters (and thus, envs). E.g., consider a project that requires multiple envs (very likely in a monorepo model). If so, perhaps Git hooks ought not to rely on envs?

**Comment by SimonBiggs** [comment]
> If so, perhaps Git hooks ought not to rely on envs?

Fair point. That does make sense. I'm convinced. What do you propose as a solution?

**Comment by SimonBiggs** [comment]
> I've been thinking that we might want to include, say, RayStation scripts in PyMedPhys. Presently, RayStation required python 2.7 (admittedly they have said they expect to transition to python 3), so if we do include them, we'd need to support at least one other interpreter. Separate environments can facilitate this.

I personally am not too keen on providing support for an interpreter that is reaching [end of life in 35 weeks](https://python3statement.org/).

**Comment by Centrus007** [comment]
If `nbstripout` and any other python scripts used by Git are installed in *base*, it will be run regardless of whether you're in an env or not. If the terminal/app can't find `nbstripout` in the env, it will look in base since base is "permanently" in the PATH.

**Comment by Centrus007** [comment]
> I personally am not too keen on providing support for an interpreter that is reaching end of life in about 35 weeks.

Fair enough. So we wait then?

I might actually contact RaySearch and see if I can glean a timeline on python 3 support...

**Comment by SimonBiggs** [comment]
Yeah I think a timeline on their end will be helpful for us.

**Comment by Centrus007** [comment]
So, RayStation version 8B was released a few months ago with a CPython 3.6 interpreter. See the following note:

> CPython 3.6 is supported from v8B onwards. We haven't been given a date for when IronPython and CPython 2.7 will no longer be supported. From v8B we would encourage all users to transition to CPython 3.6, the only reason we still support the other two is because users on older versions of RayStation need time to transition to CPython 3.6 therefore we need to be backwards compatible for the moment

**Comment by SimonBiggs** [comment]
Alright, so maybe we should hold onto Python 3.6 support...

**Comment by Centrus007** [comment]
So, on a related note, your new hook that checks for installation of `pymedphys_monomanage` also breaks VS Code...

I agree that the fault here is really VS code. It's git operations should occur within the same environment as is activated for the debugger etc. But there's still the point that `git` perhaps ought not to depend on envs at all...

Is there another way to do this check? Probably not.

Might be worth raising a VS Code issue...

**Comment by SimonBiggs** [comment]
Doesn't break it for me, this is an Windows as well... It raises an error
if yarn tree hasn't been run, but then the commit just needs to be run
again.

...But I am okay with removing the hook. We can pick up issues that the
hook was picking up with the pipelines...

**Comment by SimonBiggs** [comment]
The hook was actually getting a bit annoying. It ran in less than a second
at home for no changes and about 5-10 seconds when a change was needed. At
work, it takes ~1 minute. That's painful.
