### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#239]
We should make a contributing.md, move the current contributing contents to it and then include from that file the same way we drove readme.md

We also should change the contributing workflow from a "give contributors push permissions" to a "get contributors to fork to their own repo then make a pull request" model. That way of a contributor accidentally adds large files to their repo, then removes them for example, or makes a lot of messy commits then the pull request can be squished and merged. That way, none of the cruft gets stored within PyMedPhys' git history.

It makes contributing to PyMedPhys a little more difficult, but it is the defacto way that open source git repos run. I think the benefits outweigh the costs.

**Comment by Centrus007** [comment]
Agreed. :)
