### ISSUE TITLE
Easier to read error logs

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#246]
Something that might be worth making liberal use of ...

https://github.com/cknd/stackprinter

**Comment by Centrus007** [comment]
I had been thinking that we ought to use Python's native [logging ](https://docs.python.org/3/library/logging.html) for our CLIs, at least. Output could be redirected to a GUI widget as well.

I'm pretty well experienced with it - we use it liberally at the RAH.

**Comment by Centrus007** [comment]
(I meant that as a relevant aside: it need not be `logging` *or* `stackprinter`. I'm just very used to using `logging` to output more useful error messages to users, to provide information on execution progress, to increase verbosity and debug issues, etc.)

**Comment by SimonBiggs** [comment]
Yeah let's do that. I'm just not experienced with it, more than happy to
learn though :).
