### ISSUE TITLE
A good introduction to the webdev world

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#247]
The webdev world is a very complicated one. I'm normally not a fan of tutorials, but my first foray into the webdev world was via a tutorial, and I found it really helped me find my feet.

There will likely be buckets of new concepts in the following tutorial, but if you struggle through it I imagine you'll have the core foundations required to step forward into our blueprintjs + pyiodide development for our desktop web applications.

https://reactjs.org/tutorial/tutorial.html

**Comment by SimonBiggs** [comment]
Make sure to pick the option to do the tutorial locally. It's important to get familiar with some of the webdev toolkit.

**Comment by Centrus007** [comment]
Thanks! I'll make my way through it :)

(I love tutorials, some are made very, very, well)
