### ISSUE TITLE
Swap to Windows Terminal in the docs?

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#258]
Yay :)... Let's hope it's good this time :)

https://www.theverge.com/2019/5/6/18527870/microsoft-windows-terminal-command-line-tool

**Comment by Centrus007** [comment]
I did see that!

**Comment by Centrus007** [comment]
Did you see [this](https://mspoweruser.com/microsoft-announces-visual-studio-online-a-web-based-code-editor/) as well?

**Comment by SimonBiggs** [comment]
> Did you see [this](https://mspoweruser.com/microsoft-announces-visual-studio-online-a-web-based-code-editor/) as well?

That is very neat :). I wonder if it will have access to things such pylint...

**Comment by Centrus007** [comment]
It's meant to be compatible with all VS Code extensions...

**Comment by SimonBiggs** [comment]
I hope so.

This is also pretty cool:
https://techcrunch.com/2019/05/06/microsofts-intellicode-for-ai-assisted-coding-is-now-generally-available/

I wonder how to enable it...

**Comment by SimonBiggs** [comment]
Consider swapping from cmdr to windows terminal in the docs?

https://github.com/microsoft/terminal#chocolatey-unofficial

**Comment by SimonBiggs** [comment]
What do you think about making the swap @Matthew-Jennings?

**Comment by SimonBiggs** [comment]
I think we should install it via chocolatey

**Comment by Matthew-Jennings** [comment]
I think if it proves satisfactory - I haven't used it yet - then yes; at least eventually.

We're still on Windows 7 here. Many institutions around the world will be. And I even suspect that some will remain with it for at least a short period post EOL...

**Comment by SimonBiggs** [comment]
That's okay, we don't need to support software that is less than 6 months
away from end of life. If someone wants to develop on end of life OSs they
can solve issues that crop up.

**Comment by SimonBiggs** [comment]
I think what we really need in that document is a few tiers. A top level, here is the bare minimum that you need to get up and running (written in a platform independent way). Then provide opinionated instructions for Windows 10, macOS, and Ubuntu.

**Comment by SimonBiggs** [comment]
That way, if someone wants to customise the installation to their non-standard set up they can read the platform independent instructions and customise it themselves to their OS

**Comment by Matthew-Jennings** [comment]
Agreed.
