### ISSUE TITLE
Make gamma compatible with pyodide

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#260]
We need to repackage a bit further. Turns out although scipy works, it is humungous and doesn't get cached.

https://github.com/iodide-project/pyodide/issues/240

Until that's fixed it is not feasible for us to build any webapps that have scipy as a dependency.

...so, we need to do a bit more splitting and refactoring so that the stuff we really want (dicom and trf reading) has no dependency on scipy. Should be doable, just need to sort things out a bit.

We should do this before we forge a subpackage release of 0.2.0.

**Comment by Centrus007** [comment]
Gamma would be nice too!

**Comment by SimonBiggs** [comment]
We would have to swap in our own linear interpolation for that...

**Comment by SimonBiggs** [comment]
... I'm not keen on that level of restructuring just yet...

**Comment by SimonBiggs** [comment]
... I think we need to decouple dicom from analyse. If we need to we can make two dicom packages, one that depends on analyse and the other that doesn't...

**Comment by SimonBiggs** [comment]
I could just copy "cube geometry" into dicom. It's only purpose at the moment is to extract dose planes from DICOM files... So it possibly better fits there anyway...

https://github.com/pymedphys/pymedphys/blob/4d3302df15353dc3a4c6ac3af1c8550aa4d8304c/packages/pymedphys_dicom/src/pymedphys_dicom/dicom/_level1/structure.py#L39

**Comment by SimonBiggs** [comment]
This needs to go too:

https://github.com/pymedphys/pymedphys/blob/4d3302df15353dc3a4c6ac3af1c8550aa4d8304c/packages/pymedphys_dicom/src/pymedphys_dicom/dicom/_level2/dose.py#L37

**Comment by SimonBiggs** [comment]
And that's it! Gee, that should be easy enough.

**Comment by Centrus007** [comment]
> We would have to swap in our own linear interpolation for that...

For now, could we simply extract the relevant code from `scipy` and insert somewhere in `pymedphys` (with the appropriate acknowledgements, of course)? If so, that'd be pretty easy...

**Comment by SimonBiggs** [comment]
Yes certainly, as long as it's mostly standalone within scipy... I think that interpolation function is reltively standalone ...

That could solve https://github.com/pymedphys/pymedphys/issues/260#issuecomment-490050260 also... Yeah, I think that's a good idea ...

**Comment by SimonBiggs** [comment]
We could make a "pymedphys_miniscipy" package which has a few key functions in it that we like to use that are relatively standalone. It would have its own license file and have comments referring to what commit hash and file link was used to pull the code from.

**Comment by Centrus007** [comment]
> We could make a "pymedphys_miniscipy" package which has a few key functions in it that we like to use that are relatively standalone. It would have its own license file matching scipy's and have comments referring to what commit hash and file link was used to pull the code from.

Sounds good to me.

Will pyodide be incompatible with `numba`? I'm keen to try [these interpolators](https://github.com/EconForge/interpolation.py) out.

**Comment by SimonBiggs** [comment]
For now, most certainly. In the future (more distant future) it will likely run. Anything that isn't pure python needs specific attention and won't just work. At the moment they're still focusing on packages like scipy to improve there integration. Once the big fish have been fried things like numba I imagine will follow suit.

See also https://github.com/iodide-project/pyodide/issues/416 for more info on scipy itself.

**Comment by SimonBiggs** [comment]
I just renamed this to highlight the outstanding issue discussed within here.

**Comment by SimonBiggs** [comment]
Done
