### ISSUE TITLE
convert trf to csv file

### ISSUE THREAD

**Issue by alberwan** [pymedphys/pymedphys#288]
I am using cli "pymedphys trf to-csv "D:\Projects\Python\TRF_data\elekta_reference\17_04_19 21_18_39 Z .trf" (see below): 

(base) C:\Windows\system32>pymedphys trf to-csv "D:\Projects\Python\TRF_data\elekta_reference\17_04_19 21_18_39 Z .trf"

Converting D:\Projects\Python\TRF_data\elekta_reference\17_04_19 21_18_39 Z .trf

My question is:  Where the csv file go?  I couldn't find it in the current directory (C:\Windows\system32) and trf file directory (D:\Projects\Python\TRF_data\elekta_reference).  Can anybody help?

Thanks

**Comment by SimonBiggs** [comment]
Hi @alberwan 

It should have landed in the same file as the TRF file. Could you change to the directory of the logfile itself and run `pymedphys trf to-csv *.trf`?

**Comment by Centrus007** [comment]
> same **file** as the TRF file

same **directory**, I think :)

**Comment by SimonBiggs** [comment]
Yup :)

**Comment by SimonBiggs** [comment]
@alberwan did this solve your issue?

**Comment by SimonBiggs** [comment]
(I'm going to close it, please reopen it and/or comment if you are still having a problem)
