### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by alberwan** [pymedphys/pymedphys#294]
Hi:

I got "Permission denied (publickey)" error:

D:\Projects\pymedphys-master\pymedphys>git clone git@github.com:pymedphys/pymedphys.git
Cloning into 'pymedphys'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anybody help?
Thanks

**Comment by SimonBiggs** [comment]
Hi @alberwan you've just been given access, so that should now work, but I just wanted to check what you were trying to do.

**Comment by alberwan** [comment]
Hi Simon:
I will change anything.  Just read it.
ThanksAlbert
    On Wednesday, May 15, 2019, 4:15:45 PM EDT, Simon Biggs <notifications@github.com> wrote:  
 
 
Hi @alberwan you've just been given access, so that should now work, but I just wanted to check what you were trying to do.

**Comment by SimonBiggs** [comment]
You're certainly allowed to change things :) even encouraged to do so :).

For your future knowledge, if you do just want to read a git repo you can fork it to your own account, and then clone it from there :).
