### ISSUE TITLE
Current state of pyodide integration with PyMedPhys docs

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#295]
Just wanted to have a place here to keep people abreast of pyodide progress. 

Over at https://github.com/pymedphys/pymedphys/pull/252 I have begun experimenting with running `pydicom` within the client's browser, within the documentation. I believe it will be an amazing use case to be able to build little applications directly into the docs.

At the moment the `pymedphys` sub packages are still a bit too heavy on the dependency side of things, but `pydicom`, is beautifully standalone. So, it works like a charm. Once we craft a 0.8.0 release this will be fixed and I'll change this example to using some of our libraries.

If you open the following link and open the browser console you'll see the following console items.

https://deploy-preview-252--pymedphys.netlify.com/

![image](https://user-images.githubusercontent.com/6559099/57193427-378c1300-6f7e-11e9-812a-bd536109b0eb.png)

That last item there is a print out from pydicom, directly running within the client's browser (no server is running python). This has a huge benefit of not having any identifying DICOM files be sent to a server, while still being able to have all the power of pydicom (and numpy, and scipy, etc...) at ones fingertips.

No installation required.

See the following for a minimal html file that runs pydicom with pyodide:

```html
<html>

<head>
  <script type="text/javascript" src="https://pyodide.pymedphys.com/pyodide.js"></script>
  <script type="text/javascript">
    pythonCode = `
def something_awesome(*args):
    import pydicom

    dataset = pydicom.Dataset()
    dataset.PatientName = 'MacDonald^George'
    print(dataset)


import micropip
micropip.install('pydicom').then(something_awesome)
`

    languagePluginLoader.then(() => {
      return pyodide.loadPackage(['micropip'])
    }).then(() => {
      console.log(pyodide.runPython(pythonCode));
    })
  </script>

</head>

<body></body>

</html>
```

**Comment by Centrus007** [comment]
Awesome!!

How do you envisage interfacing with the client's file system? Will uppy work for that? Or is that intended for server-side processing?

**Comment by SimonBiggs** [comment]
I believe uppy is for server. But a search for "REACT drag and drop file upload" will give widgets that can be used that don't need a server.

**Comment by SimonBiggs** [comment]
Now at https://app.pymedphys.com
