### ISSUE TITLE
Brain storming for app interface

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#306]
There will be quite a few cases where we will want to select a set of files, then apply an operation to them all, then download a zip of the output.

We can have a united interface that achieves all of these use cases. Essentially a file upload area, which displays all the files currently within a working directory, and then a file download area which displays the output directory.

Then we have a range of options which essentially process the data in the input directory, drop it in the output directory. There could be a drop down selection where you select what operation you want to do, then press process.

Then there is a final button that allows one to zip up the output directory and download it.

There will also be buttons for "clear input directory", "clear output directory", etc.

Note that uses of "upload" and "download" aren't truely either, but for want of a better word they suffice.

Provide a status prompt detailing progress of any downloading of python files, and also progress of any python processing.

Also provide a box where code can be written that will then be used to process the files in one box and then output them in the other. Potentially selecting options from the dropdown may simply fill this code box with the required processing code.

Creating a new processing type for the all would be as simple as creating a new pieces of processing code and adding it to the list of options.

**Comment by SimonBiggs** [comment]
Have the interface look a little like the following:

https://dribbble.com/shots/4151689-Planning-and-Simulation/attachments/949520

Here are some other ideas also:

https://dribbble.com/shots/3647198-Sidebar/attachments/814810

**Comment by SimonBiggs** [comment]
I also like this navbar design:

https://dribbble.com/shots/2467615-Trader-Oversight-Dossier/attachments/482179

**Comment by SimonBiggs** [comment]
Some other examples:

https://dribbble.com/shots/1274730-Live-Graph/attachments/175633

**Comment by Centrus007** [comment]
All sounds great to me!

**Comment by SimonBiggs** [comment]
> All sounds great to me!

Awesome :)

**Comment by SimonBiggs** [comment]
* Make the processing code be within a promise so that the interface doesn't freeze up while processing.
* Make a file viewer widget that can read dicom headers, csv files, plain text, image files.
* Make double clicking on a file cause a preview of that file to open up in the file viewer
* Make the processing code pull from a code cell on the page so that users can customise the processing
* Provide a range of processing options, trf2csv, trf2dcm, dcm anonymise, images plus CSV template to WL results.
* Forward python error messages to a console on the screen.

**Comment by SimonBiggs** [comment]
Use the react Monaco editor for code editing:

https://github.com/react-monaco-editor/react-monaco-editor

Potentially might be able to hook it into pyodide for syntax highlighting and code completion.

**Comment by SimonBiggs** [comment]
Create a BehaviourSubject, isPythonRunning, ... Need more thought how to actually make it though ...

**Comment by Centrus007** [comment]
Look at you embracing app creation! :p

**Comment by SimonBiggs** [comment]
Make a Logging observable, which allows python code to provide process updates to the user.

**Comment by SimonBiggs** [comment]
Use web workers to make code not interrupt UI
Improve development flow by mounting local disk within emscripten during development

**Comment by SimonBiggs** [comment]
Closing this for now.
