### ISSUE TITLE
VSCode environment fix

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#311]
Heya @Centrus007, would something like the following within your user settings instead of repository settings help solve some of your issues?

![image](https://user-images.githubusercontent.com/6559099/58057649-f8c6a180-7ba8-11e9-9c6c-360f2c4c7657.png)

**Comment by Centrus007** [comment]
I don't think so, but I will try :)

That said, I still think it's better to install security-related packages - like `nbstripout` - in `base`. I just think security features are better off permanently in PATH, rather than temporarily so during env activation (and relying on said env activation)...

**Comment by SimonBiggs** [comment]
Makes sense
