### ISSUE TITLE
Add anonymise DICOM to the web application

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#312]
Heya @Centrus007,

When you get a chance, could you add anonymise DICOM to the web app (https://app.pymedphys.com).

It should be as simple as replacing the code within here:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/app/src/python/user-scripts/anonymise-dicom.py#L1-L10

and then uncommenting the following lines:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/app/src/python/user-scripts/options.tsx#L25-L28

Feel free to also change the order of the options in there. I think anonymise DICOM could be close to the top in demand.

I have also included the pymedphys standard library within the webapp, so let's instead import from that (as long as the pymedphys module used depends only on subpackages that are included.)

**Comment by SimonBiggs** [comment]
For an example see:

https://github.com/pymedphys/pymedphys/blob/74511ab0f1ea1e8c186ac987912961ef023e0cd5/app/src/python/user-scripts/trf2csv.py#L1-L3

Which points to the following file within pymedphys:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/packages/pymedphys/src/pymedphys/trf.py#L1-L5

Notice, I had to remove the import from `pymedphys_logfiles`, this is because that subpackage isn't available within the webapp.

Here is the list of packages that are included within the webapp:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/packages/pymedphys_monomanage/src/pymedphys_monomanage/app/wheels.py#L34-L36

Here is where pyodide dependencies are loaded up:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/app/src/python/init.tsx#L32-L44

And here are the dependencies loaded up from pypi:

**Comment by SimonBiggs** [comment]
Here is the code actually being run by the trf2csv option:

https://github.com/pymedphys/pymedphys/blob/7accfeacb9d82ad10ac9b8a6bc6fc5d138526546/packages/pymedphys_fileformats/src/pymedphys_fileformats/trf/trf2csv.py#L37-L51

**Comment by SimonBiggs** [comment]
By the way, for the time being, you need to press `Ctrl + F5` to force reload the app. The plan is to provide a prompt to the user when a new version is available, and have the new version download in the background.

**Comment by Centrus007** [comment]
How do I spin up the app locally?

**Comment by SimonBiggs** [comment]
Do the following, except instead of `yarn build` run `yarn start`:

https://github.com/pymedphys/pymedphys/blob/d74ce24e5ccbf855e1c3810d3b0f4ffe52fc6df9/scripts/netlify.py#L11-L14

**Comment by SimonBiggs** [comment]
Something like:

```
cd path/to/root/git/repo
yarn bootstrap
yarn app:wheels
cd app
yarn
yarn build
```

Should work a treat...

**Comment by SimonBiggs** [comment]
:)
