### ISSUE TITLE
Make recommended installation be pypi

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#324]
Change to three OS specific instructions. For windows, install shapely with conda from conda-forge (but not set to a default channel)
For Mac, copy what is in the Azure Pipeline
For Linux no conda needed.

No longer mention installation of pymedphys via conda.

One day, if we have a fully automated pypi + conda-forge deploy pipeline, we can bring back conda-forge installation. But in reality, I am coming to prefer using conda only when absolutely necessary (shapely for example), and leaving the rest to pip.

**Comment by Centrus007** [comment]
Could abandon `conda` completely and install shapely direct from a wheel (from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)?

Probably even less clean overall.

**Comment by SimonBiggs** [comment]
That's true... Maybe a better option would be to investigate helping
upstream. As in, we could talk to the shapely developers, help them set up
Azure pipelines, which can be used to build a wheel on Windows, then have
that auto upload on releases...

Either that or we have a "pymedphys_shapely" package where we build the
wheel ourself...

**Comment by SimonBiggs** [comment]
Yup, I think we should be looking to ditch conda:

https://mail.python.org/pipermail/python-dev/2019-May/157586.html

**Comment by SimonBiggs** [comment]
It's alright. I got conda-forge working, and we can make conda-forge releases easier by managing our deployment through CI. Have CI listen for a GitHub release, and have that trigger pypi and conda-forge.
