### ISSUE TITLE
Distributed Monte Carlo for training an AI dose calculation algorithm

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#326]
* Compile EGSnrc to web assembly.
* Create an app that exposes a customised limited API to the EGSnrc interface. It will likely consist of a:
  * phase space file, a 
  * raw electron density grid (another function could take a CT data set + CT2ED to output the raw ED grid), a 
  * DeliveryData object, and 
  * MLC + Jaw modelling parameters.
* The EGSnrc API will produce two results, an AI result (quite fast) and an EGSnrc result (exceptionally slow)
  * Initially the AI result won't be very accurate
  * When deviations between AI and EGSnrc are found, report the case to the server
* Have a toggle that says something like:
  * Allow this application to run EGSnrc simulations in the background for the purpose of improving the AI dose calculation algorithm you're using within this application.
  * Toggle it off to stop the distributed calcs on that PC.
  * Present a leader board of users (signed in with GitHub account) of those who in the past day, week, month, and all time, have contributed the most CPU cycles to training the AI
* Have an AI begin training on the Monte Carlo data
* Focus on the kinds of requests that are being sent to EGSnrc via the API, make sure the AI is good at those kinds of dose calcs first.
* Have the AI provide feedback on where the model needs more data as well as accepted deviation records from users when they are running their own calcs
* Use the distributed learning platform to focus on areas where the AI declares it needs more data.
* Be exceptionally transparent whenever a user's CPU cycles are being used to train the AI with Monte Carlo results.
* Be exceptionally transparent whenever data is to be sent to the server (CT data, AI dose, EGSnrc dose, and phase space files)
  * Only send raw pixel values, no DICOM files with their headers.
  * Provide a prompt the first time when this is happening, let the user cancel it before it happens...
  * Get achievements that are displayed on the leaderboard for finding areas of large deviation and submitting the data.

**Comment by Centrus007** [comment]
This is a pretty darn good idea (if you can get user engagement)!
