### ISSUE TITLE
integrate-profile-class

### ISSUE THREAD

**Issue by kingrpaul** [pymedphys/pymedphys#33]
Integrate the resample function into the DoseProfile class as a method. It got smaller. 

Also, allow for list-of-tuples to be supplied to DoseProfile's __init__. Also, allow for metadata to describe the profile, leaving these values undefined, for now, to allow them to be dumped-in by read-profiler, etc. 

Still need to migrate to GitHub on W7.
* [x]  Migrate to GitHub W10
* [x]  Migrate to GitHub Lin
```shell
git remote -v
git remote set-url origin git@github.com:pymedphys/pymedphys.git
git remote -v
```

* [x]  Find/fix what is broken in pipeline
* [x]  Finished docstring
* [x]  separate segment(begin,end) from resample()
* [x]  add metadata={} as an argument
* [x]  add .from_tuples() as a method
* [x]  cleanup init()
* [x]  Undo WIP from merge request

**Comment by SimonBiggs** [comment]
Hi @kingrpaul,

How has the migrations gone? Had any issues?

**Comment by kingrpaul** [comment]
I had a little difficulty on Ubuntu and ended up doing a copy-paste of a last good version from GitLab. Not a big deal. Needed to re-learn how to setup the SSH keys, which I remember now. Short answer is, pretty well, I think. Thanks for checking up on me. Still need to get familiar with where things are in the new environment. 

I think this branch is ready for review / merge to master, @SimonBiggs. Going to find where to make the merge request.

**Comment by kingrpaul** [comment]
Closing. Superceded by : https://github.com/pymedphys/pymedphys/pull/97
