### ISSUE TITLE
Need to make dependency graphing handle top_level import

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#341]
Currently `from pymedphys_deliverydata import DeliveryData` is not able to be supported. This is due to a current limitation in the dependency graphing.

**Comment by Centrus007** [comment]
Should we not include this in the existing merge request?

**Comment by SimonBiggs** [comment]
Too complicated to solve it quickly. I just removed the top level import.

**Comment by SimonBiggs** [comment]
One can still run

```python
from pymedphys.deliverydata import DeliveryData
```

So not much is lost for the time being.

**Comment by SimonBiggs** [comment]
I think go ahead with the merge of that pull request once you're happy with it.
