### ISSUE TITLE
Build objects up depending on which packages are available

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#354]
So, I would like the MOSAIQ packages to also be accessible from the DeliveryData object. But I don't want the DeliveryData object to require `pymedphys_databases`, it won't work within Pyodide then...

Here is what I propose. We refactor deliverydata package to be entirely object oriented (as you have been asking for), but we don't implement any of the "to" or "from" methods.

Instead, each package inherits from the base delivery data object and adds on its own respective "tos" and "froms". Then we have a top level package called pymedphys_mixins or something of the like. It then has a "try: import; except ImportError: pass;" for every package that implements a to and a from DeliveryData. It then creates a "mixed in" DeliveryData object which contains all the "to" and "froms" that are currently available with the packages that are currently installed.

pymedphys then imports from that. That way, the pyodide app can still run `from pymedphys import DeliveryData` and that object will just have a subset of the methods available. But if the user on their machine runs it, it will have all methods. Same API...

@Centrus007 What do you think?

**Comment by Centrus007** [comment]
If I'm understanding correctly, I think that's a neat solution :)

**Comment by SimonBiggs** [comment]
Thanks @Centrus007 the heart of this is what was undergone within https://github.com/pymedphys/pymedphys/pull/355

I decided against a mixin package, just did that within pymedphys root instead.
