### ISSUE TITLE
Update pymedphys to 0.8.2 on conda-forge

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#369]
Once the subpackages are released:

https://github.com/conda-forge/staged-recipes/pull/8480

Then we can release the top level API package:

https://github.com/conda-forge/pymedphys-feedstock/pull/15

**Comment by Centrus007** [comment]
I'd like to go through this one day :)

**Comment by SimonBiggs** [comment]
Yup certainly

**Comment by SimonBiggs** [comment]
Done. Also, @Centrus007 this message here is for you:

https://github.com/conda-forge/pymedphys-feedstock/commit/91479a3671995f87e81665d5bd6eadfc1a852441#commitcomment-33822003
