### ISSUE TITLE
A brief layman's description of what the App is doing

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#374]
@PythonLinks

So as not to clutter the pyodide issues list I'll answer your question here.

Firstly the app is built so that any function within the PyMedPhys repo can be spun off into a script within the App. Essentially any tool within PyMedPhys that follows the "input file(s)" --> "process" --> "output file(s)" model can be included as a script on that site as it is currently designed.

With respect to what I am presenting in Montreal, in Radiation Oncology Medical Physics we use Linear accelerators to treat patients with cancer. These Linear accelerators produce logging information detailing important details of how each treatment went. This tool takes that logging information and provides a way for the user to verify that the parameters reported within the files were within clinically relevant tolerances.

**Comment by SimonBiggs** [comment]
Feel free to ask further if I used too much lingo...

**Comment by PythonLinks** [comment]
Okay, I updated the webpage.

So what about all of  the other PyMedPysics applications?

What does that mailing list say about this stuff?

Does anyone else want to copy what you are doing?

Warm Regards
Christopher Lozinski

https://PythonLinks.info
tel: +48 12 361 3136
Skype: clozinski

**Comment by SimonBiggs** [comment]
Which mailing list are you referring to? I haven't posted it on any mailing list yet.

**Comment by PythonLinks** [comment]
Well I  think that your use case of medical analyses is hugely interesting to the market. 


So there must be a whole bunch of  PyMedPysics developers who would be interested in this stuff. 

Which is why I asked if you have posted to the  PyMedPysics mailing list.  Is there one?


Warm Regards
Christopher Lozinski

https://PythonLinks.info
tel: +48 12 361 3136
Skype: clozinski

**Comment by SimonBiggs** [comment]
People are certainly interested. It's early days however. We'll see how things go in the months following the conference.

**Comment by SimonBiggs** [comment]
I'm also playing it a little slow. No need to rush this one out the gate. People who find it through GitHub/word of mouth are usually a little more forgiving of the whole app freezing.

... I'd like to give it quite a bit more polish before I present it to the greater audience of my peers.
