### ISSUE TITLE
DICOM object brain storming

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#375]
@Centrus007 would you be open to building our own DICOM representation, heavily based upon pydicom dataset, and directly mappable to and from the dataset, with significant reuse. But instead build the object to be immutable, based off of tuples/named tuples much like the Delivery object.

Why would we want to build such a monstrosity you ask?

Function and method caching. (As well as other immutability benefits).

If the DICOM object is immutable then it can be used within an LRU Cache. That way repeated method calls are not rerun, instead they are just the cost of looking up a cached result within a dictionary. This means we can have complicated functions as properties, users are then free to access these properties with an understanding they'll only have to pay the cost for them once.

Also new objects that build on old objects wouldn't have to create copies, instead they would create the new object mostly consisting of pointers to the old object, with just the new part changed. Due to its immutability this would still be guaranteed to not result in complicated consequences for ourselves and our users.

So, I propose we create a base DICOM object that inherits from tuple. We would then need to call pydicom's code that reads dicom files and see if we can directly convert from file into the immutable format using pydicom's file reader code. We would also have a to and from pydicom dataset of course.

Another method I can think of is something like "fill" which will populate all DICOM fields with relevant data that are required to make the file DICOM compliant.

Anyway. Keen for your thoughts @Centrus007

**Comment by Centrus007** [comment]
I'm open to it. Given that we haven't really embraced our existing objects, now would seem the time to do it. Are you quite sure of those benefits though? For example:

> Also new objects that build on old objects wouldn't have to create copies, instead they would create a the new object mostly consisting of pointers to the old object, with just the new part changed.

Are you sure about this? Can you demonstrate with a simple example? My major issue with immutable objects was the need for copying, which is a big downside for batched tasks.

> Another method I can think of is sonething like `fill` which will populate all DICOM fields with relevant data that are required to make the file DICOM compliant.

I've been thinking along the same lines, given #372

**Comment by SimonBiggs** [comment]
```python
In [3]: tuple((tuple((1,2,3)),tuple((4,5,6))))
Out[3]: ((1, 2, 3), (4, 5, 6))

In [4]: a = tuple((tuple((1,2,3)),tuple((4,5,6))))

In [5]: b = tuple((a[0], a[0], a[0]))

In [6]: b[2] is a[0]
Out[6]: True

In [7]: id(b[2])
Out[7]: 1825505966624

In [8]: id(a[0])
Out[8]: 1825505966624
```

**Comment by SimonBiggs** [comment]
If we're going to default to `deepcopy` usage, using tuples instead is going to be orders of magnitude faster.

**Comment by SimonBiggs** [comment]
https://docs.python.org/3/library/functions.html#id

`id(object)`
Return the “identity” of an object. This is an integer which is guaranteed to be unique and constant for this object during its lifetime. Two objects with non-overlapping lifetimes may have the same `id()` value.

**CPython implementation detail: This is the address of the object in memory.**

**Comment by Centrus007** [comment]
I'm aware of `id()` :)

Cool! But does that hold when you *edit* `a[0]`? *That's* the use case I'm worried about...

**Comment by Centrus007** [comment]
I see now. So if you wanted to "edit" a DICOM object, you would create a new object and populate all unchanged fields with (kinda) pointers to the old object's values and provide a custom new value for the changed value?

**Comment by Centrus007** [comment]
I'm just a little worried about unintended consequences here. It seems convoluted. Maybe it'll become clearer as we try it :)

**Comment by SimonBiggs** [comment]
Yeah ... We'll have to see ... Uncharted territory for me...

**Comment by SimonBiggs** [comment]
Parse the DICOM standards XML files to produce a DICOM spec file which defines what parameters are allowed where under what conditions. Have a class of DICOM object which is guaranteed to be DICOM standards compliant. Have another class which is very flexible and anything goes.

Returns of "fill classes" is the object DICOM type that is standards compliant and named according to the DICOM type.

**Comment by SimonBiggs** [comment]
https://www.dicomstandard.org/current/

**Comment by SimonBiggs** [comment]
Generate the UID last, have the UID be based upon the hash of the object contents. That way a DICOM file that has exactly the same contents will always produce the same UID.

**Comment by SimonBiggs** [comment]
With the copy question... There is an option to go "half/half" as in, make as much of the object immutable as is reasonable and define a __copy__ method.

Not sure if I like that approach though... Just thought I'd flag it as an option.

https://github.com/python/cpython/blob/c879ff247ae1b67a790ff98d2d59145302cd4e4e/Lib/copy.py#L82

**Comment by SimonBiggs** [comment]
Also, of an object truely is immutable, even a copy of it is defined as the same object:

https://github.com/python/cpython/blob/c879ff247ae1b67a790ff98d2d59145302cd4e4e/Lib/copy.py#L108

**Comment by SimonBiggs** [comment]
So, how to solve this appears to have come clear. As a first step we create a `FreezeableDataset` and then we compose that object into our `DicomBase`.

`FreezableDataset` inherits from `pydicom.Dataset` with one additional method `freeze`. The freeze method will inplace convert the object into being logically immutable. It will do this by recursively overriding the set and delete attributes of the object and each nested object contained within it with a method that raises a `FrozenAttributeError`. Base this upon https://github.com/python/cpython/blob/master/Lib/dataclasses.py#L539. Consider also creating a `__slots__` and `__copy__` function. Concepts surrounding immutable objects in Python are given at https://stackoverflow.com/questions/4828080/how-to-make-an-immutable-object-in-python. I suspect a good way to achieve this freezabity is to create a variable `self._frozen` that defaults to false, and the `self.freeze()` method simply sets this variable to true. Then, have the created classes call the original set or delete methods if frozen is false, but have them return the frozen attribute error if frozen is true.

Then in our `DicomBase` our `self._dataset` object will be one of these frozen datasets. On initiation a hash function of the dataset contents will be undergone, and this will be used to create the UID. The hash function needs to be a deterministic function that equally likely creates an integer evenly spread over the space of 10^37. This number is then converted to string and appended to the PyMedPhys UID origin. Before converting to string it is also saved as a long int within `__hash`. Once the UID is defined call `self._dataset.freeze()`.

The hash function could be based on the following:
https://github.com/MagicStack/immutables/blob/master/immutables/map.py#L590

If using the above, need to find an efficient way to extend the space to 10^37 instead of being limited by 32 or 64 bit. I imagine adding a salt and repeating the process until the right amount of entropy is found would be a viable option.

Our own object can then define __eq__ by just doing an int compare of the objects `__long_hash` parameter. The __hash__ function can return a 64bit or 32bit integer (depending on system size) truncated based off of `__long_hash` and saved into `__hash`. Create set and delete functions which return new objects, create this similar to https://github.com/MagicStack/immutables/blob/master/immutables/map.py#L539. the majority of the contents of the new object can just be pointers to the old object because they will be immutable. This pointer object copy will need to be implemented. Potentially the best method will be to recursively override `__copy__` to just return a pointer instead of a new object when the dataset is frozen.

**Comment by SimonBiggs** [comment]
Was thinking about this on the plane. I think a monkey patching function would be better. Essentially a function that monkey patches the class instance and subinstances. ...not sure. Further thought.

**Comment by SimonBiggs** [comment]
@darcymason there is a new pep landing:

https://www.python.org/dev/peps/pep-0603/

Being able to use an lru_cache with DICOM datasets would be amazing. To do this we would need a FrozenDataset class. I am thinking the best home for this class would be within pydicom itself. Would you be open to me making a PR and having us iterate on the concept once PEP 603 lands?

**Comment by darcymason** [comment]
> I am thinking the best home for this class would be within `pydicom` itself.

I'm open to that idea.  I'm not sure exactly what it would entail, or if/how much it would complicate existing code.  I imagine as a derived class it would either have to override anything where items were set, or as a wrapper, it would have to wrap all 'get' calls.  Without a lot of thought, I guess that could be done with minimal change to the existing Dataset code.

> Would you be open to me making a PR and having us iterate on the concept once PEP 603 lands (Python 3.9, about a year from now)?

Are you saying the PR would come around the time of Python 3.9?  If so, then yes.  If a lot sooner ... I'd rather not have the code carried along in pydicom through possibly multiple releases before it could be used by end-users (with a known final `frozenmap` API, as opposed to any code that might be copied in to work with).

As I think about this a bit, there might be a lot to it - IIUC, Sequences would also have to be frozen as a tuple (`FrozenSequence`?).  Then with the nesting of datasets inside them, there's a recursive freeze to do.  But hey, but if you want to tackle it...  ;-)

**Comment by SimonBiggs** [comment]
Yeah, in pydicom no sooner than Python 3.9. In PyMedPhys sooner than that potentially via vendoring in future stdlib code.
