### ISSUE TITLE
Daily backups for TRF log files?

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#383]
The following question came via email:

> I’m curious if you were able to get the SDD backups to run at a daily frequency? Our Elekta service engineer said that the highest frequency was weekly. But I thought I recalled hearing that other centres were able to do it daily … perhaps I’m wrong, though!

**Comment by SimonBiggs** [comment]
We have not been able to get the diagnostics backup to run daily, no. It is unfortunate. We see three options going forward which would be appreciate paths to take:

* Also set up iCOM logging, it has 4 Hz resolution, but it can be run live. Use iCOM for immediate results, and use TRF for high time resolution results
* Ask those in charge of shutting down the machine to run the backups manually daily
* Be content with weekly, on an as needs basis trigger a manual backup

**Comment by chop-shape** [comment]
Hi, Simon. I can not find the trf files in the SDD backups.  Do you know why?

![integrity](https://user-images.githubusercontent.com/47208071/97650916-c99eaa00-1a95-11eb-85c8-3497518a7743.JPG)
![SDD](https://user-images.githubusercontent.com/47208071/97650923-cc999a80-1a95-11eb-9481-6b640f096c4e.JPG)

**Comment by SimonBiggs** [comment]
Hi @chop-shape,

That is intriguing. I don't know why. Do you have an Agility MLC?

**Comment by SimonBiggs** [comment]
Also, it is likely better creating a dedicated issue for your question. As this question isn't so much about "unable to find TRF files within diagnostic backup".

It's important for me that other users can easily find answers to their questions with a Google search. By making issues appropriately it builds up a repository of troubleshooting information.

Would you be able to create a new issue and repeat your question?

**Comment by chop-shape** [comment]
ok. I'll create this issue.
