### ISSUE TITLE
Yarn tree

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#390]
Heya @peterg1t,

What happens if you run the following:

```
python -c "from pymedphys_monomanage import tree; tree.build_tree('packages')"
```

Also what about the following:

```
which python
```

**Comment by SimonBiggs** [comment]
Run those commands within the top level directory of pymedphys.

**Comment by peterg1t** [comment]
![image](https://user-images.githubusercontent.com/8771255/59153785-eb6e3b80-8a1f-11e9-925c-7377d8096951.png)

![image](https://user-images.githubusercontent.com/8771255/59153798-23757e80-8a20-11e9-9ab6-6e518817048d.png)

**Comment by SimonBiggs** [comment]
Yeah, really best not to use the system Python for any of this.

Can you manage an independent version of Python 3.7 with either pyenv (
https://github.com/pyenv/pyenv) or miniconda (
https://docs.conda.io/en/latest/miniconda.html)?

It does look like you've potentially mapped python to python3 via an alias,
having it happen via an exported addition to the PATH variable would likely
be more robust. When you call yarn it uses a subshell, so unless the path
variable is exported it won't be used, yarn likely also isn't running your
bashrc or equivalent so your alias likely isn't being recognised.

But all that complication is removed if you just use a userspace
installation of python with miniconda or pyenv.

Cheers,
Simon

**Comment by peterg1t** [comment]
![image](https://user-images.githubusercontent.com/8771255/59223191-8c780600-8b88-11e9-861c-b1e79d570992.png)

Hi Simon,
I installed pyenv and setup python 3.7.3 as my global as you can see in the image. I then ran yarn tree, but I'm still getting this error.

Cheers
Pedro

**Comment by SimonBiggs** [comment]
You would have needed to rerun `yarn bootstrap` with the new Python install.

**Comment by peterg1t** [comment]
![image](https://user-images.githubusercontent.com/8771255/59232053-24351e80-8ba0-11e9-8378-8d63d0e8a1f1.png)

Ok. Now I got a bit of a different error. I feel we are getting closer.

**Comment by SimonBiggs** [comment]
Always do like to say "new error is a good error" because it (usually) means you fixed the first error.

From that error message it really does look like however your system is set up it is stuck thinking it should be using Python 2. Also, did that error occurred when running `yarn bootstrap`?

**Comment by peterg1t** [comment]
Hi Simon,
Yes that happens when I run yarn bootstrap. I think every Linux distro comes with python 2.7 installed for other software that depend on it. So I don't think I can get rid of it totally. I have pyenv set to 3.7.3 but it seems that doesn't do the trick. Do you have python 2.7 on your system co-existing with 3.7? What distro are you running? I'm willing to install Ubuntu or something different instead of my current Fedora. I could also try to setup yarn in a windows machine I have at home.
Cheers
Pedro

**Comment by SimonBiggs** [comment]
I personally use Ubuntu and solve all the path issues with miniconda.

**Comment by SimonBiggs** [comment]
Also, as a rule, I never use Sudo for anything Python. That helps guarantee
I'm not installing anything with the system Python.

**Comment by peterg1t** [comment]
I'll give miniconda a try!

**Comment by SimonBiggs** [comment]
Also :) I'm in you time zone (at least closeish).

Just landed in San Fransisco, on route to Toronto :).

**Comment by peterg1t** [comment]
That's right the conference, nice! Next time book through Calgary so we can take a trip to the Rockies. Although the Great Lakes in Toronto are probably supernice this time of the year over there :) Believe it or not I've never been in Toronto/Montreal in the summer.

On other bad news I installed conda and got the same error with python 3.7.3 

![image](https://user-images.githubusercontent.com/8771255/59458046-e0782a00-8dd6-11e9-8c77-ec1fa89b467d.png)

At this point maybe a fresh Ubuntu installation might do the trick. I've been working on some updates to the qc-jaws I'll make another branch soon.

**Comment by SimonBiggs** [comment]
Can you run that again without using the root user?

**Comment by SimonBiggs** [comment]
That does sound like a good idea re: Calgary :)

**Comment by peterg1t** [comment]
This is why I was running it with sudo. I got an access error...

![image](https://user-images.githubusercontent.com/8771255/59459786-e5d77380-8dda-11e9-9ca1-2f054bef1181.png)

**Comment by SimonBiggs** [comment]
I think that error has occured because of a previous sudo usage causing
some files within your home repo to be assigned to the root user. I highly
recommend you do a recursive chown of all files within the pymedphys repo
to peter:peter.

Then try again without sudo, see how that goes...

**Comment by peterg1t** [comment]
![image](https://user-images.githubusercontent.com/8771255/59464600-24bef680-8de6-11e9-81cd-08ed424548d7.png)

Success!

**Comment by peterg1t** [comment]
Although yarn tree still gives me an error.
![image](https://user-images.githubusercontent.com/8771255/59465002-22a96780-8de7-11e9-8e21-8584e98e80b3.png)

**Comment by SimonBiggs** [comment]
> ![image](https://user-images.githubusercontent.com/8771255/59464600-24bef680-8de6-11e9-81cd-08ed424548d7.png)
> 
> Success!

Woo hoo :) so what fixed it in the end?

**Comment by SimonBiggs** [comment]
With the yarn tree, what if you straight up just run the python command (instead of the yarn shortcut)? (Starts with python -c, written in your image there)

**Comment by peterg1t** [comment]
Done all runs now. I did some tiding up of the python environment. Uninstalld every package I had removed pyenv and installed miniconda. yarn tree also works fine now. :) Now  can get back to coding ha,ha

**Comment by SimonBiggs** [comment]
> Done all runs now. I did some tiding up of the python environment. Uninstalld every package I had removed pyenv and installed miniconda. yarn tree also works fine now. :) Now can get back to coding ha,ha

Great to hear! :) What would be your main advice for others in the future with the same issues?

**Comment by peterg1t** [comment]
Well, every developer sets up their system to what works for them or whatever is easier. I have always used the default python environment and never installed anything else. I always try to keep it as light as possible. Using miniConda works great but now I have other minor issues to deal with regarding matplotlib. It is not ideal but I can work very easily around those. Advice.? Don't be a purist and use what is proven :)
