### ISSUE TITLE
Adding EGSnrc-related utilities

### ISSUE THREAD

**Issue by mchamberland** [pymedphys/pymedphys#400]
This one is much easier. I have something called [egs_tools](https://bitbucket.org/marcchamberland/egs_tools/src/master/). It would be neat to include some of them in the web app so it's easier for people to run. Perhaps we can also fold the entirety of egs_tools into PyMedPhys? I'm very open to it if it means it can reach a wider audience and more eyes can look at it and help me improve it.

**Comment by mchamberland** [comment]
To get things started, I'd like to focus on the [convert_ct_to_egsphant.py](https://bitbucket.org/marcchamberland/egs_tools/src/master/scripts/convert_ct_to_egsphant.py) utility first.

**Comment by SimonBiggs** [comment]
Yup, sounds awesome. Did you want to begin the pull request?

**Comment by mchamberland** [comment]
Couple of questions: where should all those files go in PyMedPhys? The script depends on a bunch of other files (all of the ct_tools folder, the dicom folder, voxelnav.py, etc.).

Also, it uses an argument parser. How would a user enter those?

**Comment by SimonBiggs** [comment]
Initially, make a directory under labs. Let's put it in there initially.

**Comment by SimonBiggs** [comment]
Once we move modules out of the labs into the library, I can point you to
some CLI / argparse examples.

**Comment by mchamberland** [comment]
Sounds good.
