### ISSUE TITLE
Adopt the Google Python style guide

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#404]
https://google.github.io/styleguide/pyguide.html

We should consider adopting the Google Python style guide.

**Comment by SimonBiggs** [comment]
Swap to using https://pypi.org/project/yapf/

**Comment by SimonBiggs** [comment]
I'll have to no longer use nested lost comprehensions...

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, does this still apply?

**Comment by SimonBiggs** [comment]
Yes, big parts of it certainly does. Especially the "nested list comprehensions" points. The Pythonic / Non-Pythonic parts of it instead of the strict style.

I guess, black will now make it so that we never need to focus on the "bouncing ball", instead we can tackle the P/NP problem (see http://youtube.com/watch?v=wf-BqAjZb8M)

**Comment by SimonBiggs** [comment]
Concepts such as avoid using `from pymedphys import ...` and instead always do:

```python
import pymedphys

pymedphys.Delivery ...

```

There are loads of readability points in the Google Python style guide which still apply. I am slowly adopting these. It will be easier once we undergo the API rework.
