### ISSUE TITLE
Trial creating a web app for gamma

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#41]
There is a way to store a dicom file along with its header just within browser memory and not have it send to a webserver. The image data itself could then be sent to the webserver for gamma analysis, and potentially I could do the sending in quite a clever way.

I can get the users to pick the images first, initially I'll just support dicom files, I'll ask the users to pick the evaluation image first, then they can pick the reference image. The benefit of this, is that evaluation image can be uploading while they are selecting the reference image, and initally an interpolation function of that evaluation image can be made.

Although computationally it will take a bit longer I'll set it to calculate a range of gamma dose and distance threshold values automatically. I'll also get it to calculate both local and global gamma. That way the calculation can begin the moment user's evaluation file is uploaded and the first few voxels of the reference image are uploaded.

Pre shuffle the reference image using JavaScript on the client side and send the reference image in batches. Run gamma calculation in batches that way as soon as the first small portion of the reference image has uploaded the calculation can begin while the remaining upload continues.

At this point in the user interface the user still needs to select a distance and dose threshold value from a dropdown as well as lower dose cut off and local or global gamma. At this point hopefully the server will actually be already calculating gamma for all of these options at once in an efficient manner, so once these options are chosen the gamma histogram, as well as 3D gamma distribution, 3D dose distributions, and a profile tool, are all able to appear. Selecting different options from the drop down should have immediate impact because the results from each of the gamma options are being sent to the user and stored in the webbrowser's ram.

The 3D gamma distribution will look speckly at first because only a random subset will be calculated thus far, but as time goes on the speckliness will fill in. The histogram will also live update and the user should be able to see it, and the passing rate begin to stabilise relatively quickly.

The front end will be a firebase app written in Angular, bokehjs, as well as emscripted based dcmtk for reading dicom files locally within the browser and never having the header be sent to the server.

The backend will be a Python 3.7 Google app engine server running pymedphys.

Testing will be using protractor for end to end tests as well as the Angular recommended unit test framework.

**Comment by SimonBiggs** [comment]
Emscripted based client side dicom reading within a browser can be achieved with  https://github.com/commontk/dcmjs/blob/master/README.md

**Comment by SimonBiggs** [comment]
Honestly, thinking about this, I'd like to make a dual gamma learning tool / gamma dicom tool.

Have a web interface where users can pick from gamma filter, gamma no interpolation, gamma shell, gamma geometry. Have them be able to create a dose distribution and then apply adjustment either in the form of noise, or dosimetric or spatial shifts. Have the ability to change threshold values, local or global gamma.

Allow the creation of their own dummy dose distributions for learning purpose, or to provide DICOM dose files.

Could attach a DICOM plan file once to get a "machine specification", then just DICOM doses would need to be attached.

Have the whole thing be designed so that all computation is run client side with web assembly. So no data would leave the user's computer, except maybe usage statistics.

To do this I think I should rewrite the gamma calculation algorithms in the Rust language. That way the data never leaves the user's computer and it's all runnable without any installation from the web browser.

I envisage using Palantir's user interface library, blueprintjs. Using Dexiejs for browser state between tabs and instances. Using the typescript portion of the Bokeh plotting library.

Because this will be using quite a different build chain, initially I'll begin work on it in my own repo. Get it tidy, then we can work out how best to pull it in to pymedphys, if it should belong here.

**Comment by Centrus007** [comment]
Sounds like a worthwhile endeavour!

> Because this will be using quite a different build chain, initially I'll begin work on it in my own repo. Get it tidy, then we can work out how best to pull it in to pymedphys, if it should belong here.

I would also make a distinction between PyMedPhys, the "brannd" and `pymedphys`, the Github repo. The branch already has scope beyond the repo in the form of large file storage (Zenodo). Arguable our distribution channels (PyPi and conda) and documentation (ReadTheDocs), although directly informed by the repo, are logically separate entities in the broader PyMedPhys brand.

So even if this project doesn't make it into the PyMedPhys repo, if you'd like to, it could still present the PyMedPhys brand. That's completely up to you, but just a thought.

**Comment by SimonBiggs** [comment]
> So even if this project doesn't make it into the PyMedPhys repo, if you'd like to, it could still form part of the PyMedPhys brand. Practical links could be as simple as providing access to the gamma educational platform it through the PyMedPhys docs. It That's completely up to you, but just a thought.

There will certainly be a prominent link + logo of pymedphys redirecting people to pymedphys if they want a desktop version

**Comment by SimonBiggs** [comment]
The multiple gamma implementations should benefit from each other via cross testing. Rust can be compiled to native executables. I'll make sure from the get go I'll write the Rust implementations with test driven development, and then those implementations can be used to provide various baselines for any python implementations. There can be cross over of the testing suite.

But that will be for later.

**Comment by SimonBiggs** [comment]
Not implementing gamma with rust. Have a web app with pyodide at the moment. It is very rudimentary though. Will pick this back up if we decide to focus on app creation in the future.
