### ISSUE TITLE
Project ideas to work on during the development sprints at PyCon AU

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#413]
For those attending PyCon AU there would be great value in having a PyMedPhys focused development sprint. Please submit ideas here for what might be a great project to spend 2 days of focused time on from a team of Python programming Medical Physicists.

Whether or not a PyMedPhys focused team will be made during the PyCon AU sprints will depend on the interest garnered here.

**Comment by SimonBiggs** [comment]
@pchlap how interested in this might you be?

**Comment by SimonBiggs** [comment]
@Matthew-Jennings do you believe you might be able to get funding for another conference this year?

**Comment by pchlap** [comment]
> @pchlap how interested in this might you be?

Interested for sure, but I get back from Europe in the morning of Saturday the 3rd, so it could be tricky. I see the sprints are on the Monday and Tuesday following so if there is a group going hopefully I could manage to join for at least that :)
