### ISSUE TITLE
Coordinate conventions

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#431]
*Follow on from https://github.com/pymedphys/pymedphys/pull/427#discussion_r306166690*

Okay @SimonBiggs , let me have a go at thoroughly explaining it and maybe we can zero in on the best solution together:

Imagine we have a DICOM RT Dose file that we want to analyse. It has a 3-D `pixel_array` whose right/inf/post-most voxel's coordinates are `(x0, y0, z0)`, whose left/sup/ant-most voxel's coordinates are `(x1, y1, z1)` and whose resolutions along each axis are `x_step`, `y_step` and `z_step`).

The original (now deprecated) [`load_dose_from_dicom()`](https://github.com/pymedphys/pymedphys/blob/76d65aa40f60839e125df0b3c32c2bca8fedfbef/src/pymedphys/dicom/_level2/dicom_dose.py#L102) returns a tuple whose elements contain the range of `x`, `y` and `z` coordinates that apply to `pixel_array`. I.e. something like:

```python
xyz = tuple(
    np.arange(x0, x1 + x_step, x_step),
    np.arange(y0, y1 + y_step, y_step),
    np.arange(z0, z1 + z_step, z_step))
```

This was often called `(x, y, z)` when separated. Sometimes a reshaped version of it was called `coords`, e.g. in [`coords_and_dose_from_dicom()`](https://github.com/pymedphys/pymedphys/blob/76d65aa40f60839e125df0b3c32c2bca8fedfbef/src/pymedphys/dicom/_level2/dicom_dose.py#L443)

One problem with this tuple is that its elements are 1-D; their shapes don't correspond to the shape of `pixel_array`. Basically, it would often be nice to be able to index `x[a, b, c]` and have it correspond to `pixel_array[a, b, c]`. You can use a meshgrid to achieve this, and a [2-D version was actually done in `find_dose_within_structure()`](https://github.com/pymedphys/pymedphys/blob/76d65aa40f60839e125df0b3c32c2bca8fedfbef/src/pymedphys/dicom/_level2/dicom_dose.py#L568)

---

Then I came along. :D The things I wanted to address were that:
- `load_xyz_from_dicom()` didn't generalise to all patient orientations.
- `pixel_array` was reshaped in [`load_dose_from_dicom()`](https://github.com/pymedphys/pymedphys/blob/76d65aa40f60839e125df0b3c32c2bca8fedfbef/src/pymedphys/dicom/_level2/dicom_dose.py#L92), as was `coords` in [`coords_and_dose_from_dicom()`](https://github.com/pymedphys/pymedphys/blob/76d65aa40f60839e125df0b3c32c2bca8fedfbef/src/pymedphys/dicom/_level2/dicom_dose.py#L443), and I argued that a reshape wasn't necessary - and if ever needed, was best kept internal. My understanding of this has deepened, so wait until the end before worrying about this point.
- There was some confusion and possible inconsistency in use of coordinate systems: e.g. use of patient-based for `find_dose_within_structure()` and use of (kinda) IEC fixed in `extract_depth_dose()` without explicit explanation.

---

After several iterations, we have eventually arrived at:
-  `load_dose_from_dicom()` has been renamed to `dose_from_dataset()` and no longer reshapes `pixel_array` by default. This means that it retains an indexing order of `pixel_array[z_index, y_index, x_index]` (or, more palatably, `pixel_array[slice, row, column]`)
-  `load_xyz_from_dicom()` was replaced with [`xyz_axes_from_dataset()`](https://github.com/pymedphys/pymedphys/blob/c0484461e8ee731c8887798d2066086fd49269a8/packages/pymedphys_dicom/src/pymedphys_dicom/dicom/coords.py#L64). The differences being that:
  - I've tentatively tried to adopt the convention of called `xyz` a tuple of "axes" and avoiding "coords", which I *think* is better suited for the tuple of meshgrids.
  - It is now correct for all regular patient orientations.
- I added a so far unused function called [`coords_from_xyz_axes()`](https://github.com/pymedphys/pymedphys/blob/c0484461e8ee731c8887798d2066086fd49269a8/packages/pymedphys_dicom/src/pymedphys_dicom/dicom/coords.py#L31) that performs the meshgridding. An important point to notice is that the tuple called `coords` returned by this function is still in the intuitive *xyz* order, but each *tuple element* is indexed in zyx order to match `pixel_array`. I.e. coords[0] contains the meshgrid of x coordinates for `pixel_array`, BUT that meshgrid is indexed in zyx order. I.e. `coords[0][z_index, y_index, x_index]` corresponds to the x coordinate of `pixel_array[z_index, y_index, x_index]`. But perhaps a more palatable way to think about it is not that `x_p = coords[0][z_index, y_index, z_index]` but instead that `x_p = coords[0][slice, row, column]`. When stated this way, I'm relatively convinced this is the best solution to adopt. Actually, to be honest, the latter understanding is more correct, since for decubitis orientations, its order would instead be zxy, but still slice-row-column!

---

After some further thought, I do wonder whether we ought to now avoid the `xyz`/`axis` tuples entirely and to primarily just deal with coordinate meshgrids. I.e., combine `xyz_axes_from_dataset()` and `coords_from_xyz_axes()` into a new `coords_from_dataset()` and have it return a tuple of meshgrids. We can just slice the meshgrids if we ever need the old "axes". I think this is compatible with your new implementations of profile and depth dose extraction.

I never ever meant for either the axes *tuple* or the coords (meshgrids) *tuple* to be in `zyx` order, but rather that the x, y and z meshgrids themselves (tuple elements) ought to be *indexed* in that order. I think that has been a source of confusion, since I see that there is a `zyx_and_dose_from_dataset()` and that the  `interp_coords` parameter in your new `dicom_dose_interpolate()` expects zyx order. Unless there is another complication I'm missing, I don't think this is necessary - xyz order of tuple elements is fine!

Does that clear things up? What are your thoughts going forward?

**Comment by SimonBiggs** [comment]
> After some further thought, I do wonder whether we ought to now avoid the `xyz`/`axis` tuples entirely and to primarily just deal with coordinate meshgrids. I.e., combine `xyz_axes_from_dataset()` and `coords_from_xyz_axes()` into a new `coords_from_dataset()` and have it return a tuple of meshgrids. We can just slice the meshgrids if we ever need the old "axes". I think this is compatible with your new implementations of profile and depth dose extraction.

I do really like this. And I am certainly (very) partial to having a standard that we implement everywhere such as this.

> I never ever meant for either the axes _tuple_ or the coords (meshgrids) _tuple_ to be in `zyx` order, but rather that the x, y and z meshgrids themselves (tuple elements) ought to be _indexed_ in that order. I think that has been a source of confusion, since I see that there is a `zyx_and_dose_from_dataset()` and that the `interp_coords` parameter in your new `dicom_dose_interpolate()` expects zyx order. Unless there is another complication I'm missing, I don't think this is necessary - xyz order of tuple elements is fine!

I think you have pin-pointed the source of my confusion exactly.

-------

Now on this, I can't help but think this coordinate system issue that we are trying to address/standardise is exactly the use case that `xarray` was trying to make exceptionally transparent and explicit.

I really like the meshgrid idea and would be willing to standardise on it, but at this junction I think there is potentially a high pay off available at attempting to mimic this meshgrid functionality with `xarray` instead.

**Comment by SimonBiggs** [comment]
For example:

http://xarray.pydata.org/en/stable/generated/xarray.broadcast.html

With the note that broadcasting happens by default, but that is a good explanation of the effect.

**Comment by Matthew-Jennings** [comment]
Yep, ti does look good. Certainly worth giving a go!

**Comment by SimonBiggs** [comment]
An interesting coordinate transformation approach that allows the handling of a range of co-ordinate transformations:

Section 11.4 of the following -- http://aosabook.org/en/matplotlib.html

Worth studying that implementation...

**Comment by SimonBiggs** [comment]
Alright, better idea (I think). We create an object inherited from a namedtuple. The namedtuple is called DICOMPatientCoords or something like that. It has four inputs, x, y, z, and orientation.

In our object that we inherit of that we add methods hfs, ffs, etc which each return the current object converted into the new orientation assuming the points themselves are stationary relative to the IEC Fixed reference frame. It would also have a method called "fixed" which would also need an isocentre parameter that would then return a IECFixedCoords which has x, y, z, as well as CT isocentre (CT isocentre would need to be a DICOMPatientCoords object I think).

I also propose that we don't actually ever expose these objects. Instead we provide functions that use these objects internally only.

That way we can remove my z, y, x functions and swap them back to x, y, z, and then just internally call these coords objects to make them robust to different DICOM coord orientations.

**Comment by Matthew-Jennings** [comment]
I think that sounds logical, though I might need to dwell on it a bit more.

One thing has come to mind recently as I've coded away: in most situations, I actually prefer to work in fixed coordinates rather than patient coordinates. I think it's more natural to expect coordinates to be fixed relative to the machine (or Earth) and a little strange to rotate them as the patient is rotated. For example, when displaying a patient CT: if the patient is, say, FFP, I think I'd prefer to actually see a face down CT displayed. My mind naturally works in the fixed system.

Maybe that's just my own personal preference and isn't widely shared. What do you think?

If I'm right, maybe we just don't need to worry so much about this coordinate stuff and just routinely use `xyz_axes_from_dataset(ds, coord_system='FIXED')`.

Moreover, I think the only reason we're using this confusing "axes" construct is because RegularGridInterpolator's constructor takes it as a parameter. This is annoyingly inconsistent, to be honest, because it then takes proper coordinates as an input when called to interpolate. Unless there's a very good reason to keep `numba` off the cards as a dependency, I think we're much better suited to using [EconForge's `interpolation`](https://github.com/EconForge/interpolation.py) package. I've recently been using it for exactly our use case - 3D dose interpolation - and it performs beautifully at up to an order of magnitude faster than `RegularGridInterpolator`.

I think we're only after trilinear interpolation, which is very simple to code. We could actually write our own vectorised interpolator, employ `numba` and possibly find we even outperform EconForge.

**Comment by SimonBiggs** [comment]
I am very happy to have numba become a dependency. Also would be more than happy to swap out `RegularGridInterpolator` for an EconForge interpolation especially if you have found it works neatly.

Regarding fixed coords, I completely agree. My mind does not want its coordinate system rotating with either the patient or the gantry. If internally we can transform everything to fixed and then just have some tidy functions that convert to and from fixed when needed to support external formats that would be ideal for me.

**Comment by Matthew-Jennings** [comment]
It's better for another reason, actually.

When using a patient-based coordinate system, the `x`, `y` and `z` axes returned from `xyz_axes_from_dataset()` **do not necessarily correspond** to the indices 'i', 'j' and 'k' when accessing `pixel_data[k, j, i]`. They do for HFS and FFP, but not FFS and HFP ('y' and 'x' directions are flipped) and certainly not for any of the decubitis orientations, for which 'y' corresponds to 'i'. We've been lazy with this so far.

But working in a fixed system, the relationship between `xyz` axes and `pixel_data`'s `ijk` indices holds true for all cases.

**Comment by SimonBiggs** [comment]
So I'm trying to knuckle this down. Right this minute within PyMedPhys the only things we are using coordinates from DICOM for are for dose interpolation. Gamma is using the coords to interpolate dose, the profile code is doing the same.

Are we (have I) potentially been trying to generalise this too soon? Maybe what we want, maybe all we want, is to have a "fixed coords" dose exporter. And then have a fixed coords co-ordinate exporter.

That way we can use plain old numpy arrays and just always keep them in XYZ order.

What do you think?

This would involve transforming the pixel_data object's axis order, and transforming the axis direction so that positive fixed coordinate space results in increasing index. This would be done based on patient orientation, and then we just need to export fixed co-ordinate values as well.

So something like (names need improving):

```pythin
coords, dose = fixed_coords_and_dose_from_dataset(dicom_dose_dataset)
```

**Comment by SimonBiggs** [comment]
(by the way, on annual leave at the moment, so if you do want to call, don't bother calling my work phone :) )
