### ISSUE TITLE
Swap to black formatter

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#432]
The black formatter has managed to gain an almost semi-official degree of support:

https://mobile.twitter.com/llanga/status/1153417050024550401

Of note, they recommend bumping the line length up to 88 (based on git diff reduction analysis). @Matthew-Jennings you'll like that :).

But it seems like quite a good way forward. It appears to be quite a nice autoformater.

**Comment by Matthew-Jennings** [comment]
Happy :)
