### ISSUE TITLE
Blackifying codebase

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#444]
Black aims to minimise diffs allowing reviewing to be easier and have the git blames be better assigned to who changed the line.

However, in the transition it will do exactly the opposite. And potentially cause conflicts in open pull requests. I vote, we get current major pull requests merged. Then blackify the whole code base before open a new pull request.

Either that, or iteratively blackify things and we will to go through a bit of review pain with excessive diffs initially...

**Comment by Matthew-Jennings** [comment]
I agree, but I don't really think we need to finish off all pull requests before pulling the trigger. We can just blackify all branches.

**Comment by SimonBiggs** [comment]
True, it is deterministic ... So conflicts should actually be minimal.

**Comment by Matthew-Jennings** [comment]
So `pylint` doesn't like `black`'s indentation:

![image](https://user-images.githubusercontent.com/19767103/62014690-978fff80-b1e3-11e9-940c-9689c29222ee.png)

@SimonBiggs, would you be willing for us to include a global ignore of `bad-continuation`?

**Comment by SimonBiggs** [comment]
All good, we just need to make an rc file for pylint within the repo that
disables those particular messages.
