### ISSUE TITLE
Deterministic UIDs independent of implementation

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#448]
Heya @Matthew-Jennings ,

When discussing how to make deterministic UIDs we need to be wary of things like the following:

https://github.com/pydicom/pydicom/issues/896

What we choose needs to be able to be robust to changes in the underlying data stored by the DICOM object within both pydicom and any PyMedPhys DICOM object.

I had a bit of a brain wave about how to do this. Let's make a json string representation of the DICOM object, and let's make each key be a string that conforms exactly with how that key is named within the DICOM standard (spaces and all). Then, let's have all data be transformed into json data and have all keys be alphabetically sorted. The only item missing from this string is the UID of the DICOM file itself. Then, the resulting UID will be that json string object hashed with sha256 and the resulting hash converted to a UID extension.

This way, we are free to change our internal structure of the DICOM object, and also have pydicom change its structure, but the hash based UID should never change. (Unless the DICOM standard changes its key names... Has there been precedent of that?)

According to the following we must not exceed 64 characters for a UID. With our origin tag plus the separator dot this leaves us 37 characters to work with. With a space as large as 10^37 each human being on the planet would need ~10 million DICOM files for there to be ~0.001 probability that any two of those differing DICOM files end up randomly having the same UID:

https://en.wikipedia.org/wiki/Birthday_problem#Probability_table

So... I like those odds. With that space of characters to work with we should be able to then deterministically map that sha256 hash onto those 37 characters and have a probabalistic guarantee of uniqueness.

@Matthew-Jennings what are your thoughts?

@darcymason can you see any holes in my logic?

**Comment by darcymason** [comment]
In general, hashing json sounds like a reasonable thing to do - very git-like in approach.
 
However, I'm not sure I follow - if the values are hashed, then you have to assume that the json rep does not change. but is that guaranteed?  The pydicom json tools are in flux right now, unless you roll your own...

Another thought that pops into my head is Referenced UIDs in DICOM - many UIDs reference connected DICOM objects, and that value itself would then become part of the hash.  I suppose its possible to get through that, but it seems like they would have to be hashed in careful order.

And to DICOM keyword uniqueness -  I would say that the chance of any changes now is extremely low.

**Comment by SimonBiggs** [comment]
> However, I'm not sure I follow - if the values are hashed, then you have to assume that the json rep does not change. but is that guaranteed? The pydicom json tools are in flux right now, unless you roll your own...

This needs more thought I think. To be honest I wasn't aware of the following pydicom json initiative https://github.com/pydicom/pydicom/issues/807. It certainly would be prudent to not reinvent the wheel. Certainly more thought needed here. Maybe, for the time being, it isn't a promise of determinism. Instead it is just another UID creation method. Set it up, let it settle, iron out kinks. And then, one day, if we want a deterministic guarantee we vendor in the relevant pydicom code so as to guarantee the json rep used for hash creation is unchanged... Not sure. Just throwing ideas around really.

> Another thought that pops into my head is Referenced UIDs in DICOM - many UIDs reference connected DICOM objects, and that value itself would then become part of the hash. I suppose its possible to get through that, but it seems like they would have to be hashed in careful order.

Yup certainly. The internally referenced UIDs would also be hashed, so yes order would be important. As in, any references DICOM object would need to first have its UID determined.

> And to DICOM keyword uniqueness - I would say that the chance of any changes now is extremely low.

Cheers :).

**Comment by SimonBiggs** [comment]
I was wrong about spaces. The DICOM json spec has the keywords without spaces:

http://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_6.html#table_6-1
