### ISSUE TITLE
Get the Windows Pipeline working again

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#452]
Hi,

I'm getting the following error when I try to run `pytest` from within the `pymedphys` root dir:

![image](https://user-images.githubusercontent.com/19767103/62101169-9d650e00-b2d3-11e9-9fd5-40429f0dc068.png)

I haven't yet been able to isolate a commit for whch this doesn't happen. I tried reinstalling `pytest` via `pip` and "reinstalling" the entire env to no avail. I wonder whether we've had a sneaky upgrade to a dependency that Windows doesn't like?

**Comment by Matthew-Jennings** [comment]
I wonder whether we ought to implement a Windows pipeline...

**Comment by SimonBiggs** [comment]
Interesting. Yup, a Windows pipeline I would argue should now bump up the priority list.

**Comment by SimonBiggs** [comment]
I'll do that tonight I think.

**Comment by Matthew-Jennings** [comment]
Reverting to `pytest==3.6.4` helped.

**Comment by SimonBiggs** [comment]
> Reverting to `pytest==3.6.4` helped. That's a long way back though and not really a solution (no `tmp_path`) - maybe a dependency of `pytest` itself is the problem?

Working on the pipeline hopefully will shed some light on it.
