### ISSUE TITLE
Pinnacle Export image dataset issue for pre-version 9.0

### ISSUE THREAD

**Issue by MPCurrie** [pymedphys/pymedphys#455]
Hi there,

Thanks for making this pinnacle export tool available. I've been testing it out on our pinnacle tarfile archive and noticed that for our older plans pre-Pinnacle version 9.0, the image dataset is offset in the Y direction from the dose and structureset. The dose and structures appear to have the correct coordinates.

**Comment by pchlap** [comment]
Hi Mike, thanks for testing the tool and for opening this issue. Good timing as I literally got back from leave today! :)

I haven't tested on anything pre-version 9.0 I don't think, and I don't even have this version of Pinnacle available to me. What would be really useful is if you could export a dummy plan on some phantom image or similar (i.e. a plan where no identifiable patient data can be found) and share the raw pinnacle files as well as the Pinnacle exported Dicom with me. Then I could start having a look at what's causing that issue.

If you have a university affiliation you could share them using [Cloudstor](https://cloudstor.aarnet.edu.au). If not something like OneDrive or Google Drive will do. As we get more people testing this tool out I can imagine we would like to do more sharing of datasets like this, so we might need to think of a better way to share these moving forward.

**Comment by SimonBiggs** [comment]
@pchlap as long as the user is very confident that the data does not contain any sensitive information the data can be uploaded to https://zenodo.org/ this is likely how we plan on including any data file larger than 10 MiB within PyMedPhys itself in the near future.

**Comment by SimonBiggs** [comment]
@pchlap do you envisage any further work here? Can this issue be closed? I'm trying to clean out the issue backlog to just cover things that might feasibly be addressed.

**Comment by pchlap** [comment]
@SimonBiggs I think we'll close this one... There is work to be done as far as getting the tool working on a range of Pinnacle versions. But I think we need to tackle that in a more structured way where we identify key Pinnacle versions and plan types which we want to support and then find a way to get the test data for that.

Will close now :)
