### ISSUE TITLE
Pinnacle RTPlan export issue regarding wedges

### ISSUE THREAD

**Issue by MPCurrie** [pymedphys/pymedphys#456]
I know this feature is listed as "not validated" yet, but in case this helps with debugging, I've noticed that RTPlan export fails for plans with Enhanced Dynamic Wedges. I get the following error message:

  File "C:\Program Files\Anaconda3\envs\py37\lib\site-packages\pymedphys_pinnacle\export\rtplan.py", line 289, in convert_plan
    wedgename = cp['WedgeContext']['WedgeName'].upper() + wedgeangle + "OUT"

TypeError: can only concatenate str (not "int") to str

**Comment by SimonBiggs** [comment]
This is the line where that issue is:

https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_pinnacle/src/pymedphys_pinnacle/export/rtplan.py#L310

Likely that should be using an f string instead.

**Comment by pchlap** [comment]
Yes, this code needs to be refactored to use f strings everywhere I'd say. This will definitely be part of the next iteration of development.

This would fix this problem and the RTPlan will export but validating the RTPlan output is another issue which we will need to tackle separately.

**Comment by SimonBiggs** [comment]
Given I opened up the rtplan file I wanted to make a few comments on some of the things I saw. See the review at https://github.com/pymedphys/pymedphys/pull/402#pullrequestreview-270576223

There is already code within PyMedPhys that turns the `Delivery` object into an RTPlan file (https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_dicom/src/pymedphys_dicom/delivery/core.py#L157-L186)

I suspect it might be better to make a `Delivery.from_pinnacle()` method, and then convert from `Delivery` to RTPlan using the already available tools.

**Comment by SimonBiggs** [comment]
This would then remove the need for that `rtplan.py` file altogether....

**Comment by SimonBiggs** [comment]
Of note, one thing in that file is hard coded Varian MLC leaf widths...

**Comment by SimonBiggs** [comment]
Also!! Welcome back! And congratulations :) @pchlap

**Comment by SimonBiggs** [comment]
> Given I opened up the rtplan file I wanted to make a few comments on some of the things I saw. See the review at [#402 (review)](https://github.com/pymedphys/pymedphys/pull/402#pullrequestreview-270576223)
> 
> There is already code within PyMedPhys that turns the `Delivery` object into an RTPlan file (https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_dicom/src/pymedphys_dicom/delivery/core.py#L157-L186)
> 
> I suspect it might be better to make a `Delivery.from_pinnacle()` method, and then convert from `Delivery` to RTPlan using the already available tools.

(The delivery to rtplan code will need to be expanded to support all the required cases, but that will be great as that will also expand all sorts of other things as well)

**Comment by SimonBiggs** [comment]
But feel free to do this however you feel is best. Really want you to feel like this is your part of the code base and for you to have the freedom and authority you need to make the changes you need to make.

**Comment by pchlap** [comment]
@SimonBiggs Thanks a lot for the comments and code review. Yeah I couldn't agree more that all of these hard coded values need to go. I definitely think integrating this to work with existing pymedphys modules is a great idea and will make the code much easier to maintain.

I do like the concept of using a template for the Dicom generation, however I do have some concerns. Firstly there might not be a Dicom template easily accessible to the user, if, for example, they don't have access to Pinnacle itself anymore. Additionally, often we will run an export of a cohort of over 1000 patients, who have been treated over time on different machines and different treatment modalities etc... Would that mean we would need multiple templates? And then have to match the appropriate template with the treatment modality etc..? I'm not sure exactly what would be required here, but I could imagine this would cause headaches for the user. Perhaps one solution could be that we provide some 'default' templates to fall back on when the user isn't able to supply templates for their institution?

I must admit that I'm not very familiar with the RTPlan modality and I'm not sure exactly whats required to generate a sufficiently accurate version of this.

**Comment by SimonBiggs** [comment]
I guess the first question is are some of those values that are currently hard coded actually findable within the pinnacle tar files. Because if they are findable (such as what machine model it is, therefore what MLC bounds it has and what iso distance it has) then we don't need to talk templates at all.

If that information isn't findable anywhere then we certainly could create templates that have that information in it. It would make sense to have a template for each machine type.

**Comment by SimonBiggs** [comment]
> Additionally, often we will run an export of a cohort of over 1000 patients, who have been treated over time on different machines and different treatment modalities etc... Would that mean we would need multiple templates? And then have to match the appropriate template with the treatment modality etc..?

It does make one hope that a solution can be found that is not template based, but instead all of this info will be found within the tar files and can then be appropriately mapped.

Yeah, I think scrap my template idea. That's not going to be the nearest solution. Let's not use the `Delivery` object for this. But it would be nice to make an abstract DICOM RT Plan creation toolbox that abstracts out RT Plan creation functions that are independent of which planning system the data is coming from...

**Comment by Matthew-Jennings** [comment]
> Additionally, often we will run an export of a cohort of over 1000 patients, who have been treated over time on different machines and different treatment modalities etc... Would that mean we would need multiple templates? And then have to match the appropriate template with the treatment modality etc..? I'm not sure exactly what would be required here, but I could imagine this would cause headaches for the user.

> It does make one hope that a solution can be found that is not template based, but instead all of this info will be found within the tar files and can then be appropriately mapped.

The thing is, the user *must* be able to provide either the relevant machine characteristics or the machine make and model for *each* plan in a batch in order to meaningfully use the RTPlan information. I would say that the tool really should fail if insufficient machine data is available.

At the RAH, we (try to) backup all of our patient data with their respective machine(s). Thus, our .tar files typically contain all of the required machine information in a file called `.auto.plan.Pinnacle.Machines`. Unfortunately, exporting machine(s) along with patient data is optional and does substantially increase backup size. Moreover, the actual machines that are exported are user-selected. Unless you export all machines, there is a chance that you don't export the machine the corresponds to at least one plan in the patient's data. Frustratingly, Pinnacle does not check for this.

Basically, there is no guarantee that a given .tar file contains all of the requisite machine data. BUT there *is* sufficient information in each plan (i.e., `MachineNameAndVersion`) to at least check *whether* you have the required machine data. **I would argue for implementing this check and having the tool fail upon this check failing.** Or perhaps fail after providing a list of templates from which the user could select. See comments below:

> Perhaps one solution could be that we provide some 'default' templates to fall back on when the user isn't able to supply templates for their institution?

I think this is doable. This is common for TPSs themselves, and we can probably cover the majority of users of relatively few templates.

> But it would be nice to make an abstract DICOM RT Plan creation toolbox that abstracts out RT Plan creation functions that are independent of which planning system the data is coming from...

+1

**Comment by crcrewso** [comment]
I'm not sure if I should add it here or a new issue, but the current master version does not handle at least 1 format of fixed wedge. 

Here's an example Field control point 
```
            Gantry = 310;
            Couch = 0;
            Collimator = 0;
            WedgeContext ={
              WedgeName = "UP 45";
              Orientation = "WedgeRightToLeft";
              OffsetOrigin = "Patient Surface";
              OffsetDistance = -2.5;
              Angle = "Fixed";
              MinDeliverableMU = 0;
              MaxDeliverableMU = 1e+30;
            };
```

**Comment by SimonBiggs** [comment]
It is possible to upload an example file to github issues, are you able to
make a test case based on a qa patient?

I won't be the one fixing this, but those sorts of things really help.

**Comment by crcrewso** [comment]
@SimonBiggs sorry, but our pinnacle system is shut down, so I can't create a new plan, only test ones. I'll resubmit as a full issue so that all the details can live in their own thread

**Comment by pchlap** [comment]
Thanks @crcrewso 

We do have Pinnacle so one idea would be to create a plan, with multiple trials which contain all different types of plans/beams, at least those we would like to support.

I don't know how to use Pinnacle so I will have to get someone to help me generate something like that. Along with the Pinnacle exported (ground truth) Dicom that would be really useful. I'll see what I can do.

**Comment by SimonBiggs** [comment]
Yup, certainly having a range of supported end to end test case "input/output" pairs would essentially be the first step on building robustness into this toolkit.

**Comment by SimonBiggs** [comment]
I believe this issue was fixed in https://github.com/pymedphys/pymedphys/pull/709.

@pchlap feel free to re-open if I am mistaken.
