### ISSUE TITLE
How to build good software -- article

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#466]
Here is a good article. It explains the needs of writing good software in a way accessible to non-programers. It's written well.

https://www.csc.gov.sg/articles/how-to-build-good-software

**Comment by SimonBiggs** [comment]
@matthewdeancooper can you have a read of this. It's a great article on software development practice.

**Comment by matthewdeancooper** [comment]
@SimonBiggs reading now :)
