### ISSUE TITLE
Work a bit on docs before 0.6.0 release

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#49]
There are a few things in the docs that can have a bit of love before we make a new release

**Comment by SimonBiggs** [comment]
@Centrus007 do you think we can forge a release?

**Comment by Centrus007** [comment]
What in particular would you like to see completed before we cut one?

**Comment by SimonBiggs** [comment]
I don't think anything. My preference is really to be able to flow releases
out on a regular basis. So unless there are any show stoppers I could cut
one tonight?

**Comment by Centrus007** [comment]
Especially while we're in 0.x, I don't see the harm :)

**Comment by SimonBiggs** [comment]
Awesome :)
