### ISSUE TITLE
Image class

### ISSUE THREAD

**Issue by brenthuisman** [pymedphys/pymedphys#490]
I've spun off some of my code into a perhaps useful piece for this repo (even if only by link), my `medimage` package [click](https://github.com/brenthuisman/medimage). The utility is that it is basically a read/write wrapper around numpy arrays, so in case you analyze data using matplotlib (and who doesn't) or use other tools (Tensorflow for instance) it's easy to interoperate. Also, I think I handle axes indexing for consistent than any other lib ;) It's pure Python, so that makes it easy to use on clusters or other niche platforms.

It's been very useful to me, I thought it might be useful to others as well. Happy to hear if you're interested!

**Comment by SimonBiggs** [comment]
@brenthuisman this sounds great! Can I get back to you at some point next week about this?

I'm currently undergoing a refactor which is aiming for repo simplification focusing on ease of use for contributors:

https://github.com/pymedphys/pymedphys/pull/486

That should be finished mid next week, at which point I would be keen to work on this.

**Comment by brenthuisman** [comment]
Sure thing! Indeed, your repo seems a bit complex which is why I did not bother with a PR ;) Main thing I want to do in the following week(s) is (at long last) add dicom write support, at which point it might be a nice addition.

**Comment by SimonBiggs** [comment]
> Sure thing! Indeed, your repo seems a bit complex which is why I did not bother with a PR ;)

Yup, that was the feedback I have been getting. Thanks for re-affirming it (justifies the work to being done to simplify it).

If I want pymedphys to be a place where we can all work on code together I certainly need to fix that.

**Comment by SimonBiggs** [comment]
So @brenthuisman! :) I have simplified things a bit :). The current contributor docs are out of date, I'll see if I can fix that tonight. But the gist is this:

Environment
-----------

* Get Python 3.7 (however you like, I'm using [pyenv](https://github.com/pyenv/pyenv) on Ubuntu personally)
* Install poetry -- https://poetry.eustace.io/docs/#installation
* Either fork and clone the git repo, or ask for commit access and simply clone the repo

Intallation
-----------

### OS specific initial stuff

On Windows you will need to preinstall `shapely` by downloading the wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely and then [installing the wheel with pip](https://packaging.python.org/tutorials/installing-packages/#installing-from-local-archives) `pip install ./wheel-name.whl`.

On MacOS you will need to pre install cython with `pip install cython` and you will need to also install `freetds` with [homebrew ](https://brew.sh/) by running `brew install freetds`

On Linux no extra steps needed, it just works :).

### For all OSes

Then run `poetry install` within the git repo, and it will create a virtual environment for you and install `pymedphys` in editable mode as well as all of its development dependencies. Use `poetry install -E labs` to also install the dependencies needed to run some of the stuff within `pymedphys.labs`.

**Comment by SimonBiggs** [comment]
If you're keen it would be amazing to get a pull request where your image class is initially put within a directory in the labs:

https://github.com/pymedphys/pymedphys/tree/master/pymedphys/labs

Once it's there and happily residing within the package we can work on finding it a home within the main section of the package itself :).

**Comment by SimonBiggs** [comment]
Unfortunately neither of those options are actually ideal. A one time dump implies a sort of set and forget. Unfortunately that won't work as there is ongoing maintenance of the code, integration with other tools with PyMedPhys, refining of API etc. If you're interested in that process for your image class then it would be awesome to move forward. If you would rather a set and forget then the best option would to leave it in your current repo.

What do you think?
