### ISSUE TITLE
Mosaiq API adjustment

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#496]
For version 0.12.0 of PyMedPhys I'm considering changing the Mosaiq API quite drastically.

One part of this, is instead of exposing helper functions that hide the SQL code away, instead I think I'm going to expose just the connect functions, an "execute_sql" function, and then provide a large set of example query strings.

To use the code I propose needing to do something like:

```python
from pymedphys import mosaiq

with mosaiq.connect('hostname') as cursor:
    result = mosaiq.execute(
        cursor, mosaiq.FIELDS,
        {
            patient_id: '000000'
        }
    )
```

Where FIELDS is an SQL string which can be printed and used as a template for ones own query.

I find people more often than not want to do all sorts of things that I haven't already done. By exposing the machinery like this it equips people to do more custom things themselves.

@mchamberland what do you think?

**Comment by mchamberland** [comment]
I think that’s a good idea! I’ve been meaning to learn SQL since databases pop up all the medical physics. Providing sample queries will give users a good starting point.

**Comment by fishdda** [comment]
So actually now, do we have any tools or py script to connect to Mosaiq SQL database and extract log information like mlc position, beam names and etc.

**Comment by SimonBiggs** [comment]
@fishdda certainly, see the following issue:

https://github.com/pymedphys/pymedphys/issues/147#issuecomment-482273270

**Comment by fishdda** [comment]
Hi Simon,  your suggestion is really useful. Btw, I have another question, when I want to extract data from Mosaiq, seems the data of A_Leaf_Act and B_Leaf_Act wasn't 80 double data to store mlc leaves respectively. Do I need to decode to 80 points? Did you meet this phenomenon before?
![image](https://user-images.githubusercontent.com/23411165/65402311-209c6f00-de00-11e9-844e-aaba18f8259c.png)
these are data from Mosaiq.

Many thanks,
Henry

**Comment by SimonBiggs** [comment]
@fishdda, yup I have seen that, and the fix / workaround is here:

https://github.com/pymedphys/pymedphys/blob/52429a21e075b1a74861dbd5e1737c4a405aa9fe/packages/pymedphys_databases/src/pymedphys_databases/msq/delivery.py#L215

When you use the "delivery data from mosaiq" functions within pymedphys it does this to decode the MLC positions.

**Comment by fishdda** [comment]
many thanks for your help.

**Comment by SimonBiggs** [comment]
In the updated API I am considering making extracting MLC, gantry, collimator etc as simple as the following:

```python
import pymedphys

with pymedphys.mosaiq.connect('hostname') as cursor:
    delivery = pymedphys.Delivery.from_mosaiq(cursor, field_id)

delivery.mu  # cumulative MU
delivery.mlc  # MLC positions ... etc

```

**Comment by SimonBiggs** [comment]
> many thanks for your help.

My pleasure :)

**Comment by fishdda** [comment]
Hi Simon, one more question, the MLC data stored in Mosaiq is the physical positions of MLC ? Actually, I saw the mlc data is 200 width binary data, but our agility mlc is 80 leaves, how can I understand this difference?

**Comment by SimonBiggs** [comment]
> Hi Simon, one more question, the MLC data stored in Mosaiq is the physical positions of MLC? Actually, I saw the MLC data is 200 width binary data, but our agility MLC is 80 leaves, how can I understand this difference?

You might need to let me know what SQL query you used so that I can help you further on that one.

**Comment by SimonBiggs** [comment]
As a further question, if you use the following function on that field you are looking at, how many MLCs do you get per control point?

https://github.com/pymedphys/pymedphys/blob/52429a21e075b1a74861dbd5e1737c4a405aa9fe/packages/pymedphys_databases/src/pymedphys_databases/msq/delivery.py#L362-L396

**Comment by SimonBiggs** [comment]
> the MLC data stored in Mosaiq is the physical positions of MLC?

This depends. You can either be pulling the reference field data which are the control points that Mosaiq intends to deliver, or you can actually pull the delivery logs, which are the Linac reported positions at a 4 Hz time resolution.

I personally prefer the trf logs which provide 25 Hz time resolution.

**Comment by fishdda** [comment]
I used A_Leaf_Set in TxFieldPoint and data were like 
[4C044C044C041F04D7038E034603FD02B5026D022502DD0195014D010501BD0075002D00ECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFF8AFD8AFD8AFD24FF84FE84FE06FF9EFD9EFD9EFDECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFFECFF2D007500BD0005014D019501DD0125026D02B502FD0246038E03D7031F044C044C044C0400000000000000000000000000000000000000000000000000000000000000000000000000000000]
and I used the msq_decode py from you to extract the mlc position data, but it looks like wrong. So I have no idea how to solve this problem.

Could you show me some demo MLC position data from Mosaiq for me as a reference?
Btw I found all the data decode from Mosaiq were positive but actually some position of MLC should be negative if they are on the two sides of isocenter. I am very confused and could you help me?

**Comment by fishdda** [comment]
`def decode_msq_mlc(raw_bytes):
    """Convert MLCs from Mosaiq SQL byte format to cm floats.
    """
    raw_bytes = mosaiq_mlc_missing_byte_workaround(raw_bytes)

    length = check_all_items_equal_length(raw_bytes, "mlc bytes")

    if length % 2 == 1:
        raise Exception("There should be an even number of bytes within an MLC record.")

    mlc_pos = (
        np.array(
            [
                [
                    struct.unpack("<h", control_point[2 * i : 2 * i + 2])
                    for i in range(len(control_point) // 2)
                ]
                for control_point in raw_bytes
            ]
        )
        / 100
    )

    return mlc_pos`
I 've checked your code, could you give me an example for the format of the control point in these codes.

**Comment by SimonBiggs** [comment]
Could you run:

```bash
pip install pymedphys==0.12.0dev0
```

In a prompt to install the currently in development API.

Then do the following:

```python
import numpy as np
import pymedphys

field_id =  # a Mosaiq SQL field_id goes here

with pymedphys.mosaiq.connect('hostname') as cursor:
    delivery = pymedphys.Delivery.from_mosaiq(cursor, field_id)


print(np.shape(delivery.mlc))
```

**Comment by fishdda** [comment]
alright, but I may have a dummy question if my workstation cannot connect to the web, how could I run pip?

**Comment by SimonBiggs** [comment]
How'd you install pymedphys in the first place?

**Comment by SimonBiggs** [comment]
It is possible to download the wheel from the following address:

https://files.pythonhosted.org/packages/b6/af/97e2aa824617b9fe3e94a13a0f536ec02debbeabf0abcd2b018cf7a7241d/pymedphys-0.12.0.dev0-py3-none-any.whl

Then install pymedphys like so run from the directory where that file is:

```bash
pip install ./pymedphys-0.12.0.dev0-py3-none-any.whl
```

You'll likely need dependencies though...

**Comment by fishdda** [comment]
Oh, sorry I may neglect introducing my workflow for you. since our Mosaiq don't have access to outside network, I only remote to the server which has Mosaiq and use SQL tool to extract all the data to a txt file. And then I load this file including TxFieldPoint to matlab, but what mlc leaf position look like is a binary data and I am confused how to extract them.

As you know, I have rtplan dicom storing MLC position. What I wanna do is to compare Mosaiq and TPS.

**Comment by fishdda** [comment]
but actually the key for me is the mlc position in mosaiq
what they look like in matlab is following:
![image](https://user-images.githubusercontent.com/23411165/65417843-9d920d80-de2d-11e9-96b9-146d5fab5380.png)

**Comment by SimonBiggs** [comment]
I guess from my end, I've already solved all this within `pymedphys`, so you may as well sort out getting that into your environment.

You don't actually need to be on the Mosaiq machine to access Mosaiq SQL. Any machine in the centre which is on the same local network as Mosaiq should be able to connect to Mosaiq's SQL.

**Comment by fishdda** [comment]
I get your point, Simon.

**Comment by fishdda** [comment]
Thanks

**Comment by SimonBiggs** [comment]
Have you tried connecting to Mosaiq SQL from another machine on the local network?

**Comment by fishdda** [comment]
not yet

**Comment by SimonBiggs** [comment]
That might be your winner. Can you access the internet from another computer on the same local network as the Mosaiq machine?

**Comment by fishdda** [comment]
yes, seems could but I still don't try it now.
