### ISSUE TITLE
Make tomo_sinogram_csv2pdf.py clinic-friendly

### ISSUE THREAD

**Issue by kingrpaul** [pymedphys/pymedphys#51]

**Comment by SimonBiggs** [comment]
We should turn this tool into a command line interface.

It could be quite nice if running the following within a terminal would trigger the conversion:

```
pymedphys sinogram csv2pdf inputfilename.csv outputfilename.pdf
```

That way you could call that command from any programming language (even python 2 within your TPS)

**Comment by SimonBiggs** [comment]
See the following two sections of code for where a CLI has been made:

https://github.com/pymedphys/pymedphys/blob/master/src/pymedphys/dcm/_level2/header_tweaks.py#L50-L54

https://github.com/pymedphys/pymedphys/blob/master/src/pymedphys/cli/main.py#L49-L55

**Comment by kingrpaul** [comment]
I'll scope it out. Yes, I want to use this clinically now and realize it's not in a form I can have others use.

**Comment by SimonBiggs** [comment]
Makes sense. It's also worth getting a hold of the remaining of that code
that converts the original tomo format.
