### ISSUE TITLE
PyMedPhys Steering Council

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#518]
Hi @Matthew-Jennings, @pchlap, @kingrpaul, @peterg1t, @darcymason,

I have sent through an email inviting you to the steering council meeting next week. 

This issue is actually to alert @peterg1t, I couldn't find your email. Would you be able to email me at me@simonbiggs.net so that I can forward the invite through to you?

Cheers,
Simon

**Comment by SimonBiggs** [comment]
Others who are willing to commit to the PyMedPhys project itself may also request to attend the steering council meeting.

**Comment by peterg1t** [comment]
Hi Simon,
Thanks for letting me know! You can forward the invite to
pemartin@ucalgary.ca or pedro.enrique.83@gmail.com. looking forward to the
meeting.
Regards
Pedro

**Comment by SimonBiggs** [comment]
Done :)
