### ISSUE TITLE
Easy installation of `pytest` and `test_requires` modules

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#53]
When following the `pymedphys` installation instructions [here](http://pymedphys.com/en/stable/developer/contributing.html#install-the-development-version-of-pymedphys), all of the modules required for running `pymedphys` (i.e. everything in the `install-requires` list) install fine. But `pytest` and all of the modules under `tests_require` do not.

To date I've just installed each of the modules in `pytests_require` manually, but is there a way to do so as conveniently as for those under `install_requires`?

Cheers,
Matt

**Comment by Centrus007** [comment]
E.g. is it worth putting them in `extras_require` as per the following SO posts?
https://stackoverflow.com/a/41398850/4665458
https://stackoverflow.com/a/32513360/4665458

**Comment by SimonBiggs** [comment]
I'd be happy for that to happen :) feel free :).
