### ISSUE TITLE
Help setting up PyMedPhys

### ISSUE THREAD

**Issue by rembishj** [pymedphys/pymedphys#540]
* [x] Remove shapely
* [x] Remove need for admin in contrib docs

**Comment by SimonBiggs** [comment]
[] Remove shapely
[] Remove need for admin in contrib docs

**Comment by SimonBiggs** [comment]
@rembishj 

Once you are able to install the development version of PyMedPhys you will be able to do the following:

```python
import pydicom

import pymedphys
import pymedphys.mosaiq

MSQ_FLD_ID = 000000  # an SQL FLD_ID goes here
DICOM_PLAN_FILEPATH = 'path/to/RP.something.dcm'

with pymedphys.mosaiq.connect('hostname') as cursor:
    mosaiq_delivery = pymedphys.Delivery.from_mosaiq(cursor, MSQ_FLD_ID)

dicom_plan = pydicom.dcmread(DICOM_PLAN_FILEPATH, force=True)

# the need to write a fraction number can be changed if it is painful to use
dicom_delivery = pymedphys.Delivery.from_dicom(dicom_plan, fraction_number=1)

# here you can then compare mu, mlc, jaw, gantry, coll, etc.
# more can be added to the delivery object if need be
```


These are defined at:

https://github.com/pymedphys/pymedphys/blob/33e890a3efa0460b5d7ffac5ab72bab83bf4de22/pymedphys/_mosaiq/delivery.py#L323-L357

and

https://github.com/pymedphys/pymedphys/blob/33e890a3efa0460b5d7ffac5ab72bab83bf4de22/pymedphys/_dicom/delivery/core.py#L62-L71

and

https://github.com/pymedphys/pymedphys/blob/7ea86ff38bcb6c32deaee94a5be252ed3ce28f46/pymedphys/_base/delivery.py#L44

**Comment by SimonBiggs** [comment]
With a delivery object, you can also calculated mudensity like so:

```python
mudensity = delivery.mudensity()
```

Which is defined here:

https://github.com/pymedphys/pymedphys/blob/33e890a3efa0460b5d7ffac5ab72bab83bf4de22/pymedphys/_mudensity/delivery/core.py#L33-L61

Internally we compare Mosaiq and DICOM as well as logfiles by comparing the MU Density.

TRF files can also be converted into a delivery object like so:


```python
delivery = pymedphys.Delivery.from_logfile('/path/to/trf')
```

**Comment by SimonBiggs** [comment]
Removed shapely and improved contrib docs. New contrib docs are at:

https://master--pymedphys.netlify.com/contrib/tutes/setup-win.html

The pull requests for the changes are the following: 

* https://github.com/pymedphys/pymedphys/pull/544
* https://github.com/pymedphys/pymedphys/pull/545
* https://github.com/pymedphys/pymedphys/pull/546
