### ISSUE TITLE
Rename dcm module to dicom

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#56]
With the new file structure we don't need to have the module name in front of every file path. This also means that short module names aren't really needed anymore.

I believe `dcm` as a name is too cute. I think it would make far more sense to call the module `dicom`.

**Comment by Centrus007** [comment]
Agreed.

**Comment by Centrus007** [comment]
On a related note, we've typically been using the variable name "dcm" to represent a pydicom Dataset. This is in contrast with pydicom convention, where "ds" (short for "dataset, I believe) is preferred.

Should we replace all `dcm` variables with `ds` in the library?

**Comment by SimonBiggs** [comment]
What about in the pydicom docs, does it use dcm there? I'm sure I picked it
up from somewhere.

I'd be happy to change, but I'd like to confirm that we are actually
breaking convention before we do.

**Comment by SimonBiggs** [comment]
Also :) if there's no rush on your end I'd be happy to do it when I do get
a chance

**Comment by Centrus007** [comment]
The link I provided above is from the PyDicom docs. But for more specific evidence, see:

- From the Pydicom Complete API Reference, **Examples** under the `class pydicom.dataset.Dataset` entry ([link here](https://pydicom.github.io/pydicom/stable/api_ref.html#pydicom.dataset.Dataset)):
```python
>>> ds = Dataset()
>>> ds.PatientName = "CITIZEN^Joan"
>>> ds.add_new(0x00100020, 'LO', '12345')
>>> ds[0x0010, 0x0030] = DataElement(0x00100030, 'DA', '20010101')
```
- From the Pydicom Complete API Reference, **Examples** under the `pydicom.filereader.dcmread()` function entry ([link here](https://pydicom.github.io/pydicom/stable/api_ref.html#pydicom.filereader.dcmread)):
```python
>>> ds = pydicom.dcmread("rtplan.dcm")
>>> ds.PatientName
```

**Comment by Centrus007** [comment]
In fact, even PyDicom's dataset editing functions name the returned dataset `ds`. For example, see:

* From the Pydicom Complete API Reference, the docstring for the`pydicom.filewriter.correct_ambiguous_vr()` function ([link here](https://pydicom.github.io/pydicom/stable/api_ref.html#pydicom.filewriter.correct_ambiguous_vr)):

> Iterate through `ds` correcting ambiguous VR elements (if possible).
[...]
Returns `ds:pydicom.dataset.Dataset

**Comment by Centrus007** [comment]
> Also :) if there's no rush on your end I'd be happy to do it when I do get a chance

No rush from me at all :)

**Comment by Centrus007** [comment]
Just one last cherry to pop on the top: `dicompyler-core` has a pydicom wrapper class called `DicomParser` which saves the parsed pydicom Dataset as `self.ds`. See [here](https://github.com/dicompyler/dicompyler-core/blob/f5f9fa770d0573373510135863fa2933919cdba7/dicompylercore/dicomparser.py#L34).

**Comment by SimonBiggs** [comment]
Yup I'm convinced. Let's defer to the defacto standard nomenclature.

**Comment by SimonBiggs** [comment]
I'm happy for you to do it if you want to. Either way :). But I think it
would be worthwhile making the switch before 0.6.0.

**Comment by SimonBiggs** [comment]
:)
