### ISSUE TITLE
Increase log file precision

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#569]
Currently when MU is extracted from trf files and stored within the MU item within the `Delivery` `namedtuple` it doesn't use the higher precision column. Reported by @mwillam. 

@mwillam given you reported this would you like to have the pull request and commit that changes it be accredited to you? As in, would you like to make the code change and pull request? I'm happy to do it if you don't want to, just let me know.

**Comment by mwillam** [comment]
Sure I'll make the change. Maybe someone else can comment on this though. I noticed that the main difference between the 'Dose' and 'StepDose' data fields is the precision. 
StepDose smallest increment is 0.1MU while Dose has 1/64MU increments.
There might be other differences that I don't know about. Does anyone know this?
