### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by sykesjonr** [pymedphys/pymedphys#58]
Finally I get a moment to try out your installation instructions. Some things I ran into problems with were
1) I did not have a github account so needed to make that in order to raise this issue.
2) I did not have GIT installed so decided to install through Chocalatey as you have talked about this packager before. I did this by running powershell and the following command
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) as per https://chocolatey.org/install
3)  After closing the powershell and reopening (as admin) I ran 
choco install git.install.
After that running your commands to install BleedingEdge with GitHub worked fine.

**Comment by SimonBiggs** [comment]
Thanks @sykesjonr ! Those steps definitely should be added to the bleeding edge install instructions.

**Comment by sykesjonr** [comment]
But then I read on to your section on contribution and I guess the information I needed was there.

**Comment by SimonBiggs** [comment]
That info does also certainly belong in the bleeding edge install
instructions, or maybe under the bleeding edge install I should just
redirect to the contributor docs...

**Comment by SimonBiggs** [comment]
Would you like to be added to the repo?

**Comment by SimonBiggs** [comment]
You don't have to make use of if it if I do add you, but it frees you to easily submit pull requests if you would like...

**Comment by sykesjonr** [comment]
to install nbstripout I had to use
conda install -c conda-forge nbstripout
instead of simply
conda install nbstripout
Similarly I had to use 
conda install -c conda-forge pymedphys --only-deps
This gave me a warning I should update conda and pip to latest versions, which I did.

**Comment by sykesjonr** [comment]
I'm just trying to work through the instructions and get up to speed a little. Not sure if I need to be added to repo just yet.

**Comment by SimonBiggs** [comment]
Did you run the following?

```
conda config --add channels conda-forge
```

**Comment by sykesjonr** [comment]
No. I didn't. I guess that would have helped. I'll do it now in case I need it in future.

**Comment by SimonBiggs** [comment]
@sykesjonr I remember you asking about a "user friendly, non-programming database" this following product appears like it might fit that bill:

https://airtable.com

**Comment by SimonBiggs** [comment]
Getting started docs have been improved. I imagine further improvement will occur in docs rewrite which will be tracked in https://github.com/pymedphys/pymedphys/issues/416
