### ISSUE TITLE
Citing pymedphys

### ISSUE THREAD

**Issue by rickardcronholm** [pymedphys/pymedphys#602]
What's the proper/preferred way of citing pymedphys in a scientific paper?

**Comment by SimonBiggs** [comment]
Hi @rickardcronholm :),

What particular package are you using?

**Comment by rickardcronholm** [comment]
I'm using pymedphys_gamma version 0.8.4 (still on python 3.6)

**Comment by SimonBiggs** [comment]
No real great way to cite PyMedPhys yet unfortunately. Do you have any good ideas?

Potentially there would be value in actually having a `pymedphys` `gamma` paper. You were certainly instrumental in the part of the validation of the algorithm. Might there be value in putting out a small little technical note together in a journal like PESM (https://www.acpsem.org.au/member-bunker/pesm-journa) regarding the gamma implementation and validation?

**Comment by rickardcronholm** [comment]
I guess the best way of citing it right now would be to cite the website (
https://docs.pymedphys.com/index.html)?.
I still have the tex files for the manuscript we compiled with a more
clinical touch, so I guess a lot could be extracted from it for a technical
note. I don't have a lot of time to invest in writing such a paper
currently, but if you do I can certainly contribute to some extent. Another
option would be to publish on arxiv, either a technical note or the
manuscript we did write on npgamma. Although I guess you'd be more
interested in a citable item for pymedphys.

**Comment by SimonBiggs** [comment]
How about just citing https://pymedphys.com? Right now that redirects to the docs page, but if I ever did create a home page for pymedphys that's where it would sit.

**Comment by rickardcronholm** [comment]
Works for me

**Comment by SimonBiggs** [comment]
GitHub actually reformatted that url. So I'll rewrite it here, I would recommend citing:

```
https://pymedphys.com
```
