### ISSUE TITLE
Possible to make gamma_shell operate using purely relative dose?

### ISSUE THREAD

**Issue by BananaOrbit** [pymedphys/pymedphys#611]
I have two PDDs I want to compare using gamma_shell in 1D mode. Both of the numpy arrays are in units of % of D_max (numbers from 0 to 1). When I run gamma_shell, it assumes that the maximum dose is 1 Gy rather than unitless number 1 or 100%.

```
Calcing using global normalisation point for gamma
Global normalisation set to 1.0 Gy
Global dose threshold set to [0.02] Gy ([2.]%)
Distance threshold set to [2.] mm
Lower dose cutoff set to 0.1 Gy (10%)
```

Could we include an option for the dose units on both the reference and evaluation dose to be in units of % or in unitless values in the interval [0,1]?

**Comment by SimonBiggs** [comment]
I could just remove the reference to Gy in the output?

**Comment by BananaOrbit** [comment]
The analysis works fine as is, I just think it may be a good idea for the user to specify what units the dose arrays are in (Gy, cGy, %, etc...) and the output be adjusted according to that.

**Comment by SimonBiggs** [comment]
My preference is to have no input into the function be required that isn't absolutely necessary. I'll remove the units from the output given that the input arrays are unitless.

**Comment by SimonBiggs** [comment]
@BananaOrbit can you verify that this is fixed in https://github.com/pymedphys/pymedphys/releases/tag/v0.14.1 by installing 0.14.1

Cheers,
Simon

**Comment by BananaOrbit** [comment]
> @BananaOrbit can you verify that this is fixed

Seems to be fixed! Thanks for that :)
Although there seem to be double percent signs being written in the output:

```
Calcing using global normalisation point for gamma
Global normalisation set to 1.0
Global dose threshold set to [0.02] ([2.]%% of normalisation)
Distance threshold set to [2.]
Lower dose cutoff set to 0.1 (10%% of normalisation)
```

**Comment by SimonBiggs** [comment]
Cheers I'll fix that :)
