### ISSUE TITLE
Importing Gamma Shell

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#612]
A report by email from @BananaOrbit:

> I also wanted to let you know that the old way of importing gamma_shell doesn't seem to be accurate anymore.
> 
> Instead of using
> from pymedphys.gamma import gamma_shell
> 
> I am now using
> from pymedphys._gamma.implementation.shell import gamma_shell

Actually, the way to import gamma from pymedphys is the following:

```python
import pymedphys

pymedphys.gamma  # <-- this is gamma_shell
```

This was part of the API change in version 0.12.0 (https://docs.pymedphys.com/release-notes.html#id16).

If you ever do import from one of the `pymedphys._modulename` modules this is considered part of the private API and no changes to it will be reported in the changelog, and it will likely be shuffled around each time a refactor near that code occurs.

**Comment by SimonBiggs** [comment]
@BananaOrbit, you okay if I close this?

**Comment by BananaOrbit** [comment]
No problem

**Comment by SimonBiggs** [comment]
:)
