### ISSUE TITLE
Considering undergoing a license change

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#619]
Some work is being undergone to build a tool that will be helpful to the Medical Physics community, but I also believe that it will be helpful to users within the Jupyter ecosystem. It's a spiritual successor of the [scripted forms tool](https://github.com/SimonBiggs/scriptedforms).

I want to be able to have this tool included within PyMedPhys so that PyMedPhys itself benefits from the added popularity this tool, being included within it, would bring.

I suspect (I may be wrong) users within the Jupyter ecosystem, especially creators of the Jupyter tools themselves would actively avoid copyleft licenses due to not wanting to limit users of the ecosystem to a copyleft framework.

I would very much enjoy and appreciate being able to work within the Jupyter ecosystem and collaborate with Jupyter core developers. As such I would like to be able to change the entirety of PyMedPhys to instead use a permissive license instead of a copyleft license. The license of choice would be the Apache License due to how it covers cases of negligence and the importance of such a clause in the Medical Physics ecosystem.

My reasoning for choosing the AGPL was to maximise the likelihood of collaborators by making it so that there was no question whether or not the source code of derivatives should be made open source themselves. However, collaborators are collaborating not because of the AGPL, but simply because they want to collaborate. The AGPL itself has not been the cause of any extra contributions. By changing to the Apache license and by releasing the upcoming Jupyter ecosystem tool I believe these two actions in combination will attract more collaborators than should the tool be released while PyMedPhys is still under the AGPL.

@blink1073 would you say my reasoning about license style and the Jupyter community be correct, or maybe in your opinion a license change is not necessary? Would swapping from AGPL to Apache be enough? Or would the fact that it's not BSD be an issue?

@Matthew-Jennings @kingrpaul @pchlap @peterg1t @rembishj would you guys all be okay with a license change such as this, should I get the go ahead from work?

@msobolewski pinging you so you're aware of this thread.

**Comment by SimonBiggs** [comment]
Thanks @kingrpaul :). I have now had approval for this change from my work. I'll wait for all to approve and then if there are no issues or discussion points I shall make the change.

**Comment by peterg1t** [comment]
I have no preference over either type of license. If it encourages collaboration the change is welcome. :)

**Comment by SimonBiggs** [comment]
For reference here is the Apache license that I am proposing to use:

https://choosealicense.com/licenses/apache-2.0/

**Comment by Matthew-Jennings** [comment]
Wow!

Is CCA on board with this?

**Comment by Matthew-Jennings** [comment]
I think my opinion on the topic, though perhaps now milder in magnitude, remains the same: I'd welcome the Apache licence!

**Comment by SimonBiggs** [comment]
> Wow!
> 
> Is CCA on board with this?

Yup, approved.

**Comment by SimonBiggs** [comment]
Alrighty then :) If I get approval from @rembishj and @pchlap before the day is out I might make a `0.16.0` release tonight with the new license.

**Comment by pchlap** [comment]
> Alrighty then :) If I get approval from @rembishj and @pchlap before the day is out I might make a `0.16.0` release tonight with the new license.

Yep, more than happy to switch over to the Apache licence on my end.

**Comment by SimonBiggs** [comment]
@rembishj given the actual only contribution of yours that has currently been merged to master was `get_all_treatment_data` I moved that function out of master into your current pull request so that I can change master over to `Apache` this evening while I have the oportunity. Hope that's okay...

**Comment by SimonBiggs** [comment]
Undergone in `v0.16.0` https://github.com/pymedphys/pymedphys/releases/tag/v0.16.0

**Comment by rembishj** [comment]
Sorry for being late to the party, I have no issues with this!

**Comment by SimonBiggs** [comment]
Awesome :) Thanks @rembishj :).
