### ISSUE TITLE
Question about gamma_shell

### ISSUE THREAD

**Issue by lucasdbo** [pymedphys/pymedphys#700]
Hello,

I am using gamma_shell implementation in my research to evaluate dose distribution (np.array of float) generate by a deep artificial neural network. 
I am note sure to understand those parameters : coords_reference and coords_evaluation as a tuple. I also saw that elements of coords need to have the same length of matrix. And how does it include pixels sizes ? 
Thanks a lot

**Comment by SimonBiggs** [comment]
Hi @lucasdbo,

Let me write up a neat little example from raw numbers and put it up in the docs to see if that makes it easier to understand. I'll see if I can give that a shot this weekend.

Cheers,
Simon

**Comment by SimonBiggs** [comment]
@lucasdbo could you have a read through of https://docs.pymedphys.com/howto/gamma/effect-of-noise.html and let me know if that helps you understand how to use `pymedphys.gamma?

If not, I'm keen for some recommendations on how to improve it.

Cheers,
Simon

**Comment by lucasdbo** [comment]
@SimonBiggs thank you very much, your example is clear and I understand how to use pymedphys.gamma. This a precious help for my research.

Cheers,
Lucas

**Comment by SimonBiggs** [comment]
Brilliant :) glad to be able to help :)
