### ISSUE TITLE
BB finding algorithm falls apart with panel washed out FFF beams and large fields

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#727]
Further work required on the robustness of the BB finding algorithm.

**Comment by fishdda** [comment]
Hi Simon, 
Currently, BB finding algorithm is robust? I am usually using RIT software to find the BB and calculate the position error to identify the isocenter.

**Comment by SimonBiggs** [comment]
For BB position I would recommend using pylinac's version for the time being. Pylinac version 2.2.6 appears to have the most robust wlutz results this far.

In the future I expect that pymedphys will actually use both pylinac vs 2.2.6 and pylinac 3.x under the hood and compare the results to each other and flag if there is any deviations.

See the following issue for why I would not currently recommended using pylinac v 2.2.7 or 2.2.8 for bb finding:

https://github.com/jrkerns/pylinac/issues/268

**Comment by SimonBiggs** [comment]
The current pymedphys wlutz algorithm does well in many cases, and all the time it also does run pylinac 2.2.6 under the hood and raises an error if the difference is more that 0.2 mm.

Sometimes however the pymedphys implementation will often raise an error instead of returning a value of there is ever any uncertainty in its ability to provide a result.
