### ISSUE TITLE
Make attribution be alphabetical

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#74]
Heya @Centrus007,

I think we should make the attribution of developers and their companies be alphabetical. Alphabetical by first name of the contributor and then alphabetical by company first name.

I choose this method as there is already precedence for this style in the wild:

https://github.com/jupyterlab/jupyterlab#team

It can be mentioned as such that the team list is alphabetical.

**Comment by Centrus007** [comment]
I don't think I mind. Happy to defer to your preference :)

**Comment by SimonBiggs** [comment]
See https://github.com/pymedphys/pymedphys/pull/99
