### ISSUE TITLE
Build an inter-package testing ecosystem

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#768]
[EDIT]
This issue has been repurposed to track setting up pymedphys to be included in upstream libraries testing suites.
[/EDIT]

--------------

Here is a well structured and designed monorepo which contains within it Python libraries:

https://github.com/dagster-io/dagster

If we do want to allow user contributed sublibraries managed within this repo, that'd be the way to do it.

Out of interest, @pchlap, would you be interested in having your own library, designed to be a pymedphys plugin, where you are able to have complete reigns. You can still request reviews etc, and you can benefit from the continuous integration testing pipelines built into this repo, but as an extra, what you say goes within that package. Users would install it separately with pip should they choose.

**Comment by pchlap** [comment]
Interesting idea, so the code would still be contained in the repository? How would versioning be handled? Separately for each library?

I think that might be a cleaner option in the long run. However for the time being its not like we are getting in each others way. I'll need to make some more contributions before that would become a problem... :/

**Comment by SimonBiggs** [comment]
> Interesting idea, so the code would still be contained in the repository? How would versioning be handled? Separately for each library?

A good methodology for plugin libraries is to follow the same major version as the underlying library as much as possible (see https://github.com/deepmind/sonnet), but yes, each release would be separate and minor and patch versions would be separate (see https://semver.org/ for what I mean by major, minor, patch).

> I'll need to make some more contributions before that would become a problem

I've learnt when people take ownership of something they tend to be more involved. Part of this strategy of giving you ownership is to trial a framework where I manage the core infrastructure while explicitly giving ownership of sub-modules to others is to find a scalable way of having many people/departments truly involved. Naturally I imagine that each sub-module would be scoped by department (https://en.wikipedia.org/wiki/Conway%27s_law) that happens to have someone in a position to be able to take ownership of a department plugin.

The main benefit of having a department library plugin is every new release/commit of PyMedPhys will automatically run all the testing CI code of each department's software. That way new commits to PyMedPhys will be checked against department code making sure software that is used in each department isn't being broken by updates to PyMedPhys core. That way, software that breaks department code covered by tests within the monorepo won't get released.

**Comment by SimonBiggs** [comment]
@darcymason I've also had a thought, that potentially I could wrap up all the testing of PyMedPhys within the library itself, have all data be downloadable from Zenodo. I can then go through and flag any test that flexes pydicom's muscles and have it so that pytest can be run with a pydicom flag and that can be run within the pydicom repo. You can choose whether or not to action a failing test, but at least we can have an early alert if any commit breaks downstream code.

@jrkerns, I'm not yet directly depending on an installed version of pylinac, but I imagine it's only a matter of time. If you're keen I'd also be happy to set up a GitHub action on pylinac repo and flag tests that flex pylinac also.

Potentially the way we can connect up the medical physics software is by building a interconnected CI pipeline that gives a to the commit alert of software breakages all the way from the most core packages (pylinac, pydicom) all the way through to department code.

I'd be happy to set up and maintain this infrastructure.

**Comment by darcymason** [comment]
> pytest can be run with a pydicom flag and that can be run within the pydicom repo.

Sounds good.  Would definitely be good to know of any breaking ahead of time.  I've been dabbling a little in github actions so would be happy to do the last step of putting the new action in, if I have clear instructions on how to run the pymedphys tests with pydicom flag  ;-)

**Comment by SimonBiggs** [comment]
Awesome :). Also, I imagine, often a test breakage may not mean that that commit can't go ahead, it just might mean that the downstream developer get's pinged if that breakage needs to move forward so that they can make the appropriate changes, etc. As long as the downstream developer is on the ball, they could either pin the upstream package if needed, or adjust the code base so that the new breakage is accounted for and released before the upstream code lands.

**Comment by SimonBiggs** [comment]
@darcymason as a note, it'll be important that a line like the following is included within the GitHub action:

https://github.com/pymedphys/pymedphys/blob/master/.github/workflows/main.yml#L170-L173

That'll make it so that all testing data that is downloaded for the tests is cached from one action to the next. Testing data is not stored within the repo itself, instead it is saved on Zenodo, and then downloaded and cached to a `~/.pymedphys` directory on the test runner's machine.

**Comment by darcymason** [comment]
> That'll make it so that all testing data that is downloaded for the tests is cached from one action to the next

Sure, just keep an eye on it when I create the action, make sure my old brain didn't forget it.

**Comment by SimonBiggs** [comment]
Implemented within pydicom and the last two releases of pymedphys.
