### ISSUE TITLE
Monaco to Linac log file checking system

### ISSUE THREAD

**Issue by JacobMcAloney** [pymedphys/pymedphys#786]
As amazing as the icon comparison logfile printout is, the following would be nice:

- Patient name along with the ID and plan name
- Histogram of MU difference to go with the histogram of gamma result

**Comment by JacobMcAloney** [comment]
Also the voila widget tool is great, maybe another add-on to fallback to a DICOM RT plan file

**Comment by SimonBiggs** [comment]
Also wanted to add, should include the following:

* An indicator whether or not the iCOM listeners are currently running
* An indicator on when the most recent trf log file extraction and indexing occured
* The option to compare to trf file instead of iCOM

**Comment by SimonBiggs** [comment]
Make an "Advanced" tick box. Hide all the extra "physicsy" info until "Advanced" is ticked. Also, only show the "Monaco/iCOM/other" options when advanced is ticked.

**Comment by SimonBiggs** [comment]
Make the Gamma parameters able to be smaller

**Comment by SimonBiggs** [comment]
When using DICOM RT plan allow plans to be imported directly from Monaco's DICOM file export location.

**Comment by SimonBiggs** [comment]
Present MU for each field that is being selected. When multiple fields can be selected present the sum of the MU from each field at the end. Also present an MU diff after both evaluation and reference have been selected.

This info can be presented as a pandas table. Make a function "display deliveries" or something of the sort. Have it have columns such as total MU, number of control points, start and end gantry angle, start and end collimator angle. When fields are selected, present this after the selection.

**Comment by SimonBiggs** [comment]
Only make the error message of "No iCOM found" appear if a patient ID has been written in. Best to just remove the zfill to do this, and then show no error in patient ID of "" is provided.

**Comment by SimonBiggs** [comment]
* iCOM MU Density leaf/jaw limits (expand for the calc)
* figure squished (015094)
* rerunning MU density is not appropriately cached

**Comment by SimonBiggs** [comment]
* Make a note that static fields and CT are not supported
  * Raise a sensible error message
* Make field_id column bold, or even better make it the dataframe index
* Pandas dataframe widget not sufficiently high, reproduce and raise issue with streamlit -- appears to be due to Firefox, also the unnecessary height scroll is a little painful.

**Comment by SimonBiggs** [comment]
* Fail gracefully when patient name doesn't conform as expected.
* Raise an error when 0 control points are found in a tel file, mention that 3DCRT is not yet supported.
* Scale the mu density plots with the same vmax (with vmin=0). Do this so that the colours are comparable between the two.

**Comment by SimonBiggs** [comment]
* Change the testing to just Windows for now
* Refactor the internals of the tool, pull the functions out of main
* Store the data required for an automatic rerun within the outputs, a json file containing the input paths, as well as a reference and evaluation.zip containing the actual files used during that run.




Later
Make the testing cross platform
Make the Streamlit watcher also watch for changes either within the git repo, or within pymedphys. Using .gitignore to manage the watcher within the repo could be helpful.
- while I am at it, may as well watch the DICOM export directory and patient directory etc...

**Comment by SimonBiggs** [comment]
Tracking these items over at https://github.com/pymedphys/pymedphys/issues/825
