### ISSUE TITLE
patient anonymization tool for Unity Data from Elekta

### ISSUE THREAD

**Issue by fishdda** [pymedphys/pymedphys#817]
Hi Simon,
I am not sure if we have an anonymization tool for the raw data(FocalData) from Monaco especially for the Unity (MR-Linac)? I have a tool but I am not if it's helpful for the current project.

**Comment by SimonBiggs** [comment]
Hi @fishdda,

This would be quite a nice addition I believe. Maybe make a pull request to the labs?
