### ISSUE TITLE
Implement auto-contouring paper

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#82]
Being able to implement the following paper would seriously rock my socks:

https://arxiv.org/abs/1809.04430

**Comment by SimonBiggs** [comment]
Surface distance library:

https://github.com/deepmind/surface-distance

**Comment by SimonBiggs** [comment]
@sunyu0410 I remember you mentioned you were interested in implementing auto segmentation with machine learning.

The above paper has caught my interest. Would you be interested in working on this with me?

**Comment by SimonBiggs** [comment]
@rameshboggula you mentioned you would be interested in something like the above. How available do you think you might be for implementing the above paper with TensorFlow?

While we are working on the model we could undergo a process where we train the model at our local site, using our own segmentation training datasets and then only share the model. That way patient datasets need not be shared, but we can all benefit from a model that has been trained on a range of datasets.

**Comment by rameshboggula** [comment]
Good news is we have GitHub access now and the bad news is I am super busy
with MBA program :) Surely, I am interested in the tensorflow
implementation.

I think it’s a good idea just sharing the model and that’s all you need
anyways.

**Comment by SimonBiggs** [comment]
Marked this as a good Masters Project...

**Comment by sunyu0410** [comment]
> @sunyu0410 I remember you mentioned you were interested in implementing auto segmentation with machine learning.
> 
> The above paper has caught my interest. Would you be interested in working on this with me?

@SimonBiggs Thanks for the paper. I have to do the lecturing and supervision this semester so won't commit too much. But happy to work get in the discussion if you want to implement it. It should not be too hard if you use a deep learning library such as Keras or PyTorch.

**Comment by SimonBiggs** [comment]
I was thinking of potentially presenting this (and two other projects) as options for masters projects.

**Comment by sunyu0410** [comment]
> I was thinking of potentially presenting this (and two other projects) as options for masters projects to Annette

@SimonBiggs Could be a good project if the student knows the basics of neural networks. Otherwise, it's a good idea to give them some pre-training / reading beforehand.

**Comment by SimonBiggs** [comment]
Yup figured I'd be keen to focus on students who already were quite keen
and had focused on something like that in their own time already (maybe
doing a kaggle comp or something). If that student exists.

**Comment by SimonBiggs** [comment]
@pchlap I believe this paper by DeepMind might be neatly aligned to part of you PhD...

**Comment by SimonBiggs** [comment]
Their surface distance library looks like a nice way to provide weights for whether or not two contours agree https://github.com/deepmind/surface-distance

**Comment by SimonBiggs** [comment]
@mathewdeancooper to help you get to an MVP quickly, here is an example of an already available open source model with some example data:

https://github.com/NifTK/NiftyNetModelZoo/blob/master/dense_vnet_abdominal_ct_model_zoo.md

**Comment by SimonBiggs** [comment]
Two helpful guides on working with DICOM CT image files for segmentation purposes:

https://www.kaggle.com/asura93/full-preprocessing-tutorial
https://www.raddq.com/dicom-processing-segmentation-visualization-in-python/

Here is an example of me extracting DICOM segments and plotting them (it will take a while to load):

https://rawgit.com/SimonBiggs/brachytherapy-dicom-utilities/master/Displaying%20structure%20sets.html

**Comment by SimonBiggs** [comment]
Also, https://www.dicompyler.com/ is a great tool to initially have a scan through DICOM files before processing with Python.

**Comment by SimonBiggs** [comment]
@matthewdeancooper actually that link I provided (https://rawgit.com/SimonBiggs/brachytherapy-dicom-utilities/master/Displaying%20structure%20sets.html) uses the old pydicom API. You actually need to use:

```python
import pydicom
```

Instead of

```python
import dicom
```

**Comment by SimonBiggs** [comment]
@matthewdeancooper for the network structure, doing a bit more of a lit review myself it seems that after the DeepMind paper the following came out:

https://jingdongwang2017.github.io/Projects/HRNet/SemanticSegmentation.html
https://arxiv.org/pdf/1904.04514.pdf

That paper claims to have surpassed UNet for image segmentation tasks. That network + the DeepMind cost function might be quite the winning combination.

**Comment by matthewdeancooper** [comment]
This is a great example of why the skills learned by the development team
are the primary item of value cf. the code itself.

**Comment by SimonBiggs** [comment]
> This is a great example of why the skills learned by the development team are the primary item of value cf. the code itself.

To amplify that effect, I was a little concerned that every one of these recent papers used PyTorch, and the official implementation was in PyTorch only. So I searched a bit and found the following:

https://thegradient.pub/state-of-ml-frameworks-2019-pytorch-dominates-research-tensorflow-dominates-industry/

Currently I am downloading the following models for myself:

https://github.com/SimonBiggs/HRNet-Facial-Landmark-Detection

And I'm going to see if I can use those models as a pretrained model for Wlutz work I'm attempting. I figured given that pretrained models have been released for that network in PyTorch, I might be able to get results a lot quicker by bootstrapping my training with those models.

**Comment by SimonBiggs** [comment]
Ehh nvm, seems like they've hard coded in the need for using GPU. I think I'll just implement the paper in TensorFlow :).

**Comment by SimonBiggs** [comment]
@matthewdeancooper here is a colab instance downloading DeepMind's open dataset:

https://colab.research.google.com/drive/1LBYmDxCAGiwjJc5Tn_KMZSW8sDKgOP58

My plan is to merge your code into that notebook and see if I can get it working on tensor units on DeepMind's publicly available data.

**Comment by SimonBiggs** [comment]
> @matthewdeancooper here is a colab instance downloading DeepMind's open dataset:
> 
> [colab.research.google.com/drive/1LBYmDxCAGiwjJc5Tn_KMZSW8sDKgOP58](https://colab.research.google.com/drive/1LBYmDxCAGiwjJc5Tn_KMZSW8sDKgOP58)
> 
> My plan is to merge your code into that notebook and see if I can get it working on tensor units on DeepMind's publicly available data.

@matthewdeancooper try again, just make sure to run the first cells which install environment stuffs.

**Comment by matthewdeancooper** [comment]
Hey Simon, still trying to get things working on my end first before i look
too closely! Wondering why you structures the input data as (batch_size, x,
y, depth, 1) cf. to (batch, depth, x y, 1) ? This could be where im having
some issues.

Thank you though! Appreciate the help. I like how you have implemented the
args as a list to iterate over. Very neat!

Seeing Yu Sun tomorrow for coffee and will be back in Sydney for my
presentation on friday.

**Comment by SimonBiggs** [comment]
That choice of ordering was just to match the picture in my head. That's all. Batch on the far left, channel on the far right, and then [x, y, z] in the middle. That's all. I doubt that'd be the cause of the memory issue. I still did run into memory issues, not sure how much RAM the colab GPU's have, but I certainly did need to pull the batch size down and shrink the layers down as well as the channels.
