### ISSUE TITLE
Interactive PyOdide Course Built into the Documentation

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#838]
Discussions are currently underway to build a PyOdide + BlueprintJS Python for Medical Physics course within the tutorial documentation of PyMedPhys. Designed to be what is seen when one goes to the following page:

https://docs.pymedphys.com/tutes/index.html

My hope is to use Microsoft's Monaco Editor, as well as Palantir's Python Language Server, as well as BlueprintJS's tree widget for file management and its spreadsheet viewer for interactively working with tabulated data during the course. I want to design it to be run client side so that the user is free to use their own confidential patient data within the tutorial without the data leaving the confines of their client browser.

There has been a budget earmarked for this project in order to support training Medical Physicists in the use of Python within their clinics. It would support part of their professional development training.

I was asked if there is anyone that we might be able to enter into an agreement with to support the completion of this project. I thought you, @rth, would be a perfect person to contact regarding this, given your active involvement in pyodide. I also thought it might be worth a punt to reach out to @eferm, who I believe works at Palantir (and has recently put a star on pymedphys), and given the desire to build an open source PyOdide + BlueprintJS example that it may be worth thinking about working with someone at Palantir.

I do want to mention that this is most certainly in the investigation stage. This may not be approved in the end. But I thought I might test the water to help in our discussions internally.

Feel free to reach out to me at me@simonbiggs.net regarding this :).

Cheers,
Simon

**Comment by SimonBiggs** [comment]
Just as a note, a proof of principle of these technologies working together can be seen over at http://app.pymedphys.com/.

**Comment by rth** [comment]
It's a nice project idea!

> I was asked if there is anyone that we might be able to enter into an agreement with to support the completion of this project.

I can't make any promises for changes to pyodide in general, but we can certainly consider improvements/fixes to pyodide if they would benefit other pyodide users as well.
