### ISSUE TITLE
Using ReviewNB for Notebook reviewing

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#87]
Heya @Centrus007,

I thought you might be interested in the following tool which is helpful for reviewing notebook diffs on GitHub. I have copied in a link to one of your recent pull requests for perusal:

https://app.reviewnb.com/pymedphys/pymedphys/pull/81/files/

Cheers,
Simon

**Comment by Centrus007** [comment]
This is pretty nifty!

**Comment by SimonBiggs** [comment]
Certainly is :)
