### ISSUE TITLE
Propose renaming `labs` to `experimental`

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#908]
This makes the nature of the code in this region more explicit, and it comes into line with other libraries that follow the same style:

https://discuss.streamlit.io/t/adding-beta-and-experimental-channels-to-streamlit/2765
https://github.com/google/jax/tree/master/jax/experimental

**Comment by SimonBiggs** [comment]
@sjswerdloff, how about I make this change now so that when you release your CLI it can be released with the new name from the get go. That way you won't have to change your usage of it.

I'm expecting that the CLI will be something like:

```
pymedphys experimental dicom anonymise --pseudo /input/file.dcm -o /output/directory/
```

This experimental scope of `dicom anonymise` will import from the non-experimental version, so that it will act exactly the same, except have extra option(s) added. I can set this up for you if you like?

This will be designed with the aim to in the future drop the "experimental" scope once it's been put through its paces.

**Comment by SimonBiggs** [comment]
Heya @pchlap,

Are you okay with the name of `labs` changing to `experimental`? This will effect the pinnacle CLI usage. The intent is in the future to have both `experimental` and `beta` scopes so that when PyMedPhys goes to version `>= 1.0.0` portions of the CLI can be actively iterated on without needing to change the major version number of PyMedPhys. The name `experimental` is used in other libraries, so this brings us in line with what others are doing. It is also a much clearer name which has the name carry with it the warnings that should be inherent in that portion of PyMedPhys.

Let me know your thoughts. If needed I can make a pointer from `labs` through to `experimental` so that the CLI doesn't break for a few versions. But, given that it is the labs, personally I would prefer to be able to make a clean break and not have to have to manage a staged roll out.

**Comment by sjswerdloff** [comment]
Sure.  While that wasn't my initial design direction, that is how things will end up based on a refactoring approach.
Now that I know what is involved (from the work that went in to my draft PR), it's a lot easier for me to identify the refactorings that will result in the design implied by the CLI proposal below.

> @sjswerdloff, how about I make this change now so that when you release your CLI it can be released with the new name from the get go. That way you won't have to change your usage of it.
> 
> I'm expecting that the CLI will be something like:
> 
> ```
> pymedphys experimental dicom anonymise --pseudo /input/file.dcm -o /output/directory/
> ```
> 
> This experimental scope of `dicom anonymise` will import from the non-experimental version, so that it will act exactly the same, except have extra option(s) added. I can set this up for you if you like?
> 
I would be most grateful.
> This will be designed with the aim to in the future drop the "experimental" scope once it's been put through its paces.

Sounds good to me...

**Comment by SimonBiggs** [comment]
> > This experimental scope of `dicom anonymise` will import from the non-experimental version, so that it will act exactly the same, except have extra option(s) added. I can set this up for you if you like?
> 
> I would be most grateful.

Okay :)

So, I've done quite a hefty refactor to convert labs --> experimental. But as well as that I added in the following tid-bits:

https://github.com/pymedphys/pymedphys/blob/77e9c2970623954960ac1113001087ee7979b802/pymedphys/cli/experimental/dicom.py#L15-L31

https://github.com/pymedphys/pymedphys/blob/77e9c2970623954960ac1113001087ee7979b802/pymedphys/_experimental/pseudonymisation/__init__.py#L1-L8

That makes the CLI found within `pymedphys experimental dicom anonymise` be exactly the same as `pymedphys dicom anonymise` except with an additional flag `--pseudo`. Setting that flag will cause the following to be printed:

```
$ poetry run pymedphys experimental dicom anonymise boo.dcm --pseudo
Was run with pseudo!
<normal anonymisation stuff here>
```

Hopefully that will be a helpful little stub to build upon.

The pull request that contains that addition is over at https://github.com/pymedphys/pymedphys/pull/915. I still have a bit of a wack-a-mole before merging.

**Comment by SimonBiggs** [comment]
Heads up @pchlap, @db72-git, and @ayalalazaro,

In the pull request over at https://github.com/pymedphys/pymedphys/pull/915 I have renamed "labs" as "experimental". This carries through to CLI usage also. Commands that used to start with `pymedphys labs` now need to start with `pymedphys experimental`.

If there is dire need to set up backwards compatibility for a period of time I can make `pymedphys labs` point to `pymedphys experimental`. However given the nature of that part of the code base "no promises made" so to speak, I believe it should be okay to make a clean switch.

I wanted to give you guys a heads up.

Cheers,
Simon

**Comment by ayalalazaro** [comment]
Thanks for the explanation. I plan, however, as you pointed out, to build a test to qualify for non experimental. I just have to find the time.

Regards,

Rafael Ayala

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pchlap** [comment]
Thanks for the mention @SimonBiggs 

No problem here. I think anyone using Pinnacle code will be able to adapt to changes like this. No need for a pointer from labs to experimental :)

**Comment by SimonBiggs** [comment]
Thanks for that @pchlap and @ayalalazaro. :)

**Comment by db72-git** [comment]
Thanks for the heads up https://github.com/SimonBiggs

No problems at all for mine

**Comment by SimonBiggs** [comment]
> Thanks for the heads up [@SimonBiggs](https://github.com/SimonBiggs)
> 
> No problems at all for mine

Awesome :) Thanks @db72-git
