### ISSUE TITLE
ds vs dcm

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#91]
Heya @Centrus007,

I renamed `dcm_from_dict` to `ds_from_dict` following the convention, and then used it within the following file:

https://github.com/pymedphys/pymedphys/blob/master/tests/test_dicom/test_header_tweaks.py

I can't help but note that it feels less explicit... It's less clear to me that I am making a `pydicom` dataset structure. What do you think?

**Comment by Centrus007** [comment]
I'd say that the `ds` convention only really applies to _instances of a pydicom Dataset_.

The class name is `Dataset`, so the natural baseline instance name would be `dataset`. `dataset` is probably the preferred form in function names, etc. Readability is generally more affected by long variable names than long function names. I assume this is why pydicom opted for the `ds` (short for `dataset`) convention. Note that I cannot find a single example of `ds` being used for any other purpose than for `Dataset` instance variable names in pydicom. The form `dataset` seems to be preferred. E.g., see:

[`pydicom.filereader.read_dataset()`](https://pydicom.github.io/pydicom/stable/api_ref.html#pydicom.filereader.read_dataset)
[`pydicom.filereader.write_dataset()`](https://pydicom.github.io/pydicom/stable/api_ref.html#pydicom.filewriter.write_dataset)

Admittedly most of pydicom's functions are actually methods called on a `Dataset` instance, but I digress... 

---

A related aside:

The problem with `dicom`, `dcm`, etc. is that, although it is clear that you are dealing with DICOM _in some fashion_, the variable's type is unclear. Is it a pydicom dataset, or is it the filepath to the DICOM file? Or is it shorthand for the pydicom module (I've definitely seen `import pydicom as dcm`)?

Of course, `ds` itself has its own problems (theres nothing that implicitly suggests it's a *DICOM* dataset), but it *is* very clearly pydicom's convention. I'm not closed to the idea of breaking this convention if that's the consensus.

**Comment by SimonBiggs** [comment]
So have the function be called `pydicom_dataset_from_dict`

**Comment by Centrus007** [comment]
Something like that, yep!

Should we drop the `py` in `pydicom_dataset_from_dict`? It feels a little superfluous to me, and there are other kinda similar examples where we don't bother (e.g. `DicomDictBaseline` rather than `PyDicomDictBaseline`).

**Comment by SimonBiggs** [comment]
Yup, makes sense.

**Comment by SimonBiggs** [comment]
@msobolewski will like this solution :)

**Comment by SimonBiggs** [comment]
@Centrus007 Might we be able to change the usage of `ds` to `dataset` or `dicom_dataset` depending on the use case? Even within variable names?

...`ds` is bugging me...

**Comment by Centrus007** [comment]
Sure. :)
