### ISSUE TITLE
Deprecation warning ABCs from collections instead of from collections.abc, will fail in python 3.9

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#958]
Appears during testing with --run-only-slow
pymedphys/tests/dicom/test_anonymise.py::test_anonymise_dataset_and_all_is_anonymised_functions
  /home/osboxes/PythonProjects/pymedphys3/pymedphys/pymedphys/_vendor/apipkg/__init__.py:103: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    module = __import__(modpath, None, None, ["__doc__"])

it looks like the calling of the deprecated code is from an imported or perhaps "patched/imported" package

I didn't assign a label to this, should we have a "deprecation warning" label?

**Comment by SimonBiggs** [comment]
Ahh, we should fix this one up. Given it's vendored the issue won't just go
away with an upstream fix.

I'm happy for more detailed issue labelling and organisation.
