### ISSUE TITLE
Make Anonymise not create non-existent variables

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#963]
> Personally, I don't like replacing an empty value with a hardcoded anonymisation value. I don't think it makes the data any more anonymous and it risks interoperability issues or worse, DICOM conformance violation.
But one of the nice things about using the strategy (pattern) is substitution of an alternative strategy is straight forward. So a different strategy is "hardcode but don't replace empty values", and empty could be either "no value" or "empty string".
I tend to avoid changing things unless I know they are wrong, instead I tend to offer an alternative. One does end up with a lot of cruft after a while, but it avoids accidentally breaking things because someone had an expectation down the line that maybe they should not have.

_Originally posted by @sjswerdloff in https://github.com/pymedphys/pymedphys/pull/961/review_comment/create_

----

> One does end up with a lot of cruft after a while, but it avoids accidentally breaking things because someone had an expectation down the line that maybe they should not have.

At the moment, given we are version 0.*, we are quite free to break expectations, especially to improve code quality and keep cruft out. In the future, we are still free to break expectations, it just has to come with deprecation warnings and the like.

I think for PyMedPhys to continue to stand under its own weight into the future, given the size of the development team, we simply cannot afford to let cruft hang around.

I really like the pragmatic programmer book, on page 27 onwards he describes "software entropy" and how some teams manage to successfully combat it.

https://www.cin.ufpe.br/~cavmj/104The%20Pragmatic%20Programmer,%20From%20Journeyman%20To%20Master%20-%20Andrew%20Hunt,%20David%20Thomas%20-%20Addison%20Wesley%20-%201999.pdf#page=27

Excerpt:

> While software development is immune from almost all physical laws, entropy hits us hard.
Entropy is a term from physics that refers to the amount of "disorder" in a system.
Unfortunately, the laws of thermodynamics guarantee that the entropy in the universe
tends toward a maximum. When disorder increases in software, programmers call it
"software rot."
>
> There are many factors that can contribute to software rot. The most important one seems
to be the psychology, or culture, at work on a project. Even if you are a team of one, your
project's psychology can be a very delicate thing. Despite the best laid plans and the best
people, a project can still experience ruin and decay during its lifetime. Yet there are other
projects that, despite enormous difficulties and constant setbacks, successfully fight
nature's tendency toward disorder and manage to come out pretty well.
>
> What makes the difference?

-----

> Personally, I don't like replacing an empty value with a hardcoded anonymisation value. I don't think it makes the data any more anonymous and it risks interoperability issues or worse, DICOM conformance violation.

I agree, it has stepped beyond its task, a function shouldn't go and do more than one expects it to. And it is confusing that they appear when they weren't there before.

I say we remove it and put a note in the changelog to warn people as such.

_Originally posted by @SimonBiggs in https://github.com/pymedphys/pymedphys/pull/961/review_comment/create_

**Comment by SimonBiggs** [comment]
A further excerpt:

> Don't leave "broken windows" (bad designs, wrong decisions, or poor code) unrepaired. Fix
each one as soon as it is discovered. If there is insufficient time to fix it properly, then
board it up. Perhaps you can comment out the offending code, or display a "Not
Implemented" message, or substitute dummy data instead. Take some action to prevent
further damage and to show that you're on top of the situation.
>
> We've seen clean, functional systems deteriorate pretty quickly once windows start
breaking. There are other factors that can contribute to software rot, and we'll touch on
some of them elsewhere, but neglect accelerates the rot faster than any other factor.
>
> You may be thinking that no one has the time to go around cleaning up all the broken glass
of a project. If you continue to think like that, then you'd better plan on getting a dumpster,
or moving to another neighborhood. Don't let entropy win.

**Comment by sjswerdloff** [comment]
Not arguing about broken windows.
Just how to deal with what can turn out to be an implicit contract.
At 0.*, definitely free to change both implicit and explicit contracts.
The source of entropy I find dominant in legacy software that has become too ponderous to maintain is in the interfaces, or lack thereof.
The public interfaces here are clear.  The behaviour of a strategy just needs to be clearly defined in the documentation, and ideally enforced through unit/automated tests.

**Comment by SimonBiggs** [comment]
> The source of entropy I find dominant in legacy software that has become too ponderous to maintain is in the interfaces, or lack thereof.

Yeah that makes sense.
