### ISSUE TITLE
@pchlap Pinnacle experimental tools line command

### ISSUE THREAD

**Issue by SotiriStathakis** [pymedphys/pymedphys#973]
Hi Phillip,
Thank you for the Pinnacle tar to DICOM tool. It is very nice.

However, being a python and pymedphys novice, I have a few problems when I try running it in command line.
I was able to use the -m option and export only dose, plans and structures, but I have not been able to pause the script, read the available plans, select the one I need and export a specific trial within it.

Is there a way I can do this?

Thanks in advance

Sotiri

**Comment by SimonBiggs** [comment]
Just pinging @pchlap in the comments, I'm not sure if it works when it's put in the title...

**Comment by pchlap** [comment]
Hi @SotiriStathakis 
Thanks for your interest in the Pinnacle export tool. There is a description of how the command line interface works here: https://docs.pymedphys.com/ref/cli/pinnacle.html

You should be able to use --list or -l to list all of the plans and trials available. After that, you can select the plan with -p and the plan name, and the trial with -t and the trial name.

Give those a try and see how you go. Just let me know if you're still having trouble and I'm happy to help out further :)

**Comment by SotiriStathakis** [comment]
Hi @pchlap,
Thanks for the help. I used the command line with the -l option and the output is below. At the end exits with KeyError.
When I tried to modify it to  pymedphys experimental pinnacle export -o Z:\Physics\Pinnacle\Test -m RTSTRUCT -m RTDOSE -m RTPLAN -t COMPOSITE Z:\Physics\Pinnacle\Test\1310001.1.tar I got errors again. (see 2nd section below)

What am I doing wrong?

Thanks

Sotiri

C:\Users\vhastxsotirs>pymedphys experimental pinnacle export -o Z:\Physics\Pinnacle\Test -l Z:\Physics\Pinnacle\Test\1310001.1.tar
2020-08-10 08:04:52,596 - INFO - Extracting TAR archive to: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpp_xe6tlb
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Extracting TAR archive to: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpp_xe6tlb
2020-08-10 08:06:00,377 - INFO - Using Patient directory: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpp_xe6tlb\Institution_45\Mount_0\Patient_201
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Using Patient directory: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpp_xe6tlb\Institution_45\Mount_0\Patient_201
2020-08-10 08:06:00,378 - INFO - Plans and Trials:
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Plans and Trials:
2020-08-10 08:06:00,675 - INFO - ### PROSTATE FOSSA ###
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:### PROSTATE FOSSA ###
2020-08-10 08:06:11,633 - INFO - - FOSSA+LN
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:- FOSSA+LN
2020-08-10 08:06:11,634 - INFO - - BOOST
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:- BOOST
2020-08-10 08:06:11,635 - INFO - - COMPOSITE
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:- COMPOSITE
2020-08-10 08:06:11,635 - INFO - Images:
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Images:
Traceback (most recent call last):
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vhastxsotirs\AppData\Local\Programs\Python\Python38\Scripts\pymedphys.exe\__main__.py", line 7, in <module>
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\site-packages\pymedphys\cli\__init__.py", line 83, in pymedphys_cli
    args.func(args)
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\site-packages\pymedphys\_experimental\pinnacle\pinnacle_cli.py", line 137, in export_cli
    p.log_images()
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\site-packages\pymedphys\_experimental\pinnacle\pinnacle.py", line 278, in log_images
    image_header["series_UID"],
KeyError: 'series_UID'


==========================================================
C:\Users\vhastxsotirs>pymedphys experimental pinnacle export -o Z:\Physics\Pinnacle\Test -m RTSTRUCT -m RTDOSE -m RTPLAN -t COMPOSITE Z:\Physics\Pinnacle\Test\1310001.1.tar
2020-08-10 08:13:42,007 - INFO - Extracting TAR archive to: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpvtq90cn3
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Extracting TAR archive to: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpvtq90cn3
2020-08-10 08:14:36,540 - INFO - Using Patient directory: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpvtq90cn3\Institution_45\Mount_0\Patient_201
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Using Patient directory: C:\Users\VHASTX~3\AppData\Local\Temp\1\tmpvtq90cn3\Institution_45\Mount_0\Patient_201
2020-08-10 08:14:36,540 - INFO - Will export modalities: ['RTSTRUCT', 'RTDOSE', 'RTPLAN']
INFO:pymedphys._experimental.pinnacle.pinnacle_cli:Will export modalities: ['RTSTRUCT', 'RTDOSE', 'RTPLAN']
2020-08-10 08:14:36,789 - WARNING - No plan name supplied, selecting first plan: PROSTATE FOSSA
WARNING:pymedphys._experimental.pinnacle.pinnacle_cli:No plan name supplied, selecting first plan: PROSTATE FOSSA
Traceback (most recent call last):
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vhastxsotirs\AppData\Local\Programs\Python\Python38\Scripts\pymedphys.exe\__main__.py", line 7, in <module>
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\site-packages\pymedphys\cli\__init__.py", line 83, in pymedphys_cli
    args.func(args)
  File "c:\users\vhastxsotirs\appdata\local\programs\python\python38\lib\site-packages\pymedphys\_experimental\pinnacle\pinnacle_cli.py", line 166, in export_cli
    if not plan.set_active_trial(trial):
AttributeError: 'PinnaclePlan' object has no attribute 'set_active_trial'

**Comment by pchlap** [comment]
Hi @SotiriStathakis 

Hmmmm, this doesn't look like a problem with the commands you are using. More likely an issue with the pinnacle export tool.

What version of Pinnacle was used to generate that tar archive? I've only tested the tool on a few versions (mostly 9.x). Is that tar archive by chance something you can share (so only contains phantom/dummy data and absolutely no patient data)? If so, then you could share it with me and I can debug what is going wrong in the tool.

Cheers
Phil

**Comment by pchlap** [comment]
@SotiriStathakis , I'm just looking closer at that 2nd lot of debug output and there is definitely a bug in the command line tool there (when setting the trial). I will try to get a bug fix out for that in the next day or two for you.

**Comment by SotiriStathakis** [comment]
Hi @pchlap,
Thanks for looking into it. We are also working on the API and we have managed to export plans by selecting specific trials. We have a question: when selecting a trial is it possible to export all prescriptions within the trial. For example, when a trial has beams for phase 1 and boost. Within Pinnacle would be the Sum of selected prescriptions.

Thank you.

Sotiri

**Comment by SotiriStathakis** [comment]
Hi @pchlap,
We continue to work on the API. We figured out that within a trial all beams from multiple prescriptions are exported. However, we cannot change the active trial to be other than the first trial of a plan. 
When we are trying to set the active trial to be the second or third one inside the plan, it does not change. It seems that the active trial is set globally and we cannot change it. Not sure if I explain it correctly.

Sotiri

**Comment by SotiriStathakis** [comment]
Hi Philip @pchlap,
We solved the problem with the trial in the API. The dictionary was not updating the trial number we were selecting. We passed an update() to the trial number and it worked. 

Thank you for putting all this together.

Sotiri

**Comment by pchlap** [comment]
Thats great @SotiriStathakis , I'm glad you've got it working.

Yeah there are definitely still some issues with this code and no doubt there are improvements that could be made. If you do happen to solve something that's incorrect in the code, feel free to make a pull request to this repository. I can help you out with that if needed :) 

I'll fix up that command line issue with selecting the trial today.

Phil

**Comment by SimonBiggs** [comment]
Hi @SotiriStathakis,

@pchlap has undergone a fix for this and I have cut a development release that contains it. Would you be able to install the new version with:

```
pip install pymedphys==0.32.0dev6
```

And then test to see if the release has fixed the issue?

Cheers,
Simon

**Comment by medphys-trey** [comment]
I am kind of new the package and python. How do you run certain functions though python file instead of CLI. Thanks

**Comment by sjswerdloff** [comment]
> I am kind of new the package and python. How do you run certain functions though python file instead of CLI. Thanks

When I am trying to understand how to use the API of a package (or particular part of the package) I first start with the documentation:
https://docs.pymedphys.com/en/latest/
and assuming you are specifically interested in the pinnacle related functionality:
https://docs.pymedphys.com/en/latest/users/ref/lib/experimental/pinnacle.html

But if that doesn't provide enough information, I start looking at the automated tests.
Those have to invoke the same functionality, possibly at lower levels.
https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/tests/pinnacle/test_pinnacle.py

and if that isn't enough, it's time to go look directly at the source (because, after all, this is Open Source).
e.g.
in lib/pymedphys/_pinnacle/pinnacle.py

**Comment by medphys-trey** [comment]
I installed a ubuntu on windows and installed pymedphys package and download the test pinnacle file. It seems that I can run cli. However, after I enter "pymedphys experimental pinnacle export test_pinnacle_16.0.tar.gz -o /home/user". I got
![image](https://github.com/pymedphys/pymedphys/assets/109492301/77a1b97c-ca98-48a9-b8bc-946f87ff02c9)
